from pathlib import Path
import json,hashlib,html,sys
ROOT=Path.cwd();E=html.escape;stem='speaking-unit-5-behind-the-picture';media='/assets/img/english-intermediate-2/unit-5/behind-the-picture/'
rows=[
('01-door','Before the Door Opens','A person waits near a closed door with a folder.','An adult holding a folder checks a watch beside a closed door and empty chairs.',['waiting','nervous']),
('02-screen','A Surprise on the Screen','Two people react to something on a laptop.','Two adults look at a laptop; one smiles and the other raises a hand to their mouth.',['surprised','surprising']),
('03-seat','The Empty Seat','There are two drinks and one empty chair.','A woman sits at a cafe table with two drinks, a face-down phone and an empty chair.',['expecting','wondering']),
('04-presentation','After the Presentation','One person stands while others clap.','A student holds note cards beside a blank screen while classmates applaud.',['relieved','proud']),
('05-bag','Something in the Bag','Two friends look inside a bag.','Two friends look into an opaque gift bag; its contents are hidden.',['excited','exciting']),
('06-group','The Quiet Group Member','A group talks while one person listens.','Four adults work together; one listens quietly with an open notebook.',['thoughtful','concentrating']),
('07-community','Helping or Organizing?','People carry boxes and arrange supplies.','Adults carry boxes and arrange food packages at a community center.',['helpful','organized']),
('08-task','A Difficult Task','Two people work on an unfinished model.','Two adults examine loose parts of a partly built wooden model and illustrated instructions.',['confused','confusing']),
('09-arrival','An Unexpected Arrival','Someone arrives with a suitcase.','A person with a suitcase stands in a doorway as a friend rises from a sofa.',['unexpected','welcoming']),
('10-looking','What Are They Looking At?','A group looks at something outside the picture.','Three adults look off-frame in the same direction; one points, one smiles and one looks puzzled.',['interested','interesting'])
]
steps=[('Observe','What can you see?',['I can see','She is holding']),('Explain','What could be happening?',['She might be','He seems']),('Support','What clue supports your idea?',['I think this because','The picture suggests that']),('Respond','What does your partner think? How do you respond?',['That’s possible, but','I agree because'])]
extra=['They are standing','I think','Another explanation could be','Although','It could be','He must be','That can’t be']
checks=['We described something visible.','We suggested an explanation.','We supported our ideas with clues.','We listened and responded to each other.']
conversation=['I can see two drinks and an empty chair. She might be waiting for a friend because there are two cups.','That’s possible, but her friend might be ordering some food.','I agree. The empty chair doesn’t mean her friend hasn’t arrived.']
texts=list(dict.fromkeys([q for _,q,_ in steps]+[x for _,_,frames in steps for x in frames]+extra+[w for *_,words in rows for w in words]+conversation))
existing={}
for folder in ['unit-5-explanation','unit-5-grammar']:
 for a in json.loads((ROOT/'ingles/intermediate-2/audio'/folder/'models.json').read_text(encoding='utf-8'))['items']:existing[a['text']]='audio/'+folder+'/'+a['file']
dest=ROOT/'ingles/intermediate-2/audio/unit-5-picture';dest.mkdir(parents=True,exist_ok=True)
prior=json.loads((dest/'models.json').read_text(encoding='utf-8')) if (dest/'models.json').exists() else {'items':[]};old={x['text']:x for x in prior['items']};items=[];audio={}
for t in texts:
 if t in existing:audio[t]=existing[t];continue
 key=hashlib.sha256(t.encode()).hexdigest()[:14];item=dict(id=key,file=key+'.mp3',text=t,kind='phrase');item.update({k:old[t][k] for k in ('bytes','sha256') if t in old and k in old[t]});items.append(item);audio[t]='audio/unit-5-picture/'+item['file']
(dest/'models.json').write_text(json.dumps(dict(voiceId='EXAVITQu4vr4xnSDxMaL',modelId='eleven_multilingual_v2',items=items),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(dest/'scripts.md').write_text('# Behind the Picture · exact audio scripts\n\n'+'\n\n'.join(texts)+'\n',encoding='utf-8')
def say(t,starter=False):return '<button type="button" class="bp-say" data-audio="'+audio[t]+'" aria-pressed="false" aria-label="Listen: '+E(t)+'">'+E(t)+('…' if starter else '')+'<span aria-hidden="true"> ◖))</span></button>'
def prompts():return '<ol class="bp-questions">'+''.join('<li><strong>'+label+'</strong>'+say(q)+'</li>' for label,q,_ in steps)+'</ol>'
def support(words):return '<details class="bp-language"><summary>Useful language</summary><div class="bp-frames">'+''.join('<div><strong>'+label+'</strong>'+''.join(say(t,True) for t in frames)+'</div>' for label,_,frames in steps)+'</div><p class="bp-word-label">Words to consider</p><div class="bp-words">'+''.join(say(t) for t in words)+'</div><p class="bp-note">Use a word only if your interpretation supports it.</p></details>'
def checklist(i):return '<details class="bp-check"><summary>Check our conversation <span data-check-count="'+str(i)+'">0 / 4</span></summary>'+''.join('<label><input type="checkbox" data-check="'+str(i)+'-'+str(j)+'"/><span>'+E(t)+'</span></label>' for j,t in enumerate(checks))+'</details>'
scenes=[];cards=[]
for i,(slug,title,context,alt,words) in enumerate(rows):
 scenes.append(dict(id=i,slug=slug,title=title,context=context,alt=alt,words=words,image=media+slug+'.webp'))
 cards.append('<article class="bp-card" id="picture'+str(i+1)+'" data-card="'+str(i)+'"><div class="bp-card-head"><span>Picture '+str(i+1)+'</span><span data-complete="'+str(i)+'"></span></div><button type="button" class="bp-open" data-open="'+str(i)+'" aria-label="Open picture '+str(i+1)+': '+E(title)+'"><img src="'+media+slug+'.webp" alt="'+E(alt)+'" width="1536" height="1024" loading="lazy"/><span>Open picture ↗</span></button><div class="bp-copy"><h3>'+E(title)+'</h3><p class="bp-context">'+E(context)+'</p>'+prompts()+support(words)+checklist(i)+'</div></article>')
config=dict(scenes=scenes,steps=steps,audio=audio,checks=checks)
(ROOT/'assets/data/english-intermediate2-unit5-picture.json').write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
source=(ROOT/'ingles/intermediate-2/grammar-unit-5-read-the-clues.html').read_text(encoding='utf-8');head=source.split('<main>')[0].replace('Read the Clues | Unit 5 Grammar Practice','Behind the Picture | Unit 5 Speaking').replace('Ten illustrated questions on must, might and can’t, with clues, explanations and pronunciation.','Ten picture conversations: observe, explain, support your idea and respond to your partner.').replace('grammar-unit-5-read-the-clues',stem).replace('english-intermediate2-unit5-grammar.css?v=20260925-2','english-intermediate2-unit5-picture.css?v=20260925-1').replace('ie2-u5-grammar','ie2-u5-picture').replace('#grammarChallenge','\x23pictures').replace('Grammar challenge','Picture cards').replace('#quickGuide','#howTo').replace('Quick guide','How to play')
main='''<main>
<section class="ie2-grammar-hero" aria-labelledby="pageTitle"><div class="ie2-grammar-hero-copy"><p class="intermediate2-kicker">Practice Lab · Unit 5 · Pair speaking</p><h1 id="pageTitle">Behind the Picture</h1><p>What could be happening?<br>Look closely, share an idea and listen to another view.</p><div class="ie2-grammar-meta"><span>10 pictures</span><span>4 conversation steps</span><span>2 minutes per round</span></div><div class="intermediate2-actions"><a class="intermediate2-button primary" href="#pictures">Choose a picture</a><a class="intermediate2-button ghost" href="#howTo">How to play</a></div></div><figure><img src="IMAGE10" width="1536" height="1024" alt="Three people look at something outside the picture with different reactions" fetchpriority="high"/></figure></section>
<section class="ie2-grammar-shell bp-shell">
<section id="howTo" class="ie2-grammar-intro"><div><p class="intermediate2-kicker">Two partners · three pictures per session</p><h2>One picture. More than one explanation.</h2><p>Look together for 15 seconds. Partner A describes, explains and gives a clue. Partner B offers another idea and a clue. Partner A responds. Swap who starts in the next round.</p></div><aside><strong>Use evidence, not assumptions</strong><span>Different ideas can fit the same picture. Use might or could when you are not sure. Both partners speak.</span></aside></section>
<details class="bp-guide"><summary>Useful language · more ways to speak</summary><div class="bp-guide-grid">GUIDE</div><p>Use <b>must</b> or <b>can’t</b> only when strong clues support your deduction. A facial expression alone does not tell you exactly how someone feels.</p><p><a href="./unit-5-impressions-feelings-and-satire.html#ed-ing">Review feelings: -ed and -ing</a> · <a href="./unit-5-impressions-feelings-and-satire.html#modals">Review deductions</a></p></details>
<details class="bp-guide"><summary>Hear a sample conversation · Picture 3</summary><div class="bp-sample">SAMPLE</div><p>Use your own ideas when you play.</p></details>
<section class="bp-toolbar" aria-label="Picture and audio controls"><div><button type="button" class="intermediate2-button primary" data-random>Choose a random picture</button><button type="button" class="intermediate2-button" data-new-set hidden>Shuffle a new set</button><p data-deck-status role="status">10 unseen pictures in this set</p></div><div class="bp-audio-controls" role="group" aria-label="Pronunciation speed"><span>Audio</span><button type="button" data-speed="0.75" aria-pressed="true">0.75×</button><button type="button" data-speed="1" aria-pressed="false">1×</button><button type="button" data-stop-audio>Stop audio</button></div></section>
<section id="pictures" aria-labelledby="cardsTitle"><div class="bp-heading"><h2 id="cardsTitle">Choose your next conversation</h2><p id="discussionProgress" role="status">0 / 10 conversations checked</p></div><div class="bp-grid">CARDS</div></section>
<p class="bp-note">Practice in class · Checks stay on this page until you reload. No recording or submission is needed.</p><div class="intermediate2-actions"><a class="intermediate2-button primary" href="./practice-lab.html#unit-5-folder">Back to Practice Lab</a><a class="intermediate2-button" href="./unit-5-impressions-feelings-and-satire.html">Review Unit 5</a></div>
</section></main>
<dialog id="bpProjector" aria-labelledby="bpTitle"><header class="bp-project-header"><span id="bpRound">Picture conversation</span><div><button type="button" data-fullscreen>Full screen</button><button type="button" data-close autofocus>Close ×</button></div></header><div class="bp-project-stage"><figure><img id="bpImage" alt=""/><figcaption id="bpImageStatus" role="status"></figcaption></figure><section class="bp-project-copy"><h2 id="bpTitle"></h2><p id="bpContext"></p><div id="bpPrompts">PROMPTS</div><div id="bpSupport"></div><section class="bp-timer" aria-label="Optional two-minute conversation timer"><div><span>Optional timer</span><strong data-time role="timer" aria-label="Time remaining">2:00</strong></div><div class="bp-timer-buttons"><button type="button" data-timer-toggle>Start</button><button type="button" data-timer-reset>Reset</button></div><p id="bpTimerStatus" role="status">Look together first. Start when you are ready to speak.</p></section><div id="bpCheck"></div></section></div><footer class="bp-project-footer"><div class="bp-nav"><button type="button" data-prev>← Previous</button><button type="button" data-next>Next →</button></div><div class="bp-audio-controls" role="group" aria-label="Projection audio speed"><button type="button" data-speed="0.75" aria-pressed="true">0.75×</button><button type="button" data-speed="1" aria-pressed="false">1×</button><button type="button" data-stop-audio>Stop audio</button></div><div><button type="button" data-random>Random picture</button><button type="button" data-new-set hidden>Shuffle a new set</button><span data-deck-status>10 unseen pictures in this set</span></div></footer></dialog>
<footer class="site-footer"><p>&copy; 2026 JaraLingua. Intermediate English Course 2 Practice Lab.</p></footer><script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20260919-local-login"></script><script src="../../assets/js/english-intermediate2-unit5-picture.js?v=20260925-1"></script><script src="/assets/js/course-switcher.js"></script><script src="/assets/js/page-qr-access.js"></script></body></html>
'''
guide=''.join('<div><h3>'+label+'</h3>'+''.join(say(t,True) for t in frames)+'</div>' for label,_,frames in steps)+'<div class="bp-more"><h3>More options</h3>'+''.join(say(t,True) for t in extra)+'</div>'
main=main.replace('IMAGE10',scenes[9]['image']).replace('GUIDE',guide).replace('SAMPLE',''.join('<p><b>Partner '+('B' if i==1 else 'A')+'</b><br>'+say(t)+'</p>' for i,t in enumerate(conversation))).replace('CARDS',''.join(cards)).replace('PROMPTS',prompts())
(ROOT/'ingles/intermediate-2'/f'{stem}.html').write_text(head+main,encoding='utf-8')
sys.path.insert(0,str(ROOT/'tmp/unit5-explanation/python-deps'));import qrcode,qrcode.image.svg
qrcode.make('https://www.jaralingua.com/ingles/intermediate-2/'+stem+'.html',image_factory=qrcode.image.svg.SvgPathImage,box_size=10,border=4).save(ROOT/'assets/img/page-qr'/('ingles-intermediate-2-'+stem+'.svg'))
p=ROOT/'assets/js/english-intermediate2-unit5-picture.js'
if p.exists():
 js=p.read_text(encoding='utf-8');start=js.index('const config=');end=js.index('\nconst $=',start);p.write_text(js[:start]+'const config='+json.dumps(config,ensure_ascii=False)+';'+js[end:],encoding='utf-8')
print('Built 10 cards and QR;',len(items),'new audio models;',len(texts)-len(items),'existing audio models reused.')
