"""Build the private-practice Unit 6 vocabulary and oral rehearsal game."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
PAGE='practice-unit-6-news-quest.html'
base=(ROOT/'ingles/intermediate-2/vocabulary-unit-6-greenford-news.html').read_text()
head=base.split('<main>')[0].replace('ie2-newsroom-page','ie2-quest-page').replace('#newsroom','#quest')
head=re.sub(r'<title>.*?</title>','<title>News Quest · Vocabulary and Speaking | Intermediate English Course 2</title>',head)
head=re.sub(r'<meta name="description"[^>]+>','<meta name="description" content="Practise twelve news words with picture and listening challenges, ElevenLabs models and private speaking rehearsal."/>',head)
head=re.sub(r'<link rel="stylesheet" href="[^"]*english-intermediate2-newsroom.css[^"]*"/>','<link rel="stylesheet" href="../../assets/css/english-intermediate2-news-quest.css?v=20261009-1"/>',head)
body='''<main>
<section class="u4-hero" aria-labelledby="quest-title"><img class="u4-hero-image" src="/assets/img/english-intermediate-2/unit-6/newsroom/reporter-v1.webp" alt="A reporter presents news from Greenford" width="1536" height="1024"/><div class="u4-hero-inner"><div class="ie2-unit4-hero-copy"><p class="intermediate2-kicker">Unit 6 · Practice Lab</p><h1 id="quest-title">News Quest</h1><p>See it. Hear it. Say it.</p><div class="ie2-overview-chips"><span>12 news words</span><span>Vocabulary + speaking</span><span>Private practice</span></div></div></div></section>
<section id="quest" class="quest-shell" aria-label="News Quest activity">
<p id="quest-loading" role="status">Loading your challenges…</p><button id="quest-load-retry" type="button" hidden>Try loading again</button>
<noscript>Please enable JavaScript to use this activity.</noscript>
<div id="quest-app" hidden>
<div class="quest-toolbar"><a href="./practice-lab.html#unit-6-folder">← Practice Lab</a><div><label><input type="checkbox" id="quest-voice" checked/> Voice</label><label><input type="checkbox" id="quest-effects" checked/> Effects</label><button type="button" id="quest-stop-audio">Stop audio</button><label>Speed <select id="quest-speed"><option value="1">1×</option><option value="0.75">0.75×</option></select></label></div></div>
<section id="quest-intro" class="quest-panel"><p class="quest-eyebrow">Your next challenge</p><h2>Build your news vocabulary</h2><p>24 picture and listening challenges + 12 short speaking turns. Difficult words return for another try. Take your time; there are no lives to lose.</p><div class="quest-actions"><button type="button" class="quest-primary" id="quest-start">Start my quest →</button><button type="button" id="quest-preview">Review the 12 words</button></div><details class="quest-help"><summary>How speaking practice works</summary><p>Listen, record, hear yourself and compare with the model. Each word has a pronunciation tip. You choose whether you feel ready or need more practice; this is not an automatic pronunciation score.</p><p>Recordings stay in this tab, are replaced on retry and are cleared when you move on. Nothing is uploaded or sent to your teacher. You can also repeat aloud without a microphone or skip a speaking turn.</p></details></section>
<section id="quest-review" class="quest-panel" hidden><div class="quest-row"><h2>Meet the words</h2><button type="button" id="quest-review-close">Back</button></div><p>Hover or focus on a word for Spanish; tap or click to hear it.</p><div id="quest-cards"></div></section>
<section id="quest-game" class="quest-panel" hidden aria-label="Current challenge"><div class="quest-row"><span id="quest-count"></span><span id="quest-type" class="quest-tag"></span></div><progress id="quest-progress" max="36" value="0" aria-label="Challenges completed"></progress><div class="quest-row"><h2 id="quest-prompt" tabindex="-1"></h2><button type="button" id="quest-repeat-question">↻ Repeat question</button></div><div id="quest-stimulus"></div><div id="quest-model-controls" class="quest-actions"><button type="button" id="quest-listen">▶ Listen</button><button type="button" id="quest-slow">▶ Listen slowly</button></div><fieldset id="quest-options"><legend class="quest-sr">Choose one answer</legend><div id="quest-choices"></div></fieldset>
<div id="quest-speaking" hidden><div id="quest-speech-model"></div><button type="button" id="quest-reveal">Reveal the word and model</button><p id="quest-tip"></p><div class="quest-actions"><button type="button" id="quest-record" class="quest-primary">● Record my voice</button><button type="button" id="quest-record-stop" disabled>Stop recording</button><button type="button" id="quest-aloud">Repeat without a microphone</button></div><div class="quest-meter"><meter id="quest-level" min="0" max="1" value="0" aria-label="Microphone input level"></meter><span id="quest-timer">0 / 10 s</span></div><p id="quest-mic-status" role="status" aria-live="polite">Your recording stays in this tab. No automatic pronunciation score.</p><audio id="quest-recording" controls hidden aria-label="Hear my recording"></audio><div id="quest-self-check" hidden><p>Compare with the model. Listen for the sound or stress in the tip above.</p><div class="quest-actions"><button type="button" data-self="ready">I feel ready ✓</button><button type="button" data-self="practice">I need more practice ↻</button></div></div><button type="button" class="quest-link" id="quest-skip">Skip speaking for now</button></div>
<div id="quest-feedback" role="status" aria-live="polite"></div><div class="quest-actions quest-footer"><button type="button" class="quest-primary" id="quest-check" disabled>Check</button><button type="button" id="quest-retry" hidden>Try again</button><button type="button" class="quest-primary" id="quest-next" hidden>Continue →</button></div></section>
<section id="quest-results" class="quest-panel" hidden><p class="quest-eyebrow">Practice complete</p><h2 tabindex="-1" id="quest-finish-title">Your news vocabulary is growing</h2><div id="quest-summary"></div><h3>Words to revisit</h3><div id="quest-difficult"></div><div class="quest-actions"><button type="button" class="quest-primary" id="quest-practise-difficult">Practise my difficult words</button><button type="button" id="quest-phrases">Speak in sentences</button><button type="button" id="quest-restart">New quest</button></div><p class="quest-small">Vocabulary results are practice feedback. Speaking reflections are your own, not a pronunciation grade.</p></section>
<p id="quest-audio-status" role="status" aria-live="polite"></p><a class="quest-story-link" href="./vocabulary-unit-6-greenford-news.html">Revisit the Greenford News story →</a>
</div></section></main><footer class="site-footer"><p>JaraLingua · Intermediate English Course 2</p></footer>
<script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20261003-persistent-signin"></script><script src="../../assets/js/english-intermediate2-news-quest.js?v=20261009-2"></script><script src="/assets/js/course-switcher.js"></script></body></html>'''
(ROOT/'ingles/intermediate-2'/PAGE).write_text(head+body)
print('Built '+PAGE)
