"""Build the five-scene opinion coach and its canonical public audio scripts."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
DEST=ROOT/'ingles/intermediate-2/audio/unit-6-opinion-coach'
scripts={}
def say(id,text,mood='curious'):
 file=id+'.mp3'; scripts[file]={'file':file,'text':text,'delivery':mood};return {'file':file,'text':text}
def question(id,scene,kind,text,frames,examples,vocab,grammar):
 return dict(id=id,sceneId=scene,kind=kind,topic=('Let’s meet' if not scene else f'Scene {scene} · '+kind.title()),text=text,audio=say(id,text)['file'],frames=frames,examples=[say(id+'-example-'+str(i+1),t,'calm') for i,t in enumerate(examples)],vocabulary=vocab,grammar=grammar,checks=[dict(label='your idea',kind='word-count',minMatches=3)],improved=examples[0],minWords=3,maxSeconds=50)
scenes=[
 dict(id=1,slug='photo-context',title='The full picture',alt='A phone crops a man carrying boxes; the wider scene shows him handing supplies to a volunteer at a relief table.',observe="Let's look at our first picture! What can you see on the phone and in the full scene?",interpret='What does it look like the man is doing?',opinion='Could this photo make people judge the man unfairly? Why or why not?',predict='What might happen if someone shares only the cropped photo?',terms=['photo','supplies','volunteer','evidence','misleading'],examples=[['I can see a man with boxes on the phone. In the full scene, a volunteer is receiving the boxes.','There are families near a table with water and blankets.'],['It looks like he is delivering supplies to the shelter.','He seems to be helping, but the cropped photo does not show the whole situation.'],['I think the photo could mislead people because it hides the volunteer receiving the boxes.','I would not judge him from this photo because there is not enough evidence.']],detail='Look at the boxes, the open van and the volunteer. Which detail supports your impression?',reaction='The small photo leaves out the people receiving the boxes. Your interpretation needs that wider context.'),
 dict(id=2,slug='unverified-warning',title='Before you share',alt='Three students look at an anonymous flood warning on a phone and a weather map on a laptop, with rain outside.',observe="Here's a different situation. What can you see on the phone and the laptop?",interpret='Look at the student holding the phone. How does she seem to feel?',opinion='Would you share this warning now or check it first? Explain your choice.',predict='What might happen after the student makes that choice?',terms=['warning','source','share','check','worried'],examples=[['I can see a warning on a phone and a weather map on a laptop.','Three students are looking at the screens, and it is raining outside.'],['She looks worried because she is looking carefully at the warning.','She seems unsure about what to do next.'],['I would check the source first because a false warning could frighten people.','I might share it with a clear note that it is unverified because people may need time to prepare.']],detail='Look at her face and the two screens. What visible detail supports your impression?',reaction='We can see a warning, but the picture does not establish whether it is reliable.'),
 dict(id=3,slug='help-or-film',title='A phone in an emergency',alt='A person films while neighbors carry a chair and belongings out of a muddy home; an older adult sits safely nearby.',observe="Now we're outside. What are the people in this street doing?",interpret='What does it look like the person in the yellow raincoat is trying to do?',opinion='Do you think filming is useful or harmful in this situation? Explain your opinion.',predict='What might change if the person puts the phone away?',terms=['film','rescue crew','damage','help','might'],examples=[['Some people are carrying a chair, and another person is filming.','I can see muddy walls, bags and an older person sitting near a dog.'],['It looks like the person is recording the damage.','They might be asking for help, but we cannot know that from the image alone.'],['Filming could help show what the families need, as long as it does not get in the way.','I think helping directly is more useful here because the neighbors are carrying heavy things.']],detail='Which detail in the image supports your idea about the person filming?',reaction='The phone is visible. The reason for filming is something we have to infer.'),
 dict(id=4,slug='limited-supplies',title='Enough for everyone?',alt='A thoughtful volunteer stands behind three small supply boxes, water and blankets while families wait in a shelter with nearly empty shelves.',observe="Let's step inside the shelter. What is on the table, and who is waiting?",interpret='Look at the volunteer behind the table. How does she seem to feel?',opinion='If you were this volunteer, how would you distribute the supplies fairly?',predict='How might the families react to your plan?',terms=['shelter','supplies','blankets','fairly','seems'],examples=[['There are three small boxes, water bottles and blankets on the table. Several families are waiting.','I can see a volunteer, a child, an older adult and a person in a wheelchair.'],['She seems worried because there are few supplies and several people waiting.','She looks thoughtful. She might be planning how to share the supplies.'],['I would ask what each person needs and explain how the supplies will be shared.','I would give everyone some water first, then check who needs extra support.']],detail='What can you see in her expression or around the table that supports your impression?',reaction='We can see limited supplies and several people waiting. Their exact needs are not all visible.'),
 dict(id=5,slug='unequal-coverage',title='Whose story gets heard?',alt='Two similarly flood-damaged communities side by side: reporters interview residents on the left; residents clean without reporters on the right.',observe="One last picture! What is similar, and what is different, between these communities?",interpret='How do you think the people without reporters might feel?',opinion='Should reporters give these communities the same attention? Explain your view.',predict='What might happen if one community remains out of the news?',terms=['reporter','attention','community','damage','seems'],examples=[['Both communities have flood damage, but only one has reporters.','People are cleaning in both places. On the left, a camera operator is filming an interview.'],['They might feel ignored because no reporters are there.','They may feel focused on cleaning. We cannot be sure of their feelings.'],['I think both deserve attention because both communities need help.','I would compare their needs before deciding how much coverage each should receive.']],detail='Which detail supports your interpretation, and what can the image not tell us?',reaction='Both scenes show damage. The different coverage does not tell us the full needs of either community.')]
questions=[question('hello',None,'hello',"Hi! I'm David. It's good to see you! What's your name?",['My name is ___. Nice to meet you!'],['Hi, David! My name is Ana.'],['nice to meet you'],'Your name is not assessed. You can correct the transcription.')]
questions[0].update(unscored=True,minWords=1,maxSeconds=20)
follow={}
for scene in scenes:
 n=scene['id'];scene['image']='/assets/img/english-intermediate-2/unit-6/opinion-coach/'+scene['slug']+'-v1.webp'
 for i,kind in enumerate(['observe','interpret','opinion']):
  frames={'observe':['I can see ___.','There is / There are ___.'],'interpret':['She / He looks ___ because ___.','It looks like ___ is / are ___.','They seem to be ___.'],'opinion':['In my opinion, ___ because ___.','It depends on ___. For example, ___.']}[kind]
  grammar={'observe':'Describe visible people, objects and actions before guessing.','interpret':'Looks + adjective: she looks worried. Looks like + clause: it looks like she needs help. Seems to be + action: she seems to be waiting.','opinion':'Your position is yours. Give a reason, then an example. There is no single correct opinion.'}[kind]
  q=question(f's{n}-{kind}',n,kind,scene[kind],frames,scene['examples'][i],scene['terms'],grammar)
  if kind=='interpret':q['alternative']=dict(text=scene['detail'],audio=say(f's{n}-evidence',scene['detail'])['file'])
  if kind=='opinion':
   q['followUpSet']=str(n)
   follow[str(n)]={}
   for k,t in [('reason','What is your main reason for that choice?'),('prediction',scene['predict'])]:
    follow[str(n)][k]=question(f's{n}-{k}',n,k,t,['My main reason is ___.'] if k=='reason' else ['They might ___ because ___.'],[['My main reason is that the small photo leaves out important context.','My main reason is that people need reliable information.','My main reason is that filming can show what help is needed.','My main reason is that everyone should have access to essential supplies.','My main reason is that both communities need to be heard.'][n-1]] if k=='reason' else [['People might misunderstand the man and accuse him unfairly.','Some people might prepare for a flood, while others might check the source.','The person might help carry the furniture instead.','Some families might appreciate the plan, but others may ask for more supplies.','The community might receive less support because fewer people hear its story.'][n-1]],scene['terms'],'Explain your own idea. A prediction is a possibility, not a fact.')
  questions.append(q)
 scene['reaction']=say(f's{n}-reaction',scene['reaction'],'thoughtful')
replies={}
for id,text,mood in [
 ('hello',"Nice to meet you! I'm glad you're here. Let's explore these pictures together!",'warm'),
 ('observe','Thanks for describing what you noticed. Let’s look a little more closely.','warm'),
 ('inference','That is one possible interpretation. Remember, an impression is not a fact.','thoughtful'),
 ('uncertain',"It's okay to be unsure! Try one possibility with, it looks like, or, it seems.",'encouraging'),
 ('reason','You have given a reason for your view. Let’s think about what could happen next.','thoughtful'),
 ('opinion','I hear your point. Let’s explore the reason behind it.','curious'),
 ('followup','Thanks for developing your idea. You can bring that perspective to the round table!','warm'),
 ('clarify',"I'm not sure I understood your idea about this picture. Try naming one visible detail, or open Help me answer.",'gentle'),
 ('correction-looks','A small language tip: say, she looks worried, without like before the adjective. Try that pattern with your own idea.','gentle'),
 ('correction-agree','A small language tip: the phrase, I am agree, is not correct. Say, I agree. Your opinion can stay the same!','gentle'),
 ('correction-seems','A small language tip: say, she seems to be helping. Use seems to be before an action ending in ing.','gentle'),
 ('not-worried','You do not see worry in that expression. That is possible; a picture can support more than one interpretation.','thoughtful'),
 ('worried','You mentioned worry. Remember to connect that impression to a detail you can see.','thoughtful'),
 ('share','Sharing quickly can have consequences. The source and the uncertainty are part of this decision.','thoughtful'),
 ('check','Checking a source takes time, and reliability matters. Think about how you would explain your choice.','thoughtful'),
 ('both','You are considering more than one possibility. That can help you explain a balanced opinion.','warm'),
 ('question',"For this activity, use the image and give your own opinion. You can open the help for language or listen to the question again.",'gentle'),
 ('return','Now, let’s come back to the question on screen.','warm'),
 ('no-speech',"I couldn't hear a clear answer. Check your microphone, and let's try again.",'gentle'),
 ('service',"I couldn't get your words this time. Please retry the analysis, or continue without feedback.",'gentle'),
 ('closing',"Thanks for sharing your ideas! In the round table, listen to your classmates, explain your reasons, and remember: different opinions can help us think. See you soon!",'warm'),
 ('welcome',"Hi there! I'm David. Five pictures, five big questions, and your own ideas! We'll describe what we see, explore what it might mean, and share opinions. Ready? Let's talk!",'warm'),
 ('instructions',"Listen to one question at a time. Record your answer, then hear my reply. Open Help me answer if you need a start or an example. Click the picture to see more detail. You can skip a turn and come back later.",'warm')]: replies[id]=say('reply-'+id,text,mood)
terms={'photo':'foto','supplies':'suministros','volunteer':'voluntario o voluntaria','evidence':'evidencia; pruebas','misleading':'engañoso; que da una impresión equivocada','warning':'alerta; advertencia','source':'fuente de información','share':'compartir','check':'comprobar; verificar','worried':'preocupado o preocupada','film':'grabar un video','rescue crew':'equipo de rescate','damage':'daños','help':'ayudar; ayuda','might':'podría; expresa posibilidad','shelter':'refugio','blankets':'mantas; cobijas','fairly':'de manera justa','seems':'parece','reporter':'reportero o reportera','attention':'atención','community':'comunidad','nice to meet you':'mucho gusto'}
news=json.loads((ROOT/'assets/data/english-intermediate2-news-quest.json').read_text())['words']
vocab={}
for term,meaning in terms.items():
 old=next((w for w in news if w['term']==term),None)
 vocab[term]={'spanish':meaning,'audio':old['audio'] if old else 'audio/unit-6-opinion-coach/'+say('word-'+term.replace(' ','-'),term,'clear')['file']}
c=dict(id='english-intermediate-2-unit-6-opinion',language='en',locale='en-US',apiPath='/api/english-intermediate/pronunciation-assessment',storageKey='jaralingua:intermediate2:opinion:v1',persistHistory=False,courseLabel='Intermediate English Course 2',unitLabel='Unit 6',title='My opinion matters',audioRoot='audio/unit-6-opinion-coach/',attemptQuestionCount=len(questions),maxRecordingSeconds=50,character=dict(name='David Rivera',role='Your conversation coach',portrait='../../assets/img/english-intermediate-2/unit-5/david-coach/david.png'),questions=questions,followUpSets=follow,mandatoryQuestionIds=[q['id'] for q in questions],selectionGroups=[],scenes=scenes,wordHelp=vocab,replies=replies,voice=dict(id='pv8WYYW60prEkDbDXyC0',name='David',category='cloned',modelId='eleven_v3'),audio=dict(welcome=replies['welcome']['file'],instructions=replies['instructions']['file'],needDetail=replies['clarify'],noSpeech=replies['no-speech'],serviceRecovery=replies['service'],closing=replies['closing']),returnToPrompt=replies['return'],strictConfidence=True,rubric=[],feedbackRules=[],ui=dict(autoClosing=True,alwaysAllowNext=True,immediatePrompt=True,supportStartsClosed=True,hideRealSupport=True,floatingDock=False,compactFeedback=True,collapseFeedback=True,acknowledgeBeforeFollowUp=True,supportLabel='Sentence starters, examples and vocabulary',summaryLeadComplete='You explored five perspectives for the round table.'))
(ROOT/'assets/js/conversation-coach-data/english-intermediate-2-unit-6-opinion.js').write_text('window.JaraLinguaConversationCoachConfig = '+json.dumps(c,ensure_ascii=False,indent=2)+';\n')
DEST.mkdir(parents=True,exist_ok=True)
old=json.loads((DEST/'models.json').read_text()) if (DEST/'models.json').exists() else {'items':[]}
for item in scripts.values():
 # V3 direction tags affect delivery, never the visible learning transcript.
 tag={'warm':'[warmly]','curious':'[curious]','thoughtful':'[thoughtful]','gentle':'[gently]','encouraging':'[encouraging]','calm':'','clear':''}[item['delivery']]
 item['generationText']=(tag+' '+item['text']).strip()
 item['voiceSettings']={'stability':.5,'similarity_boost':.8}
 if item['file'] in ['s3-observe.mp3','s4-opinion-example-2.mp3','word-seems.mp3','reply-correction-agree.mp3']:
  item['modelId']='eleven_multilingual_v2';item['generationText']=item['text'];item['voiceSettings']={'stability':.6,'similarity_boost':.8,'style':.3,'use_speaker_boost':True}
 prior=next((x for x in old['items'] if x.get('generationText')==item['generationText'] and x.get('modelId')==item.get('modelId') and x['file']==item['file']),{})
 item.update({k:prior[k] for k in ['bytes','sha256'] if k in prior})
(DEST/'models.json').write_text(json.dumps(dict(voiceId=c['voice']['id'],voiceName='David',modelId='eleven_v3',authorization='Existing owner authorization for David cloned voice; expressive coaching requested 2026-10-09.',items=list(scripts.values())),ensure_ascii=False,indent=2)+'\n')
print(len(questions),'main turns;',len(scripts),'audio clips')
