"""Build the static Unit 4 lesson and its canonical audio inventory."""
from pathlib import Path
from html import escape as esc
import json
import re

ROOT = Path(__file__).resolve().parents[1]
COURSE = ROOT / 'ingles/intermediate-2'
ASSETS = '../../assets/img/english-intermediate-2/unit-4/explanation/'
audio_models = []
parts = []

def p(text): return f'<p>{text}</p>'
def model(text): return f'<p class="u4-model">{text}</p>'
def note(title, text): return f'<aside class="u4-note"><strong>{title}</strong><p>{text}</p></aside>'
def grid(items): return f'<div class="u4-grid u4-grid-{len(items)}">' + ''.join(f'<article class="u4-card"><h3>{t}</h3>{b}</article>' for t,b in items) + '</div>'
def table(head, rows):
    return '<div class="u4-table" role="region" aria-label="'+esc(' / '.join(head))+'" tabindex="0"><table><thead><tr>'+''.join(f'<th scope="col">{h}</th>' for h in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{c}</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def audio(slug, title, text):
    audio_models.append({'file':slug+'.mp3','title':title,'text':text})
    return f'''<div class="u4-audio"><strong>{title}</strong><audio id="audio-{slug}" controls preload="none" aria-label="{esc(title)}" src="audio/unit-4-explanation/{slug}.mp3"></audio><div class="u4-audio-actions"><button type="button" data-u4-audio="audio-{slug}" data-rate="0.75" aria-pressed="false" aria-label="Slow model: {esc(title)}">Slow model</button><button type="button" data-u4-audio="audio-{slug}" data-rate="1" aria-pressed="false" aria-label="Natural model: {esc(title)}">Natural model</button></div><p class="u4-audio-status" role="status"></p><details class="u4-support"><summary>Audio text</summary><p>{esc(text)}</p></details></div>'''
def inline_audio(slug, label, text):
    audio_models.append({'file':slug+'.mp3','title':re.sub('<[^>]+>', '', label),'text':text})
    return f'<span class="u4-audio u4-inline-audio"><button type="button" data-u4-audio="audio-{slug}" data-rate="0.75" aria-pressed="false" aria-label="Listen at 0.75 speed: {esc(text)}">{label}<span class="u4-listen-mark" aria-hidden="true"> ◖))</span></button><audio id="audio-{slug}" preload="none" src="audio/unit-4-explanation/{slug}.mp3"></audio><span class="u4-audio-status" role="status"></span></span>'

def crop(file, col, row, cols, rows, alt):
    return f'<div class="u4-crop" style="--cols:{cols};--rows:{rows};--col:{col};--row:{row}"><img src="{ASSETS}{file}" alt="{esc(alt)}" width="1536" height="1024" loading="lazy" decoding="async"/></div>'
def section(slug, title, subtitle, intro, body, keywords):
    n=len(parts)+1
    parts.append(f'<details class="ie2-theory-topic ie2-search-item" id="{slug}" data-search-keywords="{esc(keywords)}"><summary><span class="ie2-topic-index">{n:02}</span><span class="ie2-topic-summary"><strong>{title}</strong><small>{subtitle}</small></span><span class="ie2-topic-toggle" aria-hidden="true">+</span></summary><div class="ie2-theory-body"><div class="ie2-key-answer"><span>Start here</span><h2>{title}</h2><p>{intro}</p></div>{body}</div></details>')

genres=[
('Comedy','A film that aims to make you laugh.','A group of friends keeps making the same silly mistake.','Friends laughing at a comic mishap'),
('Drama','A story about relationships, emotions or difficult choices.','A musician must choose between a job and her dream.','Adults in an emotional conversation'),
('Thriller','A tense story that keeps you wondering what will happen.','A detective follows a stranger who knows her secret.','A detective in a suspenseful alley'),
('Horror','A film that aims to frighten the audience.','Someone hears footsteps in an empty house.','A dark empty corridor in a horror scene'),
('Action','A story driven by physical challenges and fast events.','An explorer escapes through a crowded city.','An energetic adventure chase'),
('Science fiction','A story that imagines science, technology or other worlds.','An astronaut discovers a signal from another planet.','An explorer in a science fiction world'),
('Animation','A way of making films with drawn or digitally created moving images.','An animated adventure can also be a comedy or a drama.','Animated adventure characters'),
('Documentary','A film that explores real people, events or subjects.','A filmmaker follows wildlife in its natural environment.','A wildlife filmmaker at work')]
body='<div class="u4-genre-grid">'
for i,(name,definition,example,alt) in enumerate(genres):
    body+=f'<article class="u4-card">{crop("genres.png",i%4,i//4,4,2,alt)}<div class="u4-card-copy"><h3>{name}</h3><p>{definition}</p>{model(example)}{audio("genre-"+name.lower().replace(" ","-"),name,name+'. '+example)}</div></article>'
body+='</div>'+note('Categories can overlap','Animation is a technique; documentary describes an approach to real subjects. A film can be an animated comedy. “Excellent” is an opinion, not a genre.')
section('movies-and-genres','Movies and genres','Recognize the kind of story before giving an opinion.','Your group is choosing a film. Start with its genre, then explain why it fits the audience.',body,'movies genres comedy drama thriller horror action science fiction animation documentary')

terms=[('Plot','The connected events of a story.','The plot follows a musician who discovers an unfinished melody.'),('Setting','The place and time of a story.','The film is set in a small railway station in the present day.'),('Character','A person in the story.','Mara is the main character; she plays the guitar.'),('Cast','The group of actors in a film.','The cast includes both new and experienced actors.'),('Performance','The way an actor plays a role.','The lead actor gives a convincing performance.'),('Scene','One part of a film, usually in one place or period of time.','My favorite scene takes place on the platform.'),('Ending','The final part of the story.','Please do not reveal the ending.'),('Soundtrack','The music used in a film.','The soundtrack connects the scenes through one melody.')]
body=note('Our fictional film · The Last Platform','Mara, a young musician, waits at a railway station. An old melody brings her into contact with Elena, a station worker. We will use this original classroom story throughout the lesson.')
body+='<p class="u4-caption">Tap a vocabulary word to hear it at 0.75× speed.</p><div class="u4-vocab-grid">'
for i,(t,d,e) in enumerate(terms):
    body+=f'<article class="u4-card u4-vocab-card">{crop("film-vocabulary.png",i%4,i//4,4,2,t+" in our fictional film")}<div><h3>{inline_audio("vocab-"+t.lower(),t,t+".")}</h3><p>{d}</p>{model(e)}</div></article>'
body+='</div>'+audio('film-elements','Film elements in context','Plot. Setting. Character. Cast. Performance. Scene. Ending. Soundtrack. The film is set in a railway station. Mara is the main character. The soundtrack connects the scenes through one melody.')
body+='<h3>Where does this story belong?</h3><p class="u4-caption">Tap Prequel, Original or Sequel to hear its pronunciation at 0.75×.</p><ol class="u4-flow u4-story-order">'
for word,meaning in [('Prequel','Events before the original story.'),('Original','The story we begin with.'),('Sequel','Events after the original story.')]:
    body+='<li>'+inline_audio('word-'+word.lower(),'<strong>'+word+'</strong>',word+'.')+'<span>'+meaning+'</span></li>'
body+='</ol>'

body+=note('Story order is not release order','A prequel is often released after the original film. A remake tells an existing story again in a new production. A trailer is a short promotional preview, not the complete film.')
section('film-elements','What makes a movie','Use precise words for the story, people and music.','“I like everything” gives little information. Name the element you mean: plot, acting, setting or soundtrack.',body,'plot setting character actor cast performance scene ending soundtrack sequel prequel remake trailer')

body='<h3>Build the present perfect</h3><div class="u4-formula"><span><b>Subject</b>I / she</span><span aria-hidden="true">+</span><span class="u4-aux"><b>Auxiliary</b>have / has</span><span aria-hidden="true">+</span><span class="u4-part"><b>Past participle</b>seen</span></div>'
body+=table(['Use','Pattern','Example'], [('Affirmative','I/you/we/they + have; he/she/it + has','I <b>have seen</b> it. She <b>has watched</b> it.'),('Negative','have/has + not + participle','I <b>haven’t seen</b> the sequel. He <b>hasn’t heard</b> the soundtrack.'),('Question','Have/Has + subject + participle?','<b>Have you seen</b> the film? <b>Has she heard</b> this song?'),('Short answer','Yes/No + pronoun + auxiliary','Yes, I have. No, she hasn’t.')])
body+='<h3>Learn the participle, not just the past form</h3>'+table(['Base','Past simple','Past participle'],[('see','saw','seen'),('hear','heard','heard'),('be','was/were','been'),('make','made','made'),('win','won','won'),('watch','watched','watched'),('listen','listened','listened')])
body+='<h3>Ever and never: a question about experience, or a negative answer</h3>'
body+=grid([
('EVER · at any time up to now',p('In experience questions, <b>ever</b> means “at any time in your life up to now” — <span lang="es">alguna vez</span>. It does not tell us whether the experience happened.')+model('<b>Have + subject + ever + past participle…?</b><br>Have you <b>ever seen</b> a silent film?<br>Has she <b>ever heard</b> this soundtrack?')+p('Ever goes after the subject and before the participle in these questions. Possible answers: <b>Yes, I have</b> or <b>No, I haven’t</b>.')),
('NEVER · at no time up to now',p('<b>Never</b> means “not at any time up to now” — <span lang="es">nunca</span>. It states that the experience has happened <b>zero times</b>.')+model('<b>Subject + have/has + never + past participle.</b><br>I have <b>never seen</b> a silent film.<br>She has <b>never heard</b> this soundtrack.')+p('Never goes between have/has and the participle. It already makes the meaning negative, so do not add <b>not</b>.'))
])
body+=table(['Question with ever','Positive answer','Negative answer with never'],[
('Have you ever seen a musical?','Yes, I have. I’ve seen two.','No, I haven’t. I’ve never seen one.'),
('Has Elena ever heard this song?','Yes, she has. She knows the chorus.','No, she hasn’t. She has never heard it.')
])
body+=note('Avoid a double negative','<b>Incorrect:</b> I haven’t never seen it.<br><b>Correct:</b> I have never seen it. / I haven’t ever seen it.<br>Both correct sentences mean that it has not happened at any time up to now.')
body+=note('Ever is not always a question word','In this lesson, ever mainly appears in experience questions. It can also appear with a superlative: <b>It is the best film I have ever seen.</b> Here it means “at any time up to now”, not “never”.')
body+='<h3>Already, yet and just</h3><p class="u4-caption">Tap each example to hear the complete sentence at 0.75×.</p><div class="u4-adverb-grid">'
for title,meaning,slug,label,text,position in [
('Already · before now','The action is complete, sometimes earlier than expected.','already-watched','I’ve <b>already watched</b> it.','I’ve already watched it.','Already usually goes between have/has and the participle.'),
('Yet · a question','We want to know whether the expected action has happened by now.','yet-question','Have you watched it <b>yet</b>?','Have you watched it yet?','Yet usually goes at the end of the question.'),
('Not yet · still incomplete','The action has not happened up to now, but it may happen later.','yet-negative','I haven’t watched it <b>yet</b>.','I haven’t watched it yet.','Yet usually goes at the end of a negative sentence.'),
('Just · a short time ago','The action happened very recently.','just-released','The band has <b>just released</b> a song.','The band has just released a song.','Just goes between have/has and the participle.')
]:
    body+=f'<article class="u4-card"><h3>{title}</h3><p>{meaning}</p>{inline_audio(slug,label,text)}<p>{position}</p></article>'
body+='</div>'

body+=audio('present-perfect','Have you ever seen it?','Have you ever seen a silent film? Yes, I have. I have seen two. Has Elena heard this soundtrack? No, she has not. I have already watched the film, but I have not seen the sequel yet. The band has just released a song.')
body+='<details class="u4-support"><summary>Extra support · for and since</summary><p>Use <b>for + duration</b> and <b>since + starting point</b> for a situation continuing until now.</p>'+model('I’ve been a fan <b>for five years</b>.<br>I’ve been a fan <b>since 2021</b>.')+'<p>“Since five years” is incorrect: five years is a duration.</p></details>'
section('present-perfect','Have you ever seen it?','Talk about experiences up to now.','Use the present perfect when the experience matters and you do not place it at a finished past time.',body,'present perfect have has participle seen saw ever never already yet just for since experience')

body='<div class="u4-grid"><article class="u4-card"><h3>Experience up to now</h3><div class="u4-timeline"><span>Past experiences</span><span aria-hidden="true">● ─── ● ─── →</span><b>NOW</b></div>'+model('I’ve seen this film twice.')+p('We count experiences in a period that reaches now. No finished past date is given.')+'</article><article class="u4-card"><h3>A finished past occasion</h3><div class="u4-timeline"><span>Last Saturday</span><span aria-hidden="true">● ─── │ ───</span><b>NOW</b></div>'+model('I watched it last Saturday.')+p('The occasion is located in a finished past period: yesterday, last Saturday, two years ago, in 2000.')+'</article></div>'
body+=table(['Intention','Model','Why this tense?'], [('Experience','I’ve seen it twice.','Present perfect: experience up to now.'),('A dated occasion','I watched it last Saturday.','Past simple: the time is finished.'),('Plot summary','The story follows a musician.','Present simple: we describe the story as it unfolds in the film.')])
body+=audio('experience-and-time','From experience to a specific occasion','Have you seen The Last Platform? Yes, I have. When did you watch it? I watched it last Saturday. What is it about? The story follows a young musician who finds an unfinished melody.')
body+=note('One conversation can use three tenses','Begin with experience, follow up with a past occasion, then describe the plot. The intention changes, so the tense changes. A review does not need to stay in the present perfect.')
section('experience-or-time','Experience or finished time?','Choose the tense for the message you want to communicate.','“Have you seen it?” asks about experience. “When did you watch it?” asks about a particular occasion.',body,'present perfect past simple yesterday last Saturday time tense plot present simple')

story=[('Setting and protagonist','Mara waits at a small railway station with her guitar. She hopes to find work as a musician.','Mara waiting at a station with a guitar case'),('Discovery and goal','She discovers an old melody inside the case. She wants to find the person who wrote it.','Mara discovering a handwritten melody'),('Conflict and response','Elena recognizes the music, but the final part is missing. They rehearse together and try to complete it.','Mara and Elena rehearsing together'),('A turning point','Eventually, they perform for the commuters. Their music changes an ordinary evening at the station.','Mara and Elena performing for commuters')]
body='<p class="u4-caption">Original fictional classroom story · This complete recount includes the final event.</p><div class="u4-storyboard">'
for i,(t,s,a) in enumerate(story): body+=f'<figure>{crop("storyboard.png",i%2,i//2,2,2,a)}<figcaption><span class="u4-step">{i+1}</span><h3>{t}</h3><p>{s}</p></figcaption></figure>'
body+='</div><h3>Connect the events</h3><ol class="u4-flow"><li><strong>First</strong><span>Introduce the situation.</span></li><li><strong>Then</strong><span>Add the next event.</span></li><li><strong>However</strong><span>Introduce a contrast or obstacle.</span></li><li><strong>Eventually</strong><span>Show what happens after some time.</span></li></ol>'
body+=model('The film <b>is set</b> in a railway station. The story <b>follows</b> Mara, a young musician. She <b>discovers</b> a melody and <b>tries</b> to find its composer. However, part of the music <b>is</b> missing.')
body+=note('A useful default for a synopsis','Use the present simple consistently: “She discovers”, “they rehearse”. Use the past simple when telling us about your own viewing experience. For a public review, introduce the conflict and avoid revealing the ending; for a complete recount, a spoiler warning is helpful.')
body+=audio('plot-model','The Last Platform · plot model','The film is set in a small railway station. The story follows Mara, a young musician. First, she discovers an old melody in her guitar case. Then, she meets Elena, a station worker who recognizes it. However, the final part is missing. They rehearse together. Eventually, they perform for the commuters.')
section('tell-the-plot','Tell the plot','Build a clear summary with a visual sequence.','A plot summary explains who wants what, what gets in the way and how the events connect.',body,'plot synopsis setting protagonist conflict first then however eventually present simple spoiler')

body=grid([('Moving / gripping / hilarious',p('<b>Moving</b> creates a strong emotional response. <b>Gripping</b> holds your attention. <b>Hilarious</b> is extremely funny.')+model('The reunion is moving because the characters finally understand each other.')),('Predictable / confusing / disappointing',p('<b>Predictable</b>: easy to guess. <b>Confusing</b>: difficult to understand. <b>Disappointing</b>: not as good as expected.')+model('The ending is predictable because every clue points to the same solution.')),('Catchy / convincing',p('A <b>catchy</b> song is easy to remember. A <b>convincing</b> performance feels believable.')+model('The chorus is catchy; I remembered its melody after one listen.'))])
body+='<h3>The work creates an effect; the viewer feels it</h3>'+table(['Film / scene: -ing','Viewer: -ed'], [('The scene is <b>exciting</b>.','I feel <b>excited</b>.'),('The dialogue is <b>boring</b>.','I feel <b>bored</b>.'),('The ending is <b>disappointing</b>.','I feel <b>disappointed</b>.')])
body+='<ol class="u4-flow"><li><strong>Opinion</strong><span>The soundtrack is memorable.</span></li><li><strong>Reason</strong><span>Because one melody connects the story.</span></li><li><strong>Detail</strong><span>We hear it at the discovery and the concert.</span></li></ol>'+note('A preference is not a fact about everyone','“I found it slow” is a personal response. “Everyone hated it” needs evidence. Explain your view without assuming that your classmates agree.')
body+=audio('opinion-model','An opinion with evidence','The concert scene is exciting, and I felt excited when the music began. The soundtrack is memorable because one melody connects the story. We hear it when Mara finds the sheet music and again at the concert. Although some scenes are slow, the acting is convincing.')
section('opinions','Give an opinion with evidence','Move from “good” and “bad” to specific reasons.','A useful review lets another person understand your reaction, even if they have a different opinion.',body,'opinion evidence reason moving gripping hilarious predictable confusing disappointing catchy convincing bored boring excited exciting')

review=[('Introduce','I’ve seen The Last Platform twice, and I watched it again last Saturday. This fictional drama is set in a small railway station.'),('Summarize','The story follows Mara, a young musician who finds an unfinished melody. She meets a station worker who recognizes it, and they try to discover its history together.'),('Evaluate','The acting is convincing, and the soundtrack is especially moving because the same melody connects important scenes. Although the middle is a little slow, the relationship between the two women keeps the story interesting.'),('Recommend','Overall, I recommend watching it if you enjoy quiet stories about friendship and music. It is worth watching for its warm performances, even if you usually prefer faster films.')]
review_text=' '.join(s for _,s in review)
body='<article class="u4-review"><p class="intermediate2-kicker">Model review · Original fictional film</p><h3>The Last Platform</h3>'+''.join(f'<div class="u4-review-paragraph"><span>{i+1} · {t}</span><p>{s}</p></div>' for i,(t,s) in enumerate(review))+'</article>'+audio('review-model','A complete film review',review_text)
body+=table(['Language job','Pattern','Example'], [('Give a reason','because + clause','The scene works because the dialogue feels natural.'),('Balance a judgment','although + clause, main clause','Although the plot is predictable, the acting is strong.'),('Add a contrasting sentence','However, + clause','The music is excellent. However, some scenes are slow.'),('Recommend','recommend + -ing / worth + -ing','I recommend watching it. It is worth watching.'),('Name the audience','If you enjoy…, you’ll probably like…','If you enjoy dramas, you’ll probably like this film.')])
body+=grid([('A vague review',model('It is a good movie. The actors are good. I like it.')+p('We cannot tell what kind of story it is, what works or who might enjoy it.')),('A useful revision',model('This quiet drama follows a musician at a station. The acting feels natural because the two leads listen and react like real friends. I recommend it to viewers who enjoy character-driven stories.')+p('The writer identifies the work, gives evidence and names an audience.'))])
body+='<details class="u4-support"><summary>Example · a sequel to the original film</summary><p>The imagined sequel <b>The Next Platform</b> keeps Mara and the musical theme, but changes the setting and conflict.</p>'+model('In this imagined sequel, Mara travels with her first band. The story explores the pressure of performing away from home. Unlike the original, it moves between several cities.')+'<p>The same character and musical theme connect the two films; the new setting and conflict make the sequel a different story.</p></details>'
section('reviews','Write and compare reviews','Connect information, opinion and a recommendation.','A review helps someone decide whether a film is right for them. Your reasons matter more than a star rating.',body,'review blog recommendation recommend worth watching although however because overall sequel prequel')

music=[('Artist / band','An individual performer / a group that performs music.'),('Track / album','One recorded piece / a collection of recorded pieces.'),('Lyrics / chorus','The words of a song / a repeated section, often its most recognizable part.'),('Beat / melody','The regular pulse / a sequence of notes you recognize as a tune.'),('Music video','A visual production made to accompany a song.'),('Views / chart / hit','Recorded plays / a ranked list / a successful or popular song.')]
body=grid([(t,p(d)) for t,d in music])+'<h3>Musical genre and video style answer different questions</h3>'+p('Pop, rock, hip-hop, electronic music and salsa describe musical genres. Performance, narrative and conceptual describe what the video shows. A rock video can be narrative; a pop video can combine all three styles.')
styles=[('Performance','The artist or band performs the song.','A band playing on stage'),('Narrative','Characters take part in a connected story.','Adults meeting again at a railway station'),('Conceptual','Images explore an idea or mood without a conventional storyline.','A dancer among abstract colored lights')]
body+='<div class="u4-media-grid">'+''.join(f'<article class="u4-card">{crop("music-styles.png",i,0,3,1,a)}<div class="u4-card-copy"><h3>{t}</h3><p>{d}</p></div></article>' for i,(t,d,a) in enumerate(styles))+'</div>'
body+=audio('music-vocabulary','Music and video vocabulary','Artist. Band. Track. Album. Lyrics. Chorus. Beat. Melody. Music video. Views. Chart. Hit. This pop track has a catchy chorus and a steady beat. Its video combines a band performance with a short narrative.')
body+=note('Popularity and quality are different questions','Views count plays according to a platform’s rules. A chart ranks works using particular criteria. Neither automatically tells us whether you will enjoy a song. “Chart” means a ranked list here; “lyrics” means song words, not “letters”.')
section('music-videos','Music videos and media','Separate what you hear from what you see.','Listen for the sound, then look for the visual structure. A video can tell a story even when its song belongs to a familiar genre.',body,'music video trends genre artist band track album lyrics chorus beat melody chart hit views performance narrative conceptual')

body=note('Illustrated comparison · fictional, not a historical ranking','These two invented classroom selections illustrate comparison. They do not describe actual MTV or Billboard lists. Each selection contains three videos. A larger research task would need dated, comparable sources.')
rows=[('Genre','2 pop videos; 1 rock video','1 pop video; 1 hip-hop video; 1 electronic video'),('Artists','2 solo artists; 1 band','2 solo artists; 1 band'),('Main visual style','2 performance; 1 narrative','1 performance; 1 narrative; 1 conceptual'),('Main distribution in this sample','All 3 shown on a music TV programme','All 3 shared on an online video platform')]
body+='<div class="u4-era"><b>Selection A · 2000</b><span aria-hidden="true">→</span><b>Selection B · 2026</b></div>'+table(['Compare the same feature','A · 2000 (fictional)','B · 2026 (fictional)'],rows)
body+=grid([('Similarity',model('<b>Both</b> selections include two solo artists and one band.')+p('Both identifies something shared.')),('Difference',model('Selection A contains more pop videos, <b>whereas</b> selection B includes more musical genres.')+p('Whereas connects a contrast between two clauses.')),('Change across the samples',model('The range of genres <b>has become</b> wider between these two selections.')+p('Has become focuses on a change and its later result.')),('A finished period',model('In the fictional 2000 selection, all three videos <b>appeared</b> on a music TV programme.')+p('Appeared locates the event in a finished period.'))])
comparison='Both fictional selections include two solo artists and one band. In the 2000 selection, two videos are pop, whereas the 2026 selection includes three different genres. The range of genres has become wider between these samples. Selection A mainly shows performances, while selection B includes a conceptual video. However, three videos from each period are not enough to establish a worldwide trend. These observations describe only the classroom selections.'
body+=audio('trends-model','Comparing two selections',comparison)+model(comparison)
body+='<details class="u4-support"><summary>Extra support · used to</summary><p><b>Used to + base verb</b> describes a past habit or situation that is no longer true.</p>'+model('I used to watch music videos on TV. Now I watch them online.')+'<p>This is a personal example, not a claim about every viewer. Questions use “Did you use to…?”</p></details>'
body+=note('For the guide’s MTV comparison','A reliable historical comparison uses verified, dated lists of music videos and identifies the source, selection method and number of entries. Different ranking criteria can affect the comparison. Observations about a sample are different from claims about worldwide trends.')
section('then-and-now','Then and now','Compare evidence and describe change.','A timeline helps us see differences. A useful comparison examines the same features in both samples.',body,'then now trends timeline comparison both unlike whereas more less has become have changed used to MTV Billboard 2000 2026')

expressions=[
('come-out','come out','Phrasal verb · intransitive','To be released or become available.','The sequel came out last month.','It came out last month.','No object follows this meaning of come out. Do not say “come the film out”.','come OUT · connect the final /m/ to the vowel in out.'),
('put-on','put on','Phrasal verb · transitive and separable','To start playing a recording.','Put on the soundtrack. / Put the soundtrack on.','Put it on.','A noun can go in either position; a pronoun must go between put and on.','put it ON · keep the three words in one group.'),
('turn-up','turn up','Phrasal verb · transitive and separable','To increase the volume.','Turn up the music. / Turn the music up.','Turn it up.','This meaning concerns volume. The object pronoun goes in the middle.','turn it UP · link it to up; emphasize the change.'),
('turn-down','turn down','Phrasal verb · transitive and separable','To reduce the volume.','Turn down the music. / Turn the music down.','Turn it down.','This meaning concerns volume. Do not say “turn down it”.','turn it DOWN · keep the final /n/ clear.'),
('find-out','find out','Phrasal verb · transitive or intransitive','To discover information.','We found out the release date. / We found the release date out.','We found it out yesterday.','A noun object may be separated; the first noun example is more natural here. Pronouns go in the middle. Keep a whole clause after out: “We found out who wrote it.”','find OUT · link /d/ to the vowel in out.'),
('stand-out','stand out','Phrasal verb · intransitive','To be particularly noticeable.','Her performance stands out.','It stands out.','There is no direct object. You can add “from”: it stands out from the other performances.','stand OUT · keep the /d/ before the vowel.'),
('steal-the-show','steal the show','Idiom','To attract the most attention and praise.','The supporting actor steals the show.','Her performance steals the show.','Informal praise. Nothing is literally stolen.','steal the SHOW · the is light; stress show.'),
('edge-of-seat','on the edge of your seat','Idiom','Very excited or tense because you want to know what happens next.','The final scene kept me on the edge of my seat.','The thriller will keep you on the edge of your seat.','Informal reaction to suspense. Adjust my/your/our to the person.','on the EDGE of my SEAT · speak as a complete group.'),
('music-to-ears','music to my ears','Idiom','News or words that are very pleasing to hear.','“The concert is free!” That is music to my ears.','Your good news is music to my ears.','This expression reacts to good news; it is not simply a description of a song.','MUSIC to my EARS · make music and ears prominent.')]
body=grid([('What is a phrasal verb?',p('A main verb and a particle work together as a vocabulary unit: <b>come + out</b> means “be released” in this context. Its meaning and object pattern must be learned together.')),('Fixed expressions and idioms',p('A fixed expression is a conventional combination, such as <b>worth watching</b>. An idiom has a figurative meaning, such as <b>steal the show</b>. Not every multiword expression is a phrasal verb.'))])
body+='<h3>Six phrasal verbs in context</h3><div class="u4-grid u4-expressions">'
for i,(slug,name,kind,meaning,noun,pronoun,rule,sound) in enumerate(expressions):
    if i==6: body+='</div><h3>Three related idioms</h3><div class="u4-grid u4-expressions">'
    glosses={'come-out':'estrenarse / salir a la venta','put-on':'poner una canción o grabación','turn-up':'subir el volumen','turn-down':'bajar el volumen','find-out':'averiguar / descubrir información','stand-out':'destacarse','steal-the-show':'llevarse los aplausos / acaparar la atención','edge-of-seat':'estar en suspenso','music-to-ears':'ser una noticia muy grata'}
    gloss=glosses[slug]
    text=name+'. '+noun.split(' / ')[0]+' '+pronoun
    body+=f'<article class="u4-card"><span class="u4-label">{kind}</span><h3>{name}</h3><p>{meaning}</p><p lang="es"><b>Idea en español:</b> {gloss}.</p>{model(noun)}{model(pronoun)}<p><b>Word order and use:</b> {rule}</p><p class="u4-sound"><b>Sound:</b> {sound}</p>{audio(slug,name,text)}</article>'
body+='</div>'+note('Choose the meaning that fits the scene','These expressions have other meanings in other situations. In this lesson, “turn down” means reduce volume and “come out” means be released. For separable verbs, move the pronoun into the middle: “Turn it down”.')
section('expressions','Phrasal verbs and idioms','Learn meaning, word order and pronunciation together.','“The film came out” does not describe a film walking out of a room. The verb and particle create a meaning together.',body,'phrasal verbs idioms expressions come out put on turn up turn down find out stand out steal show edge seat music ears separable pronoun')

body=grid([('Hear the auxiliary',model('I’ve <b>seen</b> it. /aɪv/<br>She’s <b>watched</b> it. /ʃiːz/<br>He hasn’t <b>heard</b> it. /ˈhæzənt/')+p('In “She’s watched”, ’s means <b>has</b>. In “She’s excited”, ’s means <b>is</b>. The following word helps you interpret it.')),('Keep the participle audible',model('see → saw → <b>seen</b><br>watch → watched /t/<br>listen → listened /d/')+p('Keep the final consonant in seen, watched and listened. Do not add a separate syllable to watched.')),('Group the message',model('It is set in a small station / and it follows a young musician.<br>Although the middle is slow / the soundtrack is moving.')+p('The slash marks a possible pause between meaningful groups, not a word to pronounce.')),('Stress the contrast',model('I’ve <b>SEEN</b> it / but I haven’t <b>REVIEWED</b> it.<br>The plot is <b>SIMPLE</b> / but the acting is <b>STRONG</b>.')+p('Emphasize the information that changes or matters most.'))])
body+=audio('sound-model','Sound clear · phrases and contrasts','I have seen it. I’ve seen it. She has watched it. She’s watched it. He hasn’t heard it. Seen. Watched. Listened. It is set in a small station, and it follows a young musician. Although the middle is slow, the soundtrack is moving. I’ve seen it, but I haven’t reviewed it.')
dialogue=[('Alex','Have you seen The Last Platform?'),('Sam','Yes, I have. I watched it last Saturday.'),('Alex','What is it about?'),('Sam','It follows a young musician who finds an unfinished melody.'),('Alex','What stood out for you?'),('Sam','The soundtrack stood out. Its main melody connects the important scenes.'),('Alex','Would you recommend it?'),('Sam','Yes. Although the middle is slow, the acting is convincing. If you enjoy quiet dramas, it is worth watching.'),('Alex','Which music-video selection would you choose for our event?'),('Sam','I would choose selection B. Both samples include a band, but B contains a wider range of genres.')]
body+='<h3>Model conversation · choosing for our group</h3><div class="u4-dialogue">'+''.join(f'<p><strong>{speaker}</strong><span>{line}</span></p>' for speaker,line in dialogue)+'</div>'+audio('conversation-model','Choosing a film and a music selection',' '.join(line for _,line in dialogue))
body+='<div class="intermediate2-actions"><a class="intermediate2-button primary" href="./course-overview.html#unit-4">Back to Course Overview</a><a class="intermediate2-button" href="./practice-lab.html">Practice Lab</a></div>'
section('sound-and-use','Sound clear and put it together','Use the language in one connected recommendation.','Listen for meaning first. Then repeat a short group, keeping auxiliaries, participles and important words clear.',body,'pronunciation sound contraction seen watched listened stress conversation review recommendation self check')

nav=''.join(f'<a href="#{s}">{t}</a>' for s,t in [('movies-and-genres','Movies'),('present-perfect','Grammar'),('reviews','Reviews'),('music-videos','Music'),('expressions','Expressions'),('sound-and-use','Sound & use')])
html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/><title>Unit 4: Movies, Reviews, Music Videos and Trends | Intermediate English Course 2</title><meta name="description" content="Learn to summarize films, write supported reviews, use the present perfect and compare music videos with visual examples, audio models and clear explanations."/><link rel="icon" href="/favicon.ico" sizes="any"/><link rel="stylesheet" href="../../assets/css/style.css?v=20260911-unit4-v2"/><link rel="stylesheet" href="../../assets/css/english-intermediate-2.css?v=20260911-unit4-v2"/></head>
<body class="english-intermediate2-page ie2-unit4-theory-page"><a class="u4-skip" href="#unit4-content">Skip to lesson</a><div class="global-course-switcher"><details><summary><span>Courses</span></summary><nav><a href="../../index.html">Home</a><a href="../index.html">English</a><a href="./index.html">Intermediate English Course 2</a><a href="./course-overview.html">Course Overview</a><a href="./practice-lab.html">Practice Lab</a></nav></details></div><header class="site-header"><nav class="navbar"><a class="brand" href="../../index.html"><img src="../../assets/img/jaralingua-logo.png" alt="JaraLingua Logo"/></a><ul class="nav-links"><li><a href="./index.html">Course Home</a></li><li><a href="./course-overview.html#unit-4">Course Overview</a></li><li><a href="./evaluations.html">Evaluations</a></li><li><a href="./practice-lab.html">Practice Lab</a></li></ul></nav></header>
<main><section class="u4-hero" aria-labelledby="unit4-title"><img class="u4-hero-image" src="{ASSETS}hero.png" alt="Adult learners choosing films and music together in a university media room" width="1536" height="1024" fetchpriority="high" decoding="async"/><div class="u4-hero-inner"><div class="ie2-unit4-hero-copy"><p class="intermediate2-kicker">Unit 4 · Sessions 9–10</p><h1 id="unit4-title">Movies, Reviews,<br>Music Videos and Trends</h1><p>Tell the story. Explain your reaction.<br>Help someone choose what to watch.</p><div class="ie2-overview-chips"><span>Film reviews</span><span>Present perfect</span><span>Music & change</span></div><div class="intermediate2-actions"><a class="intermediate2-button primary" href="#unit4-content">Explore the lesson</a><a class="intermediate2-button ghost" href="./course-overview.html#unit-4">Course map</a></div></div></div></section>
<div class="u4-shell"><section class="u4-opening" aria-label="Learning goals"><div><p class="intermediate2-kicker">Vocabulary, grammar and pronunciation</p><h2>The language of films and music</h2><p>Learn to introduce a film, summarize its plot, support a review and compare two music-video selections.</p></div><ol class="u4-route"><li><b>01 · Notice</b>Read or hear a model.</li><li><b>02 · Understand</b>Connect form and meaning.</li><li><b>03 · Compare</b>See differences in meaning.</li><li><b>04 · Listen</b>Hear words and expressions.</li></ol></section><nav class="u4-topic-nav" aria-label="Lesson topics">{nav}</nav>
<section class="intermediate2-search course-search-panel" data-course-search-panel data-search-target="#unit4-content" data-search-items=".ie2-search-item" aria-label="Search Unit 4"><label class="course-search-label" for="u4-search">Find a topic or expression</label><div class="course-search-row"><input id="u4-search" type="search" data-course-search-input placeholder="Try: seen, plot, soundtrack, turn down…" autocomplete="off"/><button type="button" class="course-search-clear" data-course-search-clear hidden>Clear</button></div><p class="course-search-meta"><span data-course-search-count></span><span>Choose a section to open its explanation.</span></p></section><p class="course-search-empty" data-course-search-empty hidden>No matching topic. Try another word.</p></div>
<section class="ie2-unit-theory-shell" id="unit4-content" aria-label="Unit 4 complete explanation">{''.join(parts)}</section></main><footer class="site-footer"><p>&copy; 2026 JaraLingua. English and French for step-by-step learning.</p></footer>
<script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20260911-unit4-v2"></script><script src="../../assets/js/course-search.js?v=20260911-unit4-v2"></script><script src="../../assets/js/english-intermediate2-unit4-explanation.js?v=20260911-unit4-v2"></script><script src="/assets/js/course-switcher.js?v=20260911-unit4-v2"></script><script src="/assets/js/page-qr-access.js?v=20260911-unit4-v2"></script></body></html>'''

if __name__ == '__main__':
    out=COURSE/'unit-4-movies-music-and-reviews.html'
    out.write_text(html,encoding='utf-8')
    audio_dir=COURSE/'audio/unit-4-explanation'
    audio_dir.mkdir(parents=True,exist_ok=True)
    (audio_dir/'models.json').write_text(json.dumps(audio_models,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    (audio_dir/'scripts.md').write_text('# Unit 4 explanation audio scripts\n\nCanonical original classroom models. Generated with the existing professional audio workflow. No music excerpts or copyrighted lyrics.\n\n'+ '\n\n'.join(f'## {m["title"]}\n\nFile: `{m["file"]}`\n\n{m["text"]}' for m in audio_models)+'\n',encoding='utf-8')
    print(f'Built {out.name}: {len(parts)} topics; {len(audio_models)} audio models; review {len(review_text.split())} words.')
