from pathlib import Path
import json,html,hashlib,sys
r=Path(__file__).resolve().parents[1];E=html.escape;stem='speaking-unit-5-one-picture-many-impressions';data=json.loads((r/'assets/data/english-intermediate2-unit5-impressions.json').read_text(encoding='utf-8'))
existing={}
for folder in ['unit-5-explanation','unit-5-grammar','unit-5-picture','unit-5-listening']:
 for a in json.loads((r/'ingles/intermediate-2/audio'/folder/'models.json').read_text(encoding='utf-8'))['items']:existing[a['text']]='audio/'+folder+'/'+a['file']
texts=list(dict.fromkeys([t for _,t in data['frames']+data['demo']]+[w for s in data['scenes'] for w in s['words']]+[s['expression'] for s in data['scenes']]+['What clue makes you think that?']))
dest=r/'ingles/intermediate-2/audio/unit-5-impressions';dest.mkdir(exist_ok=True);old=json.loads((dest/'models.json').read_text(encoding='utf-8')) if (dest/'models.json').exists() else {'items':[]};old={a['text']:a for a in old['items']};items=[];audio={}
for t in texts:
 if t in existing:audio[t]=existing[t];continue
 key=hashlib.sha256(t.encode()).hexdigest()[:14];item=dict(id=key,file=key+'.mp3',text=t,kind='phrase');item.update({k:old[t][k] for k in ('bytes','sha256') if t in old and k in old[t]});items.append(item);audio[t]='audio/unit-5-impressions/'+item['file']
(dest/'models.json').write_text(json.dumps(dict(voiceId='EXAVITQu4vr4xnSDxMaL',modelId='eleven_multilingual_v2',items=items),ensure_ascii=False,indent=2)+'\n',encoding='utf-8');data['audio']=audio
(r/'assets/data/english-intermediate2-unit5-impressions.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def say(t):return '<button type="button" class="mi-say" data-audio="'+audio[t]+'" aria-pressed="false" aria-label="Listen: '+E(t)+'">'+E(t)+'<span aria-hidden="true"> ◖))</span></button>'
source=(r/'ingles/intermediate-2/grammar-unit-5-read-the-clues.html').read_text(encoding='utf-8');head=source.split('<main>')[0].replace('Read the Clues | Unit 5 Grammar Practice','One Picture, Many Impressions | Unit 5 Speaking').replace('Ten illustrated questions on must, might and can’t, with clues, explanations and pronunciation.','Twenty picture discussions for teacher-led projection: impressions, feelings, opinions and expressions.').replace('grammar-unit-5-read-the-clues',stem).replace('english-intermediate2-unit5-grammar.css?v=20260925-2','english-intermediate2-unit5-impressions.css?v=20260925-1').replace('ie2-u5-grammar','ie2-u5-impressions').replace('#grammarChallenge','#pictures').replace('Grammar challenge','Picture gallery').replace('#quickGuide','#howTo').replace('Quick guide','How to speak')
image=data['scenes'][0]['image']
main='''<main><section class="ie2-grammar-hero" aria-labelledby="pageTitle"><div class="ie2-grammar-hero-copy"><p class="intermediate2-kicker">Practice Lab · Unit 5 · Teacher-led speaking</p><h1 id="pageTitle">One Picture,<br>Many Impressions</h1><p>Look closely. Share an impression.<br>Give a clue and welcome another idea.</p><div class="ie2-grammar-meta"><span>20 pictures</span><span>More than one interpretation</span><span>TV projection</span></div><div class="intermediate2-actions"><a class="intermediate2-button primary" href="#howTo">Start with the example</a><a class="intermediate2-button ghost" href="#pictures">Choose a picture</a></div></div><figure><img src="HERO" width="1536" height="1024" alt="A student holds notes as classmates look on" fetchpriority="high"/></figure></section>
<section class="ie2-grammar-shell mi-shell">
<section id="howTo" class="ie2-grammar-intro"><div><p class="intermediate2-kicker">Your turn to speak</p><h2>Say three or four connected sentences</h2><p>Give an impression, describe a feeling and its possible cause, and explain your idea. Then listen to another student and respond.</p></div><aside><strong>Different ideas can fit</strong><span>Use the picture as a clue. An expression does not prove how someone feels.</span></aside></section>
<ol class="mi-route"><li><b>1 · Give an impression</b><span>Use looks, seems or looks like.</span></li><li><b>2 · Feeling and cause</b><span>Choose a feeling and what could cause it.</span></li><li><b>3 · Explain and respond</b><span>Use I think, I guess, perhaps or maybe. Give a clue and hear another idea.</span></li></ol>
<section id="demo" class="mi-section"><p class="intermediate2-kicker">Picture 1 · An example, not the only answer</p><h2>What could you say?</h2><div class="mi-audio-controls" role="group" aria-label="Example audio speed"><span>Tap the words to listen</span><button type="button" data-speed="0.75" aria-pressed="true">0.75×</button><button type="button" data-speed="1" aria-pressed="false">1×</button><button type="button" data-stop>Stop audio</button></div><div class="mi-demo"><button type="button" class="mi-image-open" data-open="0" aria-label="Enlarge the demonstration picture"><img src="HERO" width="1536" height="1024" alt="A student holds notes in front of classmates"/><span>Enlarge image ↗</span></button><ol>DEMO</ol></div><p>These are possible impressions. Someone else may see confidence or concentration. Use an idiom or phrasal verb only when it fits your idea.</p></section>
<section id="language" class="mi-section"><p class="intermediate2-kicker">Keep these tools in mind</p><h2>Your language reminder</h2><div class="mi-language-grid">FRAMES</div><div class="mi-patterns"><p><b>looks + adjective:</b> She looks nervous.</p><p><b>looks like + noun:</b> It looks like a classroom.</p><p><b>looks like + complete idea:</b> It looks like they are working together.</p><p><b>Feeling → possible cause:</b> They feel confused → the task seems confusing.</p></div></section>
<details class="mi-teacher-guide"><summary>How to lead the discussion</summary><p>Invite one student to give an impression, another to suggest a different explanation, and a third to add a cause or expression. Ask:</p>CLUE<p>Reveal the help or sample descriptions after students have tried. Choose a few pictures per lesson or continue through the gallery.</p></details>
<section class="mi-toolbar" aria-label="Gallery controls"><div><button type="button" class="intermediate2-button primary" data-random>Random unseen picture</button><button type="button" class="intermediate2-button" data-new-set hidden>Start a new set</button><p data-deck-status role="status">20 unseen pictures</p></div><div class="mi-audio-controls" role="group" aria-label="Audio speed"><span>Pronunciation</span><button type="button" data-speed="0.75" aria-pressed="true">0.75×</button><button type="button" data-speed="1" aria-pressed="false">1×</button><button type="button" data-stop>Stop audio</button></div></section>
<section id="pictures"><div class="mi-heading"><h2>Choose a situation</h2><p>Click a picture to project it.</p></div><div class="mi-grid">CARDS</div></section><p class="mi-note">Speaking practice · No recording or submission. Opened pictures stay marked until you start a new set or reload.</p><div class="intermediate2-actions"><a class="intermediate2-button primary" href="./practice-lab.html#unit-5-folder">Back to Practice Lab</a><a class="intermediate2-button" href="./unit-5-impressions-feelings-and-satire.html#expressions">Phrasal verbs and idioms</a></div></section></main>
<dialog id="miProjector" aria-labelledby="miTitle"><header class="mi-project-header"><h2 id="miTitle"></h2><div><button type="button" id="miFullscreen">Full screen</button><button type="button" id="miClose" autofocus>Close ×</button></div></header><div class="mi-project-stage" id="miStage"><figure><img id="miImage" alt=""/><figcaption id="miImageStatus" role="status"></figcaption><button type="button" id="miImageRetry" hidden>Retry image</button></figure><aside id="miPanel" hidden aria-labelledby="miPanelTitle"><h3 id="miPanelTitle"></h3><div id="miPanelContent"></div></aside></div><footer class="mi-project-footer"><div class="mi-nav"><button type="button" id="miPrev">← Previous</button><button type="button" id="miNext">Next →</button><button type="button" data-random>Random unseen</button><button type="button" data-new-set hidden>New set</button></div><div class="mi-support-controls" role="group" aria-label="Optional speaking support"><button type="button" data-support="language" aria-controls="miPanel" aria-expanded="false">Language help</button><button type="button" data-support="models" aria-controls="miPanel" aria-expanded="false">Possible descriptions</button><button type="button" data-support="expression" aria-controls="miPanel" aria-expanded="false">Try an expression</button></div><div class="mi-audio-controls" role="group" aria-label="Projection audio speed"><button type="button" data-speed="0.75" aria-pressed="true">0.75×</button><button type="button" data-speed="1" aria-pressed="false">1×</button><button type="button" data-stop>Stop audio</button></div></footer></dialog>
<footer class="site-footer"><p>&copy; 2026 JaraLingua. Intermediate English Course 2 Practice Lab.</p></footer><script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20260919-local-login"></script><script src="../../assets/js/english-intermediate2-unit5-impressions.js?v=20260925-1"></script><script src="/assets/js/course-switcher.js"></script><script src="/assets/js/page-qr-access.js"></script></body></html>
'''
main=main.replace('HERO',image).replace('DEMO',''.join('<li><b>'+E(label)+'</b>'+say(t)+'</li>' for label,t in data['demo'])).replace('FRAMES',''.join('<article><h3>'+E(label)+'</h3>'+say(t)+'</article>' for label,t in data['frames'])).replace('CLUE',say('What clue makes you think that?'))
cards=[]
for scene in data['scenes']:
 i=scene['id'];cards.append(f'<article class="mi-card" data-card="{i}"><button type="button" class="mi-image-open" data-open="{i}" aria-label="Open picture {i+1}: {E(scene["title"])}"><img src="{scene["image"]}" alt="{E(scene["alt"])}" width="1536" height="1024" loading="lazy"/><span class="mi-number">{i+1:02}</span></button><div><h3>{E(scene["title"])}</h3><span data-visited="{i}"></span></div></article>')
main=main.replace('CARDS',''.join(cards));(r/'ingles/intermediate-2'/f'{stem}.html').write_text(head+main,encoding='utf-8')
sys.path.insert(0,str(r/'tmp/unit5-explanation/python-deps'));import qrcode,qrcode.image.svg
qrcode.make('https://www.jaralingua.com/ingles/intermediate-2/'+stem+'.html',image_factory=qrcode.image.svg.SvgPathImage,box_size=10,border=4).save(r/'assets/img/page-qr'/('ingles-intermediate-2-'+stem+'.svg'))
p=r/'assets/js/english-intermediate2-unit5-impressions.js'
if p.exists():
 s=p.read_text(encoding='utf-8');a=s.index('const config=');b=s.index('\nconst $=',a);p.write_text(s[:a]+'const config='+json.dumps(data,ensure_ascii=False)+';'+s[b:],encoding='utf-8')
print('Built 20 cards, example, reminder and QR;',len(items),'new audio clips;',len(audio)-len(items),'reused.')
