from pathlib import Path
import json
r=Path.cwd();p=r/'assets/data/english-intermediate2-unit5-impressions.json';base='/assets/img/english-intermediate-2/unit-5/'
rows=[
('Before speaking','explanation/presentation.webp','A student holds notes in front of classmates.',['nervous','interested','interesting'],['She looks nervous because she is holding her notes tightly.','It looks like a class presentation. The classmates seem interested.','Perhaps she feels confident and is simply waiting to begin.'],'break the ice'),
('During the talk','explanation/bored.webp','A person rests their cheek on one hand while listening.',['bored','boring','tired'],['He looks bored. I guess the talk is not interesting to him.','Perhaps he is tired, although the talk is interesting.','He seems quiet, but he could be thinking carefully.'],'cheer up'),
('At the museum','explanation/interested.webp','Visitors watch a guide demonstrate a model.',['interested','interesting','confused'],['The visitors look interested because they are watching closely.','The demonstration seems interesting, but perhaps some parts are confusing.','I think it looks like a group learning how a machine works.'],'look up to'),
('On the screen','behind-the-picture/02-screen.webp','Two people react to something on a laptop.',['surprised','surprising','excited'],['He looks surprised because his hand is over his mouth.','She seems excited. Perhaps they have received good news.','It looks like they are watching something funny, but we cannot see the screen.'],'be on cloud nine'),
('Following the instructions','behind-the-picture/08-task.webp','Two people examine loose pieces and a partly built model.',['confused','confusing','interested'],['He looks confused. Perhaps the instructions are confusing.','She seems interested in how the model works.','I guess they enjoy the challenge, even though it looks difficult.'],'get along with'),
('A round of applause','behind-the-picture/04-presentation.webp','One person holds notes while other people clap.',['relieved','proud','embarrassed'],['The speaker seems relieved because the presentation appears to be over.','I think the classmates look pleased with the presentation.','Perhaps the speaker feels embarrassed by all the attention.'],'be on cloud nine'),
('Checking the time','explanation/waiting.webp','A person at a bus stop checks the time.',['worried','nervous','relieved'],['She looks worried because she is checking the time.','I guess she is waiting for a bus, but perhaps she is meeting a friend.','She seems calm to me. Checking the time does not prove she is nervous.'],'calm down'),
('Arranging the supplies','behind-the-picture/07-community.webp','People carry boxes and arrange food packages.',['helpful','organized','grateful'],['It looks like a group preparing donations.','The people seem helpful because they are arranging supplies together.','Perhaps they are preparing an event rather than donating the food.'],'reach out to'),
('Listening to the group','behind-the-picture/06-group.webp','Several people talk while one person listens with an open notebook.',['interested','thoughtful','concentrating'],['The quiet person looks interested in the conversation.','I guess they are concentrating before sharing an idea.','Perhaps this is a new group and someone needs time to feel comfortable.'],'fit in'),
('Inside the gift','behind-the-picture/05-bag.webp','Two people look into a bag; its contents are hidden.',['excited','surprised','disappointed'],['They seem excited about what is inside the bag.','I think the gift looks surprising to them.','Perhaps one person is disappointed, but we need more information.'],'be on cloud nine'),
('Finding a piece','many-impressions/11-puzzle.webp','A group works on a wooden puzzle.',['confused','confusing','interested'],['The puzzle seems confusing because several pieces are still loose.','The group looks interested in solving it together.','I guess one person has found a solution while another is still thinking.'],'get along with'),
('A moment on the bench','many-impressions/12-support.webp','Two friends sit beside a sports bag; one offers water.',['disappointed','worried','grateful'],['One friend looks disappointed, but the reason is not clear.','The other person seems supportive because they are offering water.','Perhaps they are just resting after exercise rather than feeling sad.'],'cheer up'),
('Getting things ready','many-impressions/13-gathering.webp','People arrange decorations, cups and a cake.',['excited','exciting','surprised'],['It looks like a celebration is being prepared.','The activity seems exciting, and some people look happy.','Perhaps they are planning a surprise for someone.'],'be on cloud nine'),
('A quiet cup','many-impressions/14-cup.webp','A person holds a mug; tissues are on the table.',['tired','worried','relieved'],['He looks tired, and perhaps he is taking a break.','I guess he feels under the weather because there are tissues nearby.','He seems thoughtful. The tissues alone do not tell us how he feels.'],'feel under the weather'),
('Working on a project','many-impressions/15-project.webp','Two people share materials while building a model.',['interested','confident','confusing'],['They seem to get along with each other because they are sharing materials.','The project looks interesting, although some steps could be confusing.','I think one person looks confident while the other watches carefully.'],'get along with'),
('Learning a new skill','many-impressions/16-learning.webp','One person demonstrates a clay technique while another watches.',['interested','interesting','confident'],['The learner looks interested in the demonstration.','The person demonstrating seems patient and confident.','Perhaps the learner admires this person and wants to learn more.'],'look up to'),
('Making space','many-impressions/17-space.webp','Someone pulls out a chair and gestures toward a person arriving.',['helpful','nervous','welcoming'],['The person offering a chair seems welcoming.','The newcomer looks unsure, but perhaps they already know the group.','I think this looks like an invitation to join a discussion.'],'stand up for'),
('Outside the frame','behind-the-picture/10-looking.webp','Several people look in the same direction at something we cannot see.',['surprised','surprising','confused'],['They look surprised by something outside the picture.','Perhaps they are watching an exciting performance.','One person seems confused. I guess they do not all understand what is happening.'],'open up'),
('Before the door opens','many-impressions/19-door.webp','A person holds a folder near a closed door and empty chairs.',['nervous','confident','worried'],['She looks nervous because she is holding the folder close.','It looks like she is waiting for an appointment.','Perhaps she feels confident and is taking a moment to prepare.'],'calm down'),
('Picking things up','many-impressions/20-help.webp','Several people collect papers and pencils from the floor.',['embarrassed','grateful','helpful'],['One person might feel embarrassed about dropping the materials.','The others seem helpful because they are picking things up.','I think the person receiving the notebook looks grateful.'],'have a heart of gold')]
frames=[('Appearance','She looks nervous.'),('General impression','She seems relieved.'),('Looks like + noun','He looks like a volunteer.'),('Looks like + complete idea','It looks like he needs help.'),('Feeling','I feel bored.'),('Cause','The instructions are confusing.'),('Opinion','I think she is worried.'),('A guess','I guess he is waiting for a friend.'),('A possibility','Perhaps she needs more time.'),('Another possibility','Maybe she is tired.'),('Give a clue','I think this because'),('Respond','That’s possible, but'),('Agree with a reason','I agree because')]
demo=[('Give an impression','She looks nervous.'),('Interpret the scene','It looks like a class presentation.'),('Feeling and possible cause','The classmates look interested. Perhaps the topic is interesting.'),('Opinion with a clue','I think she is preparing to speak because she is holding her notes.'),('Optional expression','A friendly question could help break the ice.')]
suggestions={
'cheer up':'Suggest a friendly action that could help someone feel happier. Do not assume the person is sad.',
'calm down':'Suggest a gentle way to relax if the person feels nervous. Avoid giving an impatient order.',
'open up':'Imagine a friendly question that could help someone share an impression. Sharing is optional.',
'fit in':'Explain what could help someone feel welcome in the group.',
'get along with':'Describe how the people seem to work together. Give a visible clue.',
'reach out to':'Imagine who the group could contact to offer or ask for help.',
'stand up for':'If someone were being left out, how could another person stand up for them? The image does not prove exclusion.',
'look up to':'Imagine why a learner might admire someone. Give a reason based on their actions.',
'break the ice':'Suggest a friendly question that could make the first conversation easier.',
'feel under the weather':'Use this only as a possibility about feeling a little ill. The picture does not prove illness.',
'be on cloud nine':'Use this if your interpretation involves very good news or strong happiness.',
'have a heart of gold':'Use this as a warm compliment for a helpful action, not as proof of someone’s whole personality.'}
scenes=[dict(id=i, title=t,image=base+img,alt=ctx,context=ctx,words=words,models=models,expression=expr,suggestion=suggestions[expr]) for i,(t,img,ctx,words,models,expr) in enumerate(rows)]
meta={'cheer up': {'kind': 'Phrasal verb', 'spanish': 'Animarse / animar a alguien'}, 'calm down': {'kind': 'Phrasal verb', 'spanish': 'Calmarse'}, 'open up': {'kind': 'Phrasal verb', 'spanish': 'Abrirse y hablar de los sentimientos'}, 'fit in': {'kind': 'Phrasal verb', 'spanish': 'Encajar / sentirse integrado'}, 'get along with': {'kind': 'Phrasal verb', 'spanish': 'Llevarse bien con'}, 'reach out to': {'kind': 'Phrasal verb', 'spanish': 'Contactar para ofrecer o pedir ayuda'}, 'stand up for': {'kind': 'Phrasal verb', 'spanish': 'Defender / apoyar'}, 'look up to': {'kind': 'Phrasal verb', 'spanish': 'Admirar / respetar'}, 'break the ice': {'kind': 'Idiom', 'spanish': 'Romper el hielo'}, 'feel under the weather': {'kind': 'Idiom', 'spanish': 'Sentirse indispuesto / un poco enfermo'}, 'be on cloud nine': {'kind': 'Idiom', 'spanish': 'Estar feliz de la vida'}, 'have a heart of gold': {'kind': 'Idiom', 'spanish': 'Tener un corazón de oro'}}
data=dict(title='One Picture, Many Impressions',scenes=scenes,frames=frames,demo=demo,expressions=meta)
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('Wrote 20 distinct scenes, 60 possible descriptions, reminders and demonstration.')
