"""Build the private-practice Unit 6 vocabulary and oral rehearsal game."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
PAGE='practice-unit-6-news-quest.html'
base=(ROOT/'ingles/intermediate-2/vocabulary-unit-6-greenford-news.html').read_text()
head=base.split('<main>')[0].replace('ie2-newsroom-page','ie2-quest-page').replace('#newsroom','#quest')
head=re.sub(r'<title>.*?</title>','<title>News Quest · Vocabulary and Speaking | Intermediate English Course 2</title>',head)
head=re.sub(r'<meta name="description"[^>]+>','<meta name="description" content="Practise twelve news words with picture and listening challenges, ElevenLabs models and private speaking rehearsal."/>',head)
head=re.sub(r'<link rel="stylesheet" href="[^"]*english-intermediate2-newsroom.css[^"]*"/>','<link rel="stylesheet" href="../../assets/css/english-intermediate2-news-quest.css?v=20261009-3"/>',head)
body='''<main>
<section class="u4-hero" aria-labelledby="quest-title"><img class="u4-hero-image" src="/assets/img/english-intermediate-2/unit-6/newsroom/reporter-v1.webp" alt="A reporter presents news from Greenford" width="1536" height="1024"/><div class="u4-hero-inner"><div class="ie2-unit4-hero-copy"><p class="intermediate2-kicker">Unit 6 · Practice Lab</p><h1 id="quest-title">News Quest</h1><p>See it. Hear it. Say it.</p><div class="ie2-overview-chips"><span>12 news words</span><span>Vocabulary + speaking</span><span>Private practice</span></div></div></div></section>
<section id="quest" class="quest-shell" aria-label="News Quest activity">
<p id="quest-loading" role="status">Loading your challenges…</p><button id="quest-load-retry" type="button" hidden>Try loading again</button>
<noscript>Please enable JavaScript to use this activity.</noscript>
<div id="quest-app" hidden>
<div class="quest-toolbar"><a href="./practice-lab.html#unit-6-folder">← Practice Lab</a><div><label><input type="checkbox" id="quest-voice" checked/> Voice</label><label><input type="checkbox" id="quest-effects" checked/> Effects</label><button type="button" id="quest-stop-audio">Stop audio</button><label>Speed <select id="quest-speed"><option value="1">1×</option><option value="0.75">0.75×</option></select></label></div></div>
<section id="quest-intro" class="quest-panel"><p class="quest-eyebrow">Three challenges · Three trophies</p><h2>Your news adventure</h2><p>Choose a trophy. Practise one skill at a time, with twelve words in each challenge.</p><div id="quest-trophies" class="quest-trophies"></div><div class="quest-actions"><button type="button" class="quest-primary" id="quest-start">Start challenge 1 →</button><button type="button" id="quest-preview">Review the 12 words</button></div><p class="quest-small">Trophies and progress last for this visit. You can replay any challenge.</p><details class="quest-help"><summary>How speaking practice works</summary><p>Listen, record and compare with the professional model. Automatic feedback checks the words the system understands; it does not measure individual sounds or accent.</p><p>When you record, your audio is sent to the Jaralingua server for recognition and discarded after processing. It is not submitted to your teacher or used for grades. You can practise without a microphone, but unverified turns do not earn the pronunciation trophy.</p></details></section>
<section id="quest-review" class="quest-panel" hidden><div class="quest-row"><h2>Meet the words</h2><button type="button" id="quest-review-close">Back</button></div><p>Hover or focus on a word for Spanish; tap or click to hear it.</p><div id="quest-cards"></div></section>
<section id="quest-game" class="quest-panel" hidden aria-label="Current challenge"><div class="quest-row"><span id="quest-count"></span><button type="button" id="quest-map">🏆 Trophy map</button><span id="quest-type" class="quest-tag"></span></div><progress id="quest-progress" max="36" value="0" aria-label="Challenges completed"></progress><div class="quest-row"><h2 id="quest-prompt" tabindex="-1"></h2><button type="button" id="quest-repeat-question">↻ Repeat question</button></div><div id="quest-stimulus"></div><div id="quest-model-controls" class="quest-actions"><button type="button" id="quest-listen">▶ Listen</button><button type="button" id="quest-slow">▶ Listen slowly</button></div><fieldset id="quest-options"><legend class="quest-sr">Choose one answer</legend><div id="quest-choices"></div></fieldset>
<div id="quest-speaking" hidden><div id="quest-speech-model"></div><button type="button" id="quest-reveal">Reveal the word and model</button><p id="quest-tip"></p><div class="quest-actions"><button type="button" id="quest-record" class="quest-primary">● Record my voice</button><button type="button" id="quest-record-stop" disabled>Stop recording</button><button type="button" id="quest-aloud">Repeat without a microphone</button></div><div class="quest-meter"><meter id="quest-level" min="0" max="1" value="0" aria-label="Microphone input level"></meter><span id="quest-timer">0 / 10 s</span></div><p id="quest-mic-status" role="status" aria-live="polite">Record to check which words the system understands.</p><audio id="quest-recording" controls hidden aria-label="Hear my recording"></audio><div id="quest-assessment" role="status" aria-live="polite"></div><button type="button" id="quest-assess-retry" hidden>Retry analysis</button><div id="quest-self-check" hidden><p>Compare with the model. Listen for the sound or stress in the tip above.</p><div class="quest-actions"><button type="button" data-self="ready">I feel ready ✓</button><button type="button" data-self="practice">I need more practice ↻</button></div></div><button type="button" class="quest-link" id="quest-skip">Skip speaking for now</button></div>
<div id="quest-feedback" role="status" aria-live="polite"></div><div class="quest-actions quest-footer"><button type="button" class="quest-primary" id="quest-check" disabled>Check</button><button type="button" id="quest-retry" hidden>Try again</button><button type="button" class="quest-primary" id="quest-next" hidden>Continue →</button></div></section>
<section id="quest-results" class="quest-panel" hidden><div id="quest-celebration" aria-hidden="true"></div><p class="quest-eyebrow">Challenge complete</p><h2 tabindex="-1" id="quest-finish-title">Your news vocabulary is growing</h2><div id="quest-summary"></div><h3>Words to revisit</h3><div id="quest-difficult"></div><div class="quest-actions"><button type="button" class="quest-primary" id="quest-practise-difficult">Practise my difficult words</button><button type="button" id="quest-phrases">Speak in sentences</button><button type="button" id="quest-next-stage" class="quest-primary">Next challenge →</button><button type="button" id="quest-restart">🏆 Trophy map</button></div><p class="quest-small">Practice feedback only. Voice results show recognized words, not a phonetic or academic grade.</p></section>
<p id="quest-audio-status" role="status" aria-live="polite"></p><a class="quest-story-link" href="./vocabulary-unit-6-greenford-news.html">Revisit the Greenford News story →</a>
</div></section></main><footer class="site-footer"><p>JaraLingua · Intermediate English Course 2</p></footer>
<script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20261003-persistent-signin"></script><script src="../../assets/js/english-intermediate2-news-quest.js?v=20261009-3"></script><script src="/assets/js/course-switcher.js"></script></body></html>'''
(ROOT/'ingles/intermediate-2'/PAGE).write_text(head+body)
print('Built '+PAGE)
