from pathlib import Path
import json,hashlib,html,sys
ROOT=Path.cwd();E=html.escape;stem='listening-unit-5-a-different-first-impression';dest=ROOT/'ingles/intermediate-2/audio/unit-5-listening'
turns=json.loads((dest/'dialogue.json').read_text(encoding='utf-8'))
questions=[
('What event are Sam and Maya preparing for?',['A student film festival','A community food collection','A job interview'],'b','Sam asks whether they are ready for the community food collection.'),
('What is Alex doing when Sam first notices him?',['Sitting alone with a notebook','Carrying boxes through the door','Talking to a group of guests'],'a','Sam describes Alex sitting alone with a notebook.'),
('What is Sam’s first impression of Alex?',['He seems very experienced','He seems excited to meet everyone','He looks bored and uninterested'],'c','Sam says Alex looks bored. Later, he admits that he thought Alex was not interested.'),
('What alternative explanation does Maya suggest?',['Alex might be concentrating','Alex must be angry with Sam','Alex cannot understand the instructions'],'a','Maya says he might simply be concentrating. She does not treat his silence as proof of boredom.'),
('What does Maya explain about Alex’s notebook?',['He is writing a complaint about the event','He is drawing a poster for the door','He is checking the guest list and learning names'],'c','Maya explains that Alex is checking the guest list and trying to learn everyone’s names.'),
('Why does Sam think Maya must be tired?',['She says she did not sleep last night','She has been working since six that morning','She has just finished a long journey'],'b','Sam supports his deduction with the fact that Maya has been working since six that morning.'),
('Why did Maya feel confused at first?',['The instructions were confusing','She could not find Alex’s notebook','The guests had arrived at the wrong place'],'a','Maya says, “I felt confused because the instructions were confusing.”'),
('Why is the poster satire rather than a real report?',['It gives the wrong time for the event','It tells volunteers to stop working','It imagines coffee cups asking for a holiday'],'c','Maya calls it satire: cups cannot ask for holidays. The joke exaggerates how busy the volunteers have been.'),
('What does “break the ice” mean in this conversation?',['Make the drinks colder','Help start a friendly conversation','Finish moving the heavy boxes'],'b','Maya suggests a friendly question to help Alex begin talking with them.'),
('What does Sam plan to do next?',['Invite Alex to help with the boxes and hear his story','Tell Alex to leave the event','Ignore Alex until the food collection ends'],'a','Sam offers to invite Alex to help with the boxes and says he wants to hear his story.')]
vocab=[('impression','An idea you form about someone or something.'),('concentrating','Giving your attention to a task.'),('confused','Not understanding clearly: a person’s feeling.'),('confusing','Difficult to understand: something that causes the feeling.'),('tiring','Making someone feel tired.'),('satire','Humor or exaggeration used to comment on a situation.'),('break the ice','Help people feel comfortable and start talking.')]
noticing=[('A possibility','He might simply be concentrating.','Might leaves room for other explanations. Being quiet does not prove boredom.'),('A strong deduction','And you must be tired.','Sam gives evidence: Maya has worked since six. Must expresses a deduction here, not an obligation.'),('Feeling and cause','At first, I felt confused because the instructions were confusing.','Confused describes Maya’s feeling. Confusing describes the instructions that caused it.'),('A strong negative deduction','That can’t be a real news report.','Sam rules out a literal report about cups asking for a holiday. Maya confirms that it is satire.'),('A contrast','The poster is funny, although the work is tiring.','Although connects two contrasting ideas: a funny poster and tiring work.'),('A friendly action','A friendly question can help break the ice.','The idiom means help people start a conversation and feel comfortable.')]
texts=[w for w,_ in vocab]+[t for _,t,_ in noticing];existing={}
for folder in ['unit-5-explanation','unit-5-picture','unit-5-grammar']:
 for a in json.loads((ROOT/'ingles/intermediate-2/audio'/folder/'models.json').read_text(encoding='utf-8'))['items']:existing[a['text']]='audio/'+folder+'/'+a['file']
prior=json.loads((dest/'models.json').read_text(encoding='utf-8')) if (dest/'models.json').exists() else {'items':[]};old={x['text']:x for x in prior['items']};items=[];audio={}
for t in texts:
 if t in existing:audio[t]=existing[t];continue
 key=hashlib.sha256(t.encode()).hexdigest()[:14];a=dict(id=key,file=key+'.mp3',text=t,kind='phrase');a.update({k:old[t][k] for k in ('bytes','sha256') if t in old and k in old[t]});items.append(a);audio[t]='audio/unit-5-listening/'+a['file']
(dest/'models.json').write_text(json.dumps(dict(voiceId='EXAVITQu4vr4xnSDxMaL',modelId='eleven_multilingual_v2',items=items),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
config=dict(questions=[dict(prompt=p,options=o,answer=a,evidence=f) for p,o,a,f in questions],audio=audio)
(ROOT/'assets/data/english-intermediate2-unit5-listening.json').write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def say(t):return '<button type="button" class="u5l-say" data-word-audio="'+audio[t]+'" aria-pressed="false" aria-label="Listen: '+E(t)+'">'+E(t)+'<span aria-hidden="true"> ◖))</span></button>'
source=(ROOT/'ingles/intermediate-2/listening-unit-3-the-message-before-the-workshop.html').read_text(encoding='utf-8');head=source.split('  <main>')[0].replace('The Message Before the Workshop','A Different First Impression').replace('Unit 3 listening story about a suspicious support message, a technical problem and an unauthorized account login.','A short Unit 5 dialogue about first impressions, feelings and evidence, with ten questions and transcript support.').replace('ie2-message-listening-page','ie2-u5-listening-page').replace('#unit-3-folder','#unit-5-folder')
head=head.replace('</head>','<link rel="canonical" href="https://www.jaralingua.com/ingles/intermediate-2/'+stem+'.html"/><link rel="stylesheet" href="../../assets/css/english-intermediate2-unit5-listening.css?v=20260925-teacher2"/></head>')
body='''<main><section class="ie2-listening-hero" aria-labelledby="listening-title"><div class="ie2-listening-hero-content"><p class="intermediate2-kicker">Unit 5 Listening · Feelings and first impressions</p><h1 id="listening-title">A Different First Impression</h1><p>Sam notices a quiet volunteer. Maya helps him consider another explanation.</p><div class="ie2-listening-hero-chips"><span>1:24 at 1×</span><span>2 voices</span><span>3 listening passes</span><span>10 questions</span></div><div class="intermediate2-actions"><a class="intermediate2-button primary" href="#listening-player">Start listening</a><a class="intermediate2-button ghost" href="./practice-lab.html#unit-5-folder">Practice Lab</a></div></div></section>
<section class="intermediate2-search course-search-panel" data-course-search-panel data-search-target="#listening-activity" data-search-items=".ie2-search-item" aria-label="Search this listening"><label class="course-search-label" for="impressionSearch">Search this listening</label><div class="course-search-row"><input id="impressionSearch" type="search" data-course-search-input placeholder="Try: feelings, evidence, satire..." autocomplete="off"/><button class="course-search-clear" type="button" data-course-search-clear hidden>Clear</button></div><p class="course-search-meta"><span data-course-search-count></span></p></section><p class="course-search-empty" data-course-search-empty hidden>No matching section found.</p>
<div class="ie2-listening-shell" id="listening-activity">
<section class="ie2-listening-block ie2-search-item" id="before-listening" data-search-keywords="route gist details evidence language"><p class="intermediate2-kicker">Your listening route</p><h2>One conversation, three purposes</h2><div class="ie2-listening-focus-grid"><article><span>01</span><h3>Understand the main idea</h3><p>How does Sam’s impression change?</p></article><article><span>02</span><h3>Collect the evidence</h3><p>What do they observe? What does Maya know?</p></article><article><span>03</span><h3>Notice the language</h3><p>Listen for might, must, can’t and feelings.</p></article></div></section>
<section class="ie2-listening-block ie2-search-item" data-search-keywords="vocabulary impression concentrating confused confusing tiring satire break ice"><p class="intermediate2-kicker">Vocabulary preview</p><h2>Open only what you need</h2><div class="ie2-listening-vocab-grid">VOCAB</div></section>
<section class="ie2-listening-block ie2-search-item" data-search-keywords="prediction quiet volunteer"><p class="intermediate2-kicker">Before listening</p><h2>What might a quiet volunteer be doing?</h2><div class="ie2-prediction-options" role="group" aria-label="Choose a prediction"><button type="button" data-prediction="Waiting for someone" aria-pressed="false">Waiting for someone</button><button type="button" data-prediction="Concentrating on a task" aria-pressed="false">Concentrating on a task</button><button type="button" data-prediction="Feeling unsure about joining in" aria-pressed="false">Feeling unsure about joining in</button></div><p id="predictionStatus" role="status">Make a prediction, then listen. Predictions are not graded.</p></section>
<section class="ie2-listening-block ie2-search-item" id="listening-player" data-search-keywords="audio Sam Maya first second third speed"><div class="ie2-listening-heading"><div><p class="intermediate2-kicker">Professional audio</p><h2>Sam and Maya at the community center</h2></div><span>General American English</span></div><div class="ie2-audio-card"><div class="ie2-speaker-row"><div class="ie2-speaker-avatar" aria-hidden="true">S+M</div><div><strong>Sam + Maya</strong><span>Two volunteers preparing a community food collection</span></div></div><audio id="impressionAudio" controls preload="metadata" src="audio/unit-5-listening/a-different-first-impression.mp3">Your browser does not support audio. Ask your teacher for support.</audio><div class="ie2-audio-controls" role="group" aria-label="Playback speed"><span>Speed</span><button type="button" data-audio-speed="0.75" class="is-active" aria-pressed="true">0.75×</button><button type="button" data-audio-speed="1" aria-pressed="false">1×</button><button type="button" data-audio-speed="1.25" aria-pressed="false">1.25×</button></div><p id="audioStatus" class="ie2-audio-status" role="status">Ready at 0.75×. Listen for the clues.</p><button type="button" class="intermediate2-button" id="retryAudio" hidden>Retry audio</button><div id="teacherTools" class="u5l-teacher-tools" hidden><button type="button" class="intermediate2-button" id="transcriptToggle" aria-expanded="false" aria-controls="teacherTranscript">Teacher transcript</button><div id="teacherTranscript" hidden><h3>Sam and Maya · Transcript</h3><div id="transcriptText"></div></div></div></div><div class="ie2-listen-pass-grid">PASSES</div><p id="passStatus" class="ie2-listening-progress" role="status">Listening self-check: 0 of 3 passes marked.</p></section>
<section class="ie2-listening-block ie2-search-item" id="listening-check" data-search-keywords="questions answers comprehension evidence Alex notebook guest list six instructions poster"><p class="intermediate2-kicker">Listening check</p><h2>Choose the answer supported by the conversation</h2><form class="ie2-reading-quiz" id="impressionQuiz">QUESTIONS<div class="ie2-reading-actions"><button type="submit" class="intermediate2-button primary">Check my answers</button><button type="reset" class="intermediate2-button">Reset answers</button></div><p id="quizResult" class="ie2-reading-result" role="status"></p></form></section>
<section class="ie2-listening-block ie2-search-item" data-search-keywords="language grammar might must can’t although confused confusing evidence idiom"><p class="intermediate2-kicker">Language noticing</p><h2>How the speakers explain their ideas</h2><div class="ie2-language-detective">NOTICING</div></section>
<section class="ie2-listening-block ie2-search-item" id="speak" data-search-keywords="speaking respond opinion explanation timer"><p class="intermediate2-kicker">Speak from what you heard</p><h2>Explain the change in 45 seconds</h2><p>Describe Sam’s first impression, give the evidence that changed it and explain what you would say to Alex. Then listen to your partner’s idea and respond.</p><div class="ie2-speaking-prompt-grid"><article><strong>First impression</strong><span>At first, Sam thought…</span></article><article><strong>Evidence</strong><span>Maya explained that…</span></article><article><strong>Your response</strong><span>I would ask Alex…</span></article><article><strong>Listen and respond</strong><span>That’s possible, but…</span></article></div><div class="ie2-rehearsal-timer"><div><span>Speaking timer</span><strong id="speakingTimer" role="timer">00:45</strong></div><button type="button" class="intermediate2-button primary" id="toggleTimer">Start 45 seconds</button><button type="button" class="intermediate2-button" id="resetTimer">Reset timer</button></div><p id="timerStatus" role="status"></p><p class="ie2-private-note">Practice only. Answers and checkmarks stay on this page until you reload.</p></section>
<section class="ie2-reading-next ie2-search-item" data-search-keywords="more practice grammar unit 5"><div><p class="intermediate2-kicker">Keep practicing</p><h2>Use the clues in a new situation</h2></div><div class="ie2-reading-actions"><a class="intermediate2-button primary" href="./grammar-unit-5-read-the-clues.html">Read the Clues</a><a class="intermediate2-button" href="./unit-5-impressions-feelings-and-satire.html">Review Unit 5</a><a class="intermediate2-button" href="./listening-library.html#unit-5-listenings">Listening Library</a></div></section>
</div></main><footer class="site-footer"><p>&copy; 2026 JaraLingua. Intermediate English Course 2 listening practice.</p></footer><script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20260919-local-login"></script><script src="../../assets/js/course-search.js?v=20260905-unit3-listening"></script><script src="../../assets/js/english-intermediate2-unit5-listening.js?v=20260925-teacher2"></script><script src="/assets/js/course-switcher.js"></script><script src="/assets/js/page-qr-access.js"></script></body></html>
'''
body=body.replace('VOCAB',''.join('<details><summary>'+E(w)+'</summary>'+say(w)+'<p>'+E(d)+'</p></details>' for w,d in vocab))
body=body.replace('PASSES',''.join('<article><h3>'+title+'</h3><p>'+text+'</p><button type="button" class="intermediate2-button" data-pass="'+str(i)+'" aria-pressed="false">Mark listen '+str(i)+' complete</button></article>' for i,(title,text) in enumerate([('First listen · Main idea','Why does Sam change his first impression?'),('Second listen · Evidence','Find what Alex is doing and why Maya feels tired.'),('Third listen · Language','Notice deductions, feelings and the poster’s joke.')],1)))
qs=[]
for i,(prompt,options,answer,feedback) in enumerate(questions,1):
 labels=''.join(f'<label><input type="radio" name="q{i}" value="{chr(97+j)}" aria-describedby="feedback{i}"/><span><b class="u5l-option-letter">{chr(65+j)}.</b> {E(text)}</span></label>' for j,text in enumerate(options))
 qs.append(f'<article class="ie2-reading-question" data-answer="{answer}" data-feedback="{E(feedback)}"><h3>{i}. {E(prompt)}</h3><fieldset><legend class="u5l-sr">Question {i}: choose one answer</legend>{labels}</fieldset><p id="feedback{i}" class="ie2-question-feedback" aria-live="polite"></p></article>')

body=body.replace('QUESTIONS',''.join(qs)).replace('NOTICING',''.join('<article><h3>'+E(title)+'</h3><p>'+say(text)+'</p><details><summary>Why this language?</summary><p>'+E(why)+'</p></details></article>' for title,text,why in noticing))
(ROOT/'ingles/intermediate-2'/f'{stem}.html').write_text(head+body,encoding='utf-8')
sys.path.insert(0,str(ROOT/'tmp/unit5-explanation/python-deps'));import qrcode,qrcode.image.svg
qrcode.make('https://www.jaralingua.com/ingles/intermediate-2/'+stem+'.html',image_factory=qrcode.image.svg.SvgPathImage,box_size=10,border=4).save(ROOT/'assets/img/page-qr'/('ingles-intermediate-2-'+stem+'.svg'))
print('Built listening, ten evidence questions, QR and',len(items),'new pronunciation clips.')
