"""Build the Unit 6 explanation from the established teaching shell and verified media."""
from pathlib import Path
import html,json,re
ROOT=Path(__file__).resolve().parents[1]
PAGE='unit-6-news-and-natural-disasters.html'
models=json.loads((ROOT/'ingles/intermediate-2/audio/unit-6-explanation/models.json').read_text())
audio={x['id']:x for x in models['items']}
media=json.loads((ROOT/'assets/data/english-intermediate2-unit6-media.json').read_text())
images={x['id']:x for x in media['images']}
def esc(s):return html.escape(str(s),quote=True)
def say(key,label=None):
 a=audio[key]; meaning=f' data-u6-meaning="{esc(a["spanish"])}"' if a.get('spanish') else ''
 return f'<button type="button" class="u6-say" data-u6-say="{esc(a["file"])}" aria-pressed="false" aria-label="Listen: {esc(label or a["text"])}"{meaning}>{esc(label or a["text"])}<span aria-hidden="true"> ◖))</span></button>'
def model(key):return '<p class="u4-model">'+say(key)+'</p>'
def card(title,body):return '<article class="u4-card"><h3>'+title+'</h3>'+body+'</article>'
def grid(*items,cols=2):return f'<div class="u6-grid u6-cols-{cols}">'+''.join(items)+'</div>'
def note(title,text):return '<aside class="u4-note"><strong>'+title+'</strong><p>'+text+'</p></aside>'
def table(head,rows):return '<div class="u6-table"><table><thead><tr>'+''.join('<th scope="col">'+h+'</th>' for h in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td data-label="{esc(head[i])}">{c}</td>' for i,c in enumerate(row))+'</tr>' for row in rows)+'</tbody></table></div>'
def scene(key,title,body):
 im=images[key]
 return f'''<article class="u4-card u6-scene" data-project-title="{esc(re.sub(r"<[^>]+>", "", title))}"><button type="button" class="u4-project-open" aria-label="Enlarge: {esc(re.sub(r"<[^>]+>", "", title))}" aria-haspopup="dialog"><img src="{im["image"]}" width="{im["width"]}" height="{im["height"]}" alt="{esc(im["alt"])}" loading="lazy" decoding="async"/><span class="u4-project-hint">Enlarge ↗</span></button><div class="u4-card-copy"><h3>{title}</h3>{body}<p>{say(key,'Listen to the explanation')}</p><details class="u6-transcript"><summary>Audio text</summary><p>{esc(audio[key]['text'])}</p></details></div></article>'''
definitions={
'headline':'The title of a news story. It introduces the main point.', 'source':'The person, document or organization that provides information.', 'reporter':'A person who gathers information and presents news.', 'witness':'Someone who saw or experienced an event.', 'statement':'Something a person or organization says formally.', 'evidence':'Information that supports or challenges a claim.', 'fact':'Something that is true and can be checked.', 'opinion':'A personal judgement or belief.', 'rumour':'Information being shared without confirmation.', 'claim':'An assertion that needs to be checked; it may be true or false.', 'council':'A group responsible for decisions in a town or local area.', 'spokesperson':'Someone who speaks on behalf of a group or organization.', 'announcement':'A public statement giving news or information.', 'damage':'Harm to buildings, objects or places. Usually uncountable in this meaning.', 'rescue crew':'A team that helps people in danger.', 'shelter':'A place that provides protection or temporary accommodation.', 'warning':'A message about possible danger or a problem.', 'supplies':'Things people need, such as water, food or equipment.', 'power outage':'A period when the electricity supply stops.', 'fallen tree':'A tree that has fallen to the ground.', 'bulletin':'A short news report or official update.'}
def words(*terms):return grid(*(card(say('word-'+w.replace(' ','-')), '<p>'+definitions[w]+'</p>') for w in terms),cols=3)
topics=[];nav=[]
def topic(id,title,intro,body,short=None):
 nav.append((id,short or title));n=len(topics)+1
 topics.append(f'<details class="ie2-theory-topic ie2-search-item" id="{id}" data-search-keywords="{esc(title)}"><summary><span class="ie2-topic-index">{n:02}</span><span class="ie2-topic-summary"><strong>{title}</strong><small>{intro}</small></span><span class="ie2-topic-toggle" aria-hidden="true">+</span></summary><div class="ie2-theory-body"><div class="ie2-key-answer"><span>Meaning, form and use</span><h2>{title}</h2><p>{intro}</p></div><button class="intermediate2-button u6-project-section" type="button" aria-haspopup="dialog">Project explanation ↗</button>{body}</div></details>')
topic('news','Understanding the news','Identify the event, the source and what the report actually tells you.',
scene('checking-sources','Check the source before sharing','<p>The editor compares the bridge in two photographs. A matching location is a useful clue; the date and original source still matter.</p>')+
words('headline','source','reporter','witness','statement','evidence')+
table(['Question','Fictional example'],[['What happened?','A storm damaged a library.'],['Where and when?','In Greenford, on Monday.'],['Who provided the information?','A local resident and a council spokesperson.'],['What is still unknown?','The full extent of the roof damage.']])+note('A headline is only the beginning','Read the report before drawing a conclusion. An image does not establish a date, a cause or a number of people affected.'),'News basics')
topic('facts','Facts, opinions and rumours','Keep confirmed information separate from interpretation and unverified claims.',
words('fact','opinion','rumour','claim')+table(['Message','What kind?','How to handle it'],[
['The library is closed. The council posted a closure notice.','A checkable report with a named source.','Check that the notice is current and refers to this library.'],['I think the repairs should be the council’s priority.','An opinion.','Explain the reason; do not present the preference as a fact.'],['Someone online says the library will never reopen.','An unverified claim or rumour.','Find the original source and supporting evidence before repeating it.']])+model('cautious-reporting')+
note('Reporting a statement does not confirm its content','“A resident said…” tells us who made the statement. It does not guarantee that the statement is accurate. A claim may later be confirmed or disproved.')+
note('Connection with Unit 5','Satire uses humour or exaggeration to comment on an issue. A surprising headline is not automatically satire, and satire is not the same thing as an unverified rumour.'),'Facts & rumours')
topic('direct-reported','What did they say?','Compare the speaker’s original words with a later report.',
grid(scene('witness-interview','Maya speaks to the reporter',model('direct-worried')+'<p><b>Direct speech:</b> quotation marks show Maya’s exact words. <b>I</b> refers to Maya.</p>'),scene('reporting-the-interview','The reporter tells his editor',model('reported-worried')+'<p><b>Reported speech:</b> the reporter gives Maya’s message from his point of view. He refers to her as <b>she</b>.</p>'))+
table(['Original words','Later report','Reason'],[['I','she','The journalist is talking about Maya.'],['am','was','He looks back at her earlier statement.'],['“I am worried…”','She said that she was worried…','The whole sentence is a report, not a direct quotation.']])+note('Keep the message faithful','Do not turn “I am worried” into “She was terrified.” Changing the grammar should not exaggerate the person’s meaning.'),'Direct → reported')
topic('say-tell','Say, tell and reported statements','Build a report with a reporting verb and a complete idea.',
model('said-told')+table(['Pattern','Model','What to notice'],[['Subject + said + (that) + idea','Maya said (that) she was worried.','Said does not need a listener here.'],['Subject + told + listener + (that) + idea','Maya told the reporter (that) she was worried.','Name the listener after told: me, us, the reporter.'],['Subject + said + to + listener','Maya said to the reporter, “I am worried.”','Use to when you name a listener after said.']])+
grid(card('That is optional','<p><b>Maya said that she was worried.</b><br><b>Maya said she was worried.</b></p><p>Both are correct. That connects the reporting verb to the message; it does not replace the subject.</p>'),card('Negatives belong to the message','<p>“I am not ready.” → She said she <b>was not ready</b>.</p><p>Keep the negative meaning. “She didn’t say she was ready” describes what she did not say; it is a different message.</p>'))+
table(['Avoid','Use','Why'],[['She said me the news.','She told me the news.','Tell takes a listener directly.'],['She told that she was worried.','She told us that she was worried.','For a reported statement, told needs a listener.'],['She said was worried.','She said she was worried.','The reported idea needs its own subject.']]),'Say / tell')
topic('changes','What changes when we report?','Adjust the grammar to the speaker, the time and the place of the report.',
note('Backshift: looking back from a later time','With a past reporting verb such as said, we often move the original verb one step back. Start with these common changes. A past form in a report does not prove that the situation has ended.')+
table(['Direct speech','Later report','Change'],[[say('direct-worried'),say('reported-worried'),'am → was'],[say('direct-will'),say('reported-will'),'will → would'],[say('direct-can'),say('reported-can'),'can → could'],['“We need help.”','They said they needed help.','present simple → past simple'],['“We are checking the roof.”','They said they were checking the roof.','present continuous → past continuous']])+
table(['Reference','Example','Check the situation'],[['Person','“I lost my bag.” → Maya said she had lost her bag.','I and my refer to Maya, so the reporter uses she and her.'],['Time','On Tuesday: “tomorrow” → reporting on Thursday: “the following day”','The original tomorrow meant Wednesday. Do not accidentally change the date.'],['Place','“here” → “there” when reporting from another place','If you are still in the same place, here may remain appropriate.']])+
grid(card('Still true now',model('still-true')+'<p>If the library remains closed, a present form can show that the information is still current. <b>Was still closed</b> is also possible when reporting the earlier statement.</p>'),card('Reporting immediately','<p><b>The singer says she can perform on Saturday.</b></p><p>With says in the present, we normally do not backshift just because we are reporting. Keep time words when their reference has not changed.</p>'))+
'<details class="u6-support"><summary>Extra support · earlier past events</summary><p>Present perfect often becomes past perfect: “I have checked the source.” → She said she <b>had checked</b> the source.</p><p>Past simple can become past perfect: “I saw the tree fall.” → She said she <b>had seen</b> the tree fall. Past simple is also possible when the timing is already clear.</p><p>Past perfect stays past perfect. Would, could, should and might usually stay the same. These are extensions; master the main patterns first.</p></details>','Grammar changes')
topic('discussion','Discuss political and entertainment news','Attribute the information, explain your view and respond respectfully.',
grid(scene('community-press-conference','A council promise',model('direct-will')+'<p>Report who made the promise and when. Later, check what actually happened.</p>'),scene('entertainment-interview','A concert announcement',model('direct-can')+'<p>A statement from the singer is stronger evidence than an anonymous post about her plans.</p>'))+
words('council','spokesperson','announcement')+model('source-attribution')+
table(['Purpose','Useful language'],[['Name the source','According to the council… / The spokesperson said…'],['Explain controversy','Some residents support the plan because… Others disagree because…'],['Give a reason','I think the library should reopen soon because students use it to study.'],['Disagree respectfully','I understand your point, but I would like to see the repair report first.'],['Ask for evidence','Where did that information come from? Has it been confirmed?']])+
note('A resolved model','“The council announced a repair plan. Some residents think it is too slow because the library is their main study space. Others support the inspection because they want the building checked carefully. I would compare the proposed dates and the inspection findings before deciding.”')+
note('Discuss the issue, not private lives','In these fictional examples, focus on public statements, decisions and evidence. You can explain different viewpoints without sharing your own political affiliation or spreading personal rumours.'),'Discuss the news')
disasters=[('earthquake','A sudden shaking of the ground.','The earthquake damaged several buildings.'),('flood','Water covering land that is normally dry.','The river overflowed and flooded the street.'),('hurricane','A powerful tropical storm with strong winds and heavy rain.','The hurricane damaged homes near the coast.'),('drought','A long period with much less rain than a place needs.','Water levels fell during the drought.'),('wildfire','An uncontrolled fire spreading through vegetation.','The wildfire burned part of the wooded hillside.'),('landslide','Rock, soil or other material moving down a slope.','The landslide blocked the mountain road.')]
topic('disasters','Natural disasters and their effects','Name the event and describe the effects without inventing details.',
grid(*(scene(key,say('word-'+key),'<p>'+definition+'</p><p class="u4-model">'+example+'</p>') for key,definition,example in disasters),cols=3)+
words('damage','rescue crew','shelter','warning','supplies','power outage','fallen tree')+
note('Damage or damages?','For physical harm, use <b>damage</b>: “The storm caused damage.” To count, say “three damaged buildings.” Damages has a separate legal meaning; it is not the plural we need here.')+
note('An image cannot confirm every detail','These are generated teaching scenes. A real report needs verified dates, locations, causes and figures. Describe what is visible and identify what still needs confirmation.'),'Disaster vocabulary')
topic('past-events','Reporting what happened','Use past simple for completed events and connectors for their order.',
model('past-sequence')+table(['Base form','Past form','News example'],[['hit','hit','A storm hit the town on Monday.'],['fall','fell','A tree fell near the library.'],['damage','damaged','The storm damaged the roof.'],['rescue','rescued','The crew rescued two residents.'],['close','closed','Workers closed the road.'],['inspect','inspected','Engineers inspected the bridge.']])+
grid(card('Affirmative','<p><b>Subject + past verb</b><br>The storm damaged the roof.</p><p>Use a finished-time expression when known: on Monday, yesterday, last night.</p>'),card('Negative and question','<p>The storm <b>did not damage</b> the school.<br><b>Did</b> the storm <b>damage</b> the school?</p><p>After did or didn’t, use the base form. Avoid “did damaged.”</p>'))+
table(['Sequence','Model'],[['First','First, the storm hit Greenford.'],['Then','Then, a tree fell near the entrance.'],['Later / after that','Later, workers inspected the roof.'],['Finally','Finally, the council issued an update.']])+
note('Two different jobs','<b>The storm damaged the roof</b> directly reports a past event. <b>Maya said the storm had damaged the roof</b> reports Maya’s earlier statement. The second sentence also identifies the source.')+
'<h3>Hear the endings</h3>'+model('past-endings')+'<p><b>Reported</b> ends in /ɪd/; <b>damaged</b> and <b>rescued</b> end in /d/. Keep the ending audible without adding an extra syllable to every past verb.</p>','Past & sequence')
topic('instructions','Instructions and action plans','Distinguish direct instructions, advice and a report of someone’s instructions.',
scene('community-briefing','An information plan',model('information-plan')+'<p>Identify who provides the updates, what the group should check and how confirmed information will be shared.</p>')+
table(['Function','Form','Example'],[['Instruction','Base verb','Check official alerts.'],['Negative instruction','Do not + base verb',say('flood-instruction')],['Advice','should + base verb','You should check the source before sharing the update.'],['Reported instruction','told + listener + to + base verb',say('reported-instruction')],['Reported negative instruction','told + listener + not to + base verb',say('reported-negative-instruction')]])+
note('To check, not to checked','After told someone to, use the base verb: “She told us to check.” The past tense is in told. Use not before to for the negative: “She told us not to enter.”')+
'<p class="u6-source">Flood example adapted from <a href="https://www.ready.gov/floods" target="_blank" rel="noopener">Ready.gov: Floods</a>. During a real emergency, follow the instructions for your location and the specific hazard. This lesson practises English for communicating information.</p>','Instructions')
expression_notes={
'find out':('Learn or discover information.','Transitive and separable in this noun-object pattern.','find out the cause / find the cause out / find it out','Also: find out what happened. Keep a full what-clause after out.','Link find‿out; give out a clear stress.'),
'check out':('Examine something to see whether it is accurate or useful.','Transitive and separable in this meaning.','check out the claim / check the claim out / check it out','Conversational. Verify is a more formal alternative.','Link check‿out; keep the final /t/.'),
'carry out':('Perform or complete a task.','Transitive and separable.','carry out an inspection / carry an inspection out / carry it out','Common in formal reports. The first noun order is often smoother with long objects.','Link carry‿out; stress the key task.'),
'point out':('Draw attention to something.','Transitive and separable.','point out the damage / point the damage out / point it out','It can also introduce a clause: she pointed out that the road was closed.','Keep point and out connected without losing the /t/.'),
'clear up':('Remove confusion or make something understandable.','Transitive and separable in this meaning.','clear up the confusion / clear the confusion up / clear it up','Here it means clarify, not improve weather or tidy a room.','Link clear‿up; stress up.'),
'word of mouth':('Information passed from one person to another.','Fixed idiomatic expression.','The rumour spread by word of mouth.','Everyday language. Being widely repeated does not confirm a report.','Say by word of mouth as one group.'),
'make headlines':('Attract prominent attention in the news.','Idiomatic expression.','The concert announcement made headlines.','Common in media reporting; it does not mean physically creating a headline.','Stress headlines; make changes to made in the past.'),
'take it with a grain of salt':('Treat information with some doubt.','Idiom.','The story has no named source, so take it with a grain of salt.','Informal. It expresses caution, not proof that a claim is false.','Keep with a grain of salt together as one group.')}
expressions=[]
for term,(meaning,grammar,order,usage,sound) in expression_notes.items():
 key='expression-'+term.replace(' ','-');item=audio[key]
 expressions.append(card(say(key,term),f'<span class="u6-expression-type">{item["expressionType"]}</span><p>{meaning}</p><p class="u6-expression-spanish">{esc(item["spanish"])}</p><p><b>Grammar:</b> {grammar}</p><p><b>Model:</b> {order}</p><p>{usage}</p><p><b>Sound:</b> {sound}</p>'))
topic('bulletin','Expressions and a complete news bulletin','Bring together a clear source, ordered events and faithful reported speech.',
grid(card('What is a phrasal verb?','<p>A verb and a particle work together as one expression: <b>carry + out</b> means perform. In the separable examples below, a pronoun goes between the verb and particle: <b>carry it out</b>.</p>'),card('What is an idiom?','<p>An expression has a conventional meaning that may go beyond its individual words. <b>Take it with a grain of salt</b> asks the listener to be cautious; it is not about food.</p>'))+
grid(*expressions,cols=4)+note('Common error','Use “check it out,” not “check out it.” For a noun, both “check out the claim” and “check the claim out” work. The pronoun rule applies to the separable meanings shown here.')+
words('bulletin')+scene('television-bulletin','Model bulletin · a fictional report','<p>Listen for the event, the timeline, the witness’s statement and what remains unconfirmed. The full model is under Audio text.</p>')+
table(['Part','What the model does'],[['Opening','Introduces the storm and the library.'],['Events','Tells what happened on Monday, then describes later actions.'],['Attributed statement','Reports Maya’s concern and the spokesperson’s promise.'],['Uncertainty','Explains that the cause of the roof damage is still being investigated.'],['Closing','Promises an update when more information is confirmed.']])+
note('A model for the classroom task','For the later TV bulletin task, plan an opening, verified events, one attributed statement, relevant official instructions and a closing. A presenter, reporter and witness can share the roles. First understand this model; practice activities belong in Practice Lab.')+
'<details class="u6-support"><summary>Check the language references</summary><p>The examples are original and fictional. For further grammar support, see <a href="https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2/reported-speech-statements" target="_blank" rel="noopener">British Council: reported speech statements</a>.</p><p>Course sequence: <a href="downloads/Intermediate_Course_2_Easy_Guide.docx">Intermediate Course 2 Easy Guide</a>, sessions 15–16.</p></details><div class="intermediate2-actions"><a class="intermediate2-button primary" href="./course-overview.html#unit-6">Back to Course Overview</a><a class="intermediate2-button" href="./practice-lab.html">Practice Lab</a><a class="intermediate2-button" href="../intermediate/idioms.html">Shared expression library</a></div>','Expressions & bulletin')
base=(ROOT/'ingles/intermediate-2/unit-4-movies-music-and-reviews.html').read_text()
head=base.split('<main>')[0].replace('Unit 4: Movies, Reviews, Music Videos and Trends','Unit 6: News, Reported Speech and Natural Disasters').replace('ie2-unit4-theory-page','ie2-unit4-theory-page ie2-unit6-theory-page').replace('#unit4-content','#unit6-content').replace('#unit-4','#unit-6')
head=re.sub(r'<meta name="description"[^>]+>', '<meta name="description" content="Learn to report news, use said and told, describe natural disasters and build a bulletin with illustrated explanations and spoken models."/>',head)
head=head.replace('</head>','<link rel="stylesheet" href="../../assets/css/english-intermediate2-unit6-explanation.css?v=20261007-1"/></head>')
hero=images['newsroom-hero']
opening=f'''<main><section class="u4-hero" aria-labelledby="unit6-title"><img class="u4-hero-image" src="{hero['image']}" alt="{hero['alt']}" width="{hero['width']}" height="{hero['height']}" fetchpriority="high" decoding="async"/><div class="u4-hero-inner"><div class="ie2-unit4-hero-copy"><p class="intermediate2-kicker">Unit 6 · Sessions 15–16</p><h1 id="unit6-title">News, Reported Speech<br>and Natural Disasters</h1><p>Check the source. Report the message.<br>Tell the story clearly.</p><div class="ie2-overview-chips"><span>News &amp; sources</span><span>Reported speech</span><span>Events &amp; action plans</span></div><div class="intermediate2-actions"><a class="intermediate2-button primary" href="#unit6-content">Explore the lesson</a><a class="intermediate2-button ghost" href="./course-overview.html#unit-6">Course map</a></div></div></div></section><div class="u4-shell"><section class="u4-opening"><div><p class="intermediate2-kicker">Meaning, form and sound</p><h2>From a source to a clear report</h2><p>Learn to distinguish claims from evidence, report a speaker’s message and describe past events. All illustrated news stories here are fictional teaching examples.</p>{say('newsroom-hero','Listen to the introduction')}<details class="u6-transcript"><summary>Audio text</summary><p>{esc(audio['newsroom-hero']['text'])}</p></details></div><ol class="u4-route"><li><b>01 · Notice</b>Identify the source and the message.</li><li><b>02 · Compare</b>See what changes when you report.</li><li><b>03 · Understand</b>Connect grammar with meaning.</li><li><b>04 · Listen</b>Follow a complete news model.</li></ol></section><div class="u6-audio-settings" role="group" aria-label="Pronunciation speed"><span>Audio speed</span><button type="button" data-u6-speed="0.75" aria-pressed="true">0.75×</button><button type="button" data-u6-speed="1" aria-pressed="false">1×</button><button type="button" data-u6-stop>Stop audio</button><audio id="u6-player" controls preload="none" aria-label="Lesson audio"></audio><span id="u6-audio-status" role="status" aria-live="polite"></span></div><p class="u6-hint">Hover over vocabulary for Spanish · click to listen · tap on a phone. Open a topic when you are ready.</p>'''
navhtml='<nav class="u4-topic-nav" aria-label="Lesson topics">'+''.join(f'<a href="#{id}">{title}</a>' for id,title in nav)+'</nav>'
search='''<section class="intermediate2-search course-search-panel" data-course-search-panel data-search-target="#unit6-content" data-search-items=".ie2-search-item" aria-label="Search Unit 6"><label class="course-search-label" for="u6-search">Find a topic or expression</label><div class="course-search-row"><input id="u6-search" type="search" data-course-search-input placeholder="Try: told, drought, tomorrow, carry out…" autocomplete="off"/><button type="button" class="course-search-clear" data-course-search-clear hidden>Clear</button></div><p class="course-search-meta"><span data-course-search-count></span><span>Choose a topic to open its explanation.</span></p></section><p class="course-search-empty" data-course-search-empty hidden>No matching topic. Try another word.</p></div>'''
foot='''</section></main><footer class="site-footer"><p>JaraLingua · Intermediate English Course 2</p></footer><script src="../../assets/js/google-auth-config.js"></script><script src="https://accounts.google.com/gsi/client" async defer></script><script src="../../assets/js/google-auth.js?v=20260919-local-login"></script><script src="../../assets/js/course-search.js?v=20260918-unit4-projector"></script><script src="../../assets/js/english-intermediate2-unit6-explanation.js?v=20261007-1"></script><script src="/assets/js/course-switcher.js"></script></body></html>'''
(ROOT/'ingles/intermediate-2'/PAGE).write_text(head+opening+navhtml+search+'<section class="ie2-unit-theory-shell" id="unit6-content" aria-label="Unit 6 explanation">'+''.join(topics)+foot)
print('Built',len(topics),'sections;',len(audio),'audio models available.')
