const {chromium}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),box={window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'assets/js/conversation-coach-data/english-basic-2-unit-6-restaurant.js'),'utf8'),box);
const c=box.window.JaraLinguaConversationCoachConfig,base=process.env.UNIT6_BASE_URL||'http://127.0.0.1:8025';
assert.equal(c.questions.length,8);assert.ok(c.questions.every(q=>(q.text.match(/\?/g)||[]).length===1));assert.equal(c.language,'en');assert.equal(c.ui.floatingDock,false);
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});
 try{const page=await browser.newPage({viewport:{width:1440,height:900},permissions:['microphone']});let transcript='',mode='success';const errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url());});
 await page.route('**/api/english-basic/pronunciation-assessment',r=>r.fulfill({status:mode==='error'?503:200,contentType:'application/json',body:JSON.stringify(mode==='error'?{error:'Synthetic service outage'}:{text:transcript,language_code:mode==='foreign'?'fr':'en',words:transcript.split(/\s+/).map(word=>({word,probability:.94})),audio:{rms:.09}})}));
 await page.addInitScript(()=>{HTMLMediaElement.prototype.play=function(){setTimeout(()=>this.dispatchEvent(new Event('ended')),30);return Promise.resolve();};});
 await page.goto(base+'/ingles/basico-2/conversation-coach-unit-6-restaurant.html',{waitUntil:'networkidle'});
 for(const width of [360,390,820,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('details[open]').count(),0);const hero=await page.locator('.coach-hero').evaluate(e=>getComputedStyle(e).position);assert.ok(!['fixed','sticky'].includes(hero));await page.locator('.jl-page-qr-open').click();const rect=await page.locator('#jlPageQrDialog').boundingBox();assert.ok(Math.abs(rect.x+rect.width/2-width/2)<3);await page.locator('.jl-page-qr-close').click();await page.screenshot({path:path.join(root,`tmp/unit6-practice-qa/coach-${width}.png`)});}
 await page.setViewportSize({width:1440,height:900});await page.locator('#preflightButton').click();await page.waitForFunction(()=>!document.querySelector('#preflightPlayback').hidden);await page.locator('#startConversationButton').click();
 await page.locator('#interviewPanel [data-coach-speed="0.75"]').click();assert.equal(await page.locator('#questionAudio').evaluate(a=>a.playbackRate),.75);
 const answers=['Hi Ethan. My name is Ana.','A table for two, please.','A glass of water, please.','What does the soup contain?','I would like chicken with rice, please.','No, thank you. I do not want any bread.','The food is tasty and fresh.','Could we have the check, please?'];
 async function record(text){transcript=text;await page.waitForFunction(()=>!document.querySelector('#micButton').disabled);await page.locator('#micButton').click();await page.waitForTimeout(1300);await page.locator('#stopButton').click();}
 for(let i=0;i<answers.length;i++){await page.waitForFunction(n=>document.querySelector('#turnCounter').textContent.startsWith('Turn '+n+' of'),i+1);assert.equal(await page.locator('#answerSupport').getAttribute('open'),null);assert.ok(await page.locator('#floatingMicDock').isHidden());await record(answers[i]);await page.waitForFunction(()=>!document.querySelector('#nextTurnButton').disabled);assert.equal(await page.locator('#liveTranscript').innerText(),answers[i]);if(i===3)assert.match(await page.locator('#coachReactionText').innerText(),/potatoes, carrots/);if(i===5)assert.match(await page.locator('#coachReactionText').innerText(),/No bread/);if(i===7)assert.match(await page.locator('#coachReactionText').innerText(),/Here is your check/);await page.locator('#nextTurnButton').click();}
 assert.ok(await page.locator('#summaryPanel').isVisible());assert.ok(Number(await page.locator('#summaryScore').innerText())>0);await page.locator('#restartConversationButton').click();mode='foreign';await record(answers[0]);await page.waitForFunction(()=>!document.querySelector('#transcriptionRecovery').hidden,null,{timeout:20000});assert.match(await page.locator('#liveTranscript').innerText(),/did not return English/);mode='success';await page.locator('#retryTranscriptionButton').click();await page.waitForFunction(()=>!document.querySelector('#nextTurnButton').disabled);
 await page.locator('#recordAgainButton').click();mode='error';await record(answers[0]);await page.waitForFunction(()=>!document.querySelector('#transcriptionRecovery').hidden,null,{timeout:20000});await page.locator('#continueUnscoredButton').click();await page.waitForFunction(()=>!document.querySelector('#nextTurnButton').disabled);assert.match(await page.locator('#liveTranscript').innerText(),/not transcribed or scored/);
 assert.ok(posts.filter(p=>!p.endsWith('/csp-report')).every(p=>p.endsWith('/api/english-basic/pronunciation-assessment')));assert.deepEqual(errors,[]);console.log('PASS eight turns, synthetic microphone, English transcripts, contextual responses, score, retry, foreign-language rejection, outage recovery; no teacher submission.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
