const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const host='https://www.jaralingua.com',pathname='/ingles/intermediate-2/speaking-unit-5-our-picture-stories.html';
const fixture=JSON.parse(fs.readFileSync('tmp/unit5-group-stories/session.json','utf8'));
const local=p=>p===pathname||p.includes('english-intermediate2-group-stories.')||p.includes('/unit-5/group-stories/')||p.endsWith('ingles-intermediate-2-speaking-unit-5-our-picture-stories.svg');
const errors=[];
(async()=>{const engine=process.env.WEBKIT?'webkit':'chrome',browser=await(process.env.WEBKIT?webkit:chromium).launch(process.env.WEBKIT?{headless:true}:{channel:'chrome',headless:true});try{
 const probe=await browser.newPage(),ref=await probe.request.get(host+'/ingles/intermediate-2/grammar-unit-5-read-the-clues.html'),csp=ref.headers()['content-security-policy'];assert(csp);await probe.close();
 async function page(width=1440,height=900){const p=await browser.newPage({viewport:{width,height}});p.on('pageerror',e=>errors.push(e.message));await p.route(host+'/**',async route=>{const u=new URL(route.request().url());if(u.pathname.startsWith('/api/intermediate2/group-stories/')){if(process.env.LIVE)return route.continue();const r=await route.fetch({url:fixture.base+u.pathname+u.search});return route.fulfill({response:r});}if(u.pathname.startsWith('/api/'))return route.fulfill({status:401,json:{error:'QA isolation'}});if(!process.env.LIVE&&local(u.pathname))return route.fulfill({path:path.resolve('.'+u.pathname),headers:u.pathname.endsWith('.html')?{'Content-Security-Policy':csp}:{}});return route.continue();});await p.addInitScript(()=>{const A=window.Audio;window.__audios=[];window.Audio=function(...args){const a=new A(...args);window.__audios.push(a);return a};window.Audio.prototype=A.prototype;});await p.goto(host+pathname,{waitUntil:'networkidle'});return p;}
 async function auth(p,who){assert(!process.env.LIVE);await p.evaluate(({who,token})=>{window.__qaUser=who?{provider:'local',credential:token,name:who}:null;window.JaraLinguaAuth.getUser=()=>window.__qaUser;window.dispatchEvent(new Event('jaralingua:auth-changed'));},{who,token:fixture.tokens[who]});if(who)await p.locator('#gsAccount').waitFor({state:'visible'});}
 async function select(p,id){await p.locator('#gsSession').selectOption(id);await p.locator('#gsRoom').waitFor({state:'visible'});}
 async function hit(p,id){assert(await p.locator(id).evaluate(e=>{const r=e.getBoundingClientRect();return r.width>35&&r.height>=44&&r.top>=0&&r.bottom<=innerHeight+1&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}),id+' not visible / clickable');}
 if(!process.env.LIVE&&!process.env.LAYOUT_ONLY){
  const teacher=await page(),ana=await page(390),bea=await page(),leo=await page(768);
  await auth(teacher,'teacher');await teacher.locator('#gsName').fill('Browser QA '+engine+' '+Date.now());await teacher.locator('#gsCreate button').click();await teacher.locator('#gsRoom').waitFor({state:'visible'});const room=await teacher.locator('#gsSession').inputValue();assert(room);
  await teacher.locator('[data-assign="1"]').click();await teacher.locator('#gsRoster input[value="9903"]').check();await teacher.locator('#gsRoster input[value="9904"]').check();await teacher.locator('#gsApply').click();await teacher.locator('#gsAssign').waitFor({state:'hidden'});
  await teacher.locator('[data-assign="2"]').click();assert(await teacher.locator('#gsRoster input[value="9903"]').isDisabled());await teacher.locator('#gsRoster input[value="9905"]').check();await teacher.screenshot({path:'tmp/unit5-group-stories/'+engine+'-assign.png'});await teacher.locator('#gsApply').click();await teacher.locator('#gsAssign').waitFor({state:'hidden'});
  await auth(ana,'ana');assert.equal(await ana.locator('#gsSession option[value="'+room+'"]').count(),0);
  await teacher.locator('#gsFinalize').click();await teacher.locator('#gsStart').waitFor({state:'visible'});assert(await teacher.locator('#gsStart').isDisabled());
  for(const [p,who] of [[ana,'ana'],[bea,'bea'],[leo,'leo']]){await auth(p,who);await select(p,room);assert.equal(await p.locator('.gs-card.is-mine').count(),1);}
  assert(!(await ana.locator('#gsGallery').textContent()).includes('Leo Test'));await ana.locator('[data-open="1"]').click();await ana.locator('#gsEditor').waitFor({state:'visible'});await hit(ana,'#gsSend');assert(await ana.locator('#gsSend').isEnabled());
  await ana.locator('#gsSend').click();assert.match(await ana.locator('#gsSaveStatus').textContent(),/Write your/);
  const first='Ana Test: She looks relieved. I think she missed her friend.\n\nBea Test: The trip was tiring, but they cheered up.';
  await ana.locator('#gsText').fill(first);await ana.locator('#gsPhrasal').fill('cheer up');
  let drop=true;const retryIds=[];await ana.route('**/api/intermediate2/group-stories/save',async r=>{retryIds.push(r.request().postDataJSON().requestId);if(!drop)return r.fallback();drop=false;await r.fetch({url:fixture.base+'/api/intermediate2/group-stories/save'});await r.abort('failed');});
  await ana.locator('#gsDraft').click();await ana.waitForFunction(()=>!document.querySelector('#gsDraft').disabled&&!document.querySelector('#gsSaveStatus').textContent.startsWith('Draft saved'));await ana.locator('#gsDraft').click();await ana.waitForFunction(()=>document.querySelector('#gsSaveStatus').textContent.startsWith('Draft saved'));assert.equal(retryIds[0],retryIds[1]);
  await bea.locator('[data-open="1"]').click();await bea.locator('#gsEditor').waitFor({state:'visible'});assert.equal(await bea.locator('#gsText').inputValue(),first);
  await ana.locator('#gsText').fill(first+'\nAna Test: Perhaps they will have dinner.');await ana.locator('#gsDraft').click();await ana.waitForFunction(()=>document.querySelector('#gsSaveStatus').textContent.startsWith('Draft saved'));
  const mine=first+'\nBea Test: They seem excited.';await bea.locator('#gsText').fill(mine);await bea.locator('#gsDraft').click();await bea.locator('#gsConflict').waitFor({state:'visible'});assert.equal(await bea.locator('#gsText').inputValue(),mine);assert.match(await bea.locator('#gsLatestText').textContent(),/Perhaps/);await bea.locator('#gsKeepMine').click();await bea.locator('#gsEveryone').check();await bea.locator('#gsSend').click();await bea.waitForFunction(()=>document.querySelector('#gsSaveStatus').textContent.startsWith('Submitted to teacher'));
  await ana.locator('#gsDraft').click();await ana.locator('#gsConflict').waitFor({state:'visible'});await ana.locator('#gsUseLatest').click();assert.equal(await ana.locator('#gsText').inputValue(),mine);await ana.screenshot({path:'tmp/unit5-group-stories/'+engine+'-student-390.png'});await hit(ana,'#gsSend');assert(await ana.locator('#gsSend').evaluate(e=>e.getBoundingClientRect().width>200));
  await ana.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,value:360});visualViewport.dispatchEvent(new Event('resize'));});await hit(ana,'#gsSend');assert(await ana.locator('#gsSend').evaluate(e=>e.getBoundingClientRect().bottom<=360));await ana.evaluate(()=>{delete visualViewport.height;visualViewport.dispatchEvent(new Event('resize'));});
  await teacher.locator('#gsRefresh').click();await teacher.waitForFunction(()=>document.querySelector('#gsProgress').textContent.startsWith('1 / 2'));assert(await teacher.locator('#gsStart').isDisabled());
  await leo.locator('[data-open="2"]').click();await leo.locator('#gsEditor').waitFor({state:'visible'});await leo.locator('#gsText').fill('Leo Test: They look surprised. Perhaps the rain started suddenly. The picnic was exciting. They calmed down.');await leo.locator('#gsPhrasal').fill('calm down');await leo.locator('#gsEveryone').check();await leo.locator('#gsSend').click();await leo.waitForFunction(()=>document.querySelector('#gsSaveStatus').textContent.startsWith('Submitted to teacher'));
  await teacher.locator('#gsRefresh').click();await teacher.waitForFunction(()=>!document.querySelector('#gsStart').disabled);await teacher.locator('#gsStart').click();await teacher.waitForFunction(()=>document.querySelector('#gsStart').textContent==='Presentations started');
  await ana.locator('#gsText').fill(mine+' Changed too late.');await ana.locator('#gsDraft').click();await ana.waitForFunction(()=>document.querySelector('#gsSend').disabled&&document.querySelector('#gsSaveStatus').textContent.includes('Presentations have started'));
  await teacher.locator('[data-open="1"]').click();await teacher.locator('#gsProjector').waitFor({state:'visible'});assert.equal(await teacher.locator('#gsProjectedText').textContent(),mine);assert.match(await teacher.locator('#gsProjectNames').textContent(),/Ana Test/);await teacher.locator('#gsProjectImage').evaluate(e=>e.decode());await teacher.screenshot({path:'tmp/unit5-group-stories/'+engine+'-presentation.png'});
  await teacher.locator('#gsTimerToggle').click();await teacher.waitForFunction(()=>document.querySelector('#gsTime').textContent!=='02:00');await teacher.locator('#gsTimerToggle').click();await teacher.locator('#gsTimerReset').click();assert.equal(await teacher.locator('#gsTime').textContent(),'02:00');await teacher.locator('#gsToggleStory').click();assert(await teacher.locator('#gsProjectStory').isHidden());await teacher.locator('#gsToggleStory').click();
  await auth(teacher,null);assert(await teacher.locator('#gsProjector').isHidden());assert.equal(await teacher.locator('#gsProjectedText').textContent(),'');assert.equal(await teacher.locator('#gsRoster').textContent(),'');await auth(ana,null);assert.equal(await ana.locator('#gsText').inputValue(),'');
  for(const p of [teacher,ana,bea,leo])await p.close();console.log(engine,'PASS: roster selection, shared editor, concurrency recovery, submissions, presentation gate, timer and sign-out privacy');
 }
 for(const width of process.env.WIDTH?[+process.env.WIDTH]:[320,390,430,768,1024,1440,1920]){
  const p=await page(width,process.env.LANDSCAPE?390:900);assert.equal(await p.locator('[data-picture]').count(),10);assert.equal(await p.locator('.gs-gallery').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),width>=1400?5:width>1000?3:width>540?2:1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert(await p.locator('.jl-page-qr-card img').evaluate(e=>e.complete&&e.naturalWidth>0));await p.locator('.jl-page-qr-open').click();await p.locator('.jl-page-qr-dialog').waitFor({state:'visible'});if(width===1440)await p.locator('.jl-page-qr-dialog img').screenshot({path:'tmp/unit5-group-stories/qr-expanded.png'});await p.keyboard.press('Escape');
  await p.locator('[data-auth-toggle]').click();await p.locator('[data-local-login-form]').waitFor({state:'visible'});assert(await p.locator('[data-auth-panel]').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&r.left>=0&&r.right<=innerWidth+1&&e.contains(document.elementFromPoint(r.left+20,r.top+20))}));await p.keyboard.press('Escape');
  await p.locator('.gs-help summary').click();const buttons=await p.locator('[data-audio]').all();assert.equal(buttons.length,18);for(const b of width===1440?buttons:buttons.slice(0,1)){const src=await b.getAttribute('data-audio');await b.click();await p.waitForFunction(src=>{const a=__audios[0];return a.src.endsWith(src)&&a.currentTime>0&&!a.error&&(!a.paused||a.ended)},src,{timeout:15000});}assert.equal(await p.evaluate(()=>__audios[0].playbackRate),.75);await p.locator('[data-speed="1"]').click();assert.equal(await p.evaluate(()=>__audios[0].playbackRate),1);await p.locator('.gs-help summary').click();
  await p.locator('[data-open="10"]').click();await p.locator('#gsProjectImage').evaluate(e=>e.decode());assert(await p.locator('#gsProjectStory').isHidden());assert.equal(await p.locator('#gsProjectImage').evaluate(e=>getComputedStyle(e).objectFit),'contain');assert(await p.locator('#gsProjectImage').evaluate(e=>{const r=e.getBoundingClientRect();return r.width>100&&r.height>90&&r.top>=0&&r.bottom<=innerHeight+1}));await p.locator('[data-close="gsProjector"]').click();assert.equal(await p.evaluate(()=>__audios[0].paused),true);
  await p.locator('#gsGallery').evaluate(async e=>{await Promise.all([...e.querySelectorAll('img')].map(i=>{i.loading='eager';return i.decode()}));e.scrollIntoView({block:'start',behavior:'instant'});});if([390,1440,1920].includes(width)){await p.screenshot({path:'tmp/unit5-group-stories/'+engine+'-gallery-'+width+'.jpg',type:'jpeg'});await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:'tmp/unit5-group-stories/'+engine+'-hero-'+width+'.jpg',type:'jpeg'});}await p.close();console.log(engine,width,'PASS: responsive gallery, all images, QR, login, pronunciation and projector');
 }
 assert.deepEqual(errors,[]);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
