const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const origin=process.env.NEWS_ORIGIN||'http://127.0.0.1:8139',url=origin+'/ingles/intermediate-2/vocabulary-unit-6-greenford-news.html';
const data=JSON.parse(fs.readFileSync('assets/data/english-intermediate2-unit6-newsroom.json'));const audioModels=JSON.parse(fs.readFileSync('ingles/intermediate-2/audio/unit-6-newsroom/models.json'));
(async()=>{const b=await chromium.launch({headless:true});try{for(const width of [320,390,768,1024,1440,1920]){const p=await b.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url,{waitUntil:'domcontentloaded'});await p.locator('#news-tv').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector('.jl-page-qr-card img')?.naturalWidth>0);await p.locator('.jl-page-qr-open').click();await p.locator('.jl-page-qr-dialog').waitFor({state:'visible'});await p.keyboard.press('Escape');
assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);
const word=p.locator('#news-caption [data-word="headline"]');await word.hover();assert.equal(await p.locator('#news-tooltip').innerText(),'titular');assert(await p.locator('#news-audio').evaluate(a=>a.paused));await word.click();await p.waitForFunction(()=>document.querySelector('#news-word-audio').currentTime>0);await p.locator('[data-news-action=stop]').click();
await p.locator('#news-word-help summary').click();assert.match(await p.locator('#news-word-card').innerText(),/title/);
for(let i=0;i<12;i++){await p.locator('#news-jump').selectOption(String(i));await p.locator('#news-image').evaluate(i=>i.decode());assert.equal(await p.locator('#news-image').getAttribute('alt'),data.scenes[i].alt);assert(await p.locator('#news-image').evaluate(i=>getComputedStyle(i).objectFit==='contain'&&i.getBoundingClientRect().height<=481));assert.equal(await p.locator('#news-word-help').evaluate(d=>d.open),false);assert(await p.locator('#news-caption [data-word]').count()>0);}
await p.locator('[data-news-action=next]').click();assert(await p.locator('#news-quiz').isVisible());await p.locator('#news-jump').selectOption('9');await p.locator('[data-news-action=grade]').click();assert.match(await p.locator('#news-status').innerText(),/answer all ten/);assert.equal(await p.locator('#news-jump').inputValue(),'0');
for(let i=0;i<10;i++){await p.locator('#news-jump').selectOption(String(i));assert.equal(await p.locator('#news-choices label').count(),3);assert.match(await p.locator('#news-choices label').first().innerText(),/^A\./);await p.locator('#news-choices input').nth(i===0?1:data.questions[i].answer).check();}
await p.locator('[data-news-action=grade]').click();assert.match(await p.locator('#news-score').innerText(),/9 \/ 10/);await p.locator('#news-jump').selectOption('0');assert.match(await p.locator('#news-feedback').innerText(),/Review this answer.*Answer A/);assert.equal(await p.locator('#news-choices input:disabled').count(),3);
await p.locator('[data-news-action=project]').click();await p.locator('#news-projector').waitFor({state:'visible'});assert.equal(await p.locator('#news-projector #news-tv').count(),1);if(width===1440){await p.locator('[data-news-action=fullscreen]').click();await p.waitForFunction(()=>document.fullscreenElement===document.documentElement);await p.locator('[data-news-action=fullscreen]').click();await p.waitForFunction(()=>!document.fullscreenElement);}assert(await p.locator('#news-projector').evaluate(d=>d.scrollWidth<=innerWidth+1));await p.locator('[data-news-action=play]').click();await p.waitForFunction(()=>document.querySelector('#news-audio').currentTime>0);await p.locator('[data-news-action=stop]').click();await p.locator('[data-news-action=story]').click();await p.locator('#news-jump').selectOption('0');await p.locator('#news-caption [data-word=headline]').hover();assert(await p.locator('#news-projector #news-tooltip').isVisible());await p.keyboard.press('Escape');assert.equal(await p.locator('#news-projector').evaluate(d=>d.open),true);await p.keyboard.press('Escape');await p.locator('#news-projector').waitFor({state:'hidden'});await p.locator('#news-home #news-tv').waitFor({state:'visible'});assert.equal(await p.locator('#news-home #news-tv').count(),1);
await p.locator('[data-news-action=vocabulary]').click();assert.equal(await p.locator('.news-vocab-card').count(),12);await p.locator('[data-news-scene="7"]').click();assert.match(await p.locator('#news-progress').innerText(),/Scene 8/);await p.locator('[data-news-action=captions]').click();assert(await p.locator('#news-caption').isHidden());await p.locator('[data-news-action=captions]').click();
await p.locator('[data-news-action=continuous]').click();await p.waitForFunction(()=>document.querySelector('#news-audio').currentTime>0);await p.locator('#news-audio').evaluate(a=>a.currentTime=a.duration-.05);await p.waitForFunction(()=>document.querySelector('#news-progress').textContent==='Scene 2 / 12');await p.waitForFunction(()=>document.querySelector('#news-audio').currentTime>0);await p.locator('[data-news-action=stop]').click();
await p.locator('[data-news-action=quiz]').click();await p.locator('[data-news-action=retry-quiz]').click();assert.equal(await p.locator('#news-choices input:checked').count(),0);assert.equal(await p.locator('#news-score').innerText(),'');
if(width===390||width===1440){await p.locator('[data-news-action=story]').click();await p.locator('#news-tv').scrollIntoViewIfNeeded();await p.screenshot({path:'/private/tmp/newsroom-'+width+'.png'});}
assert.deepEqual(errors,[]);console.log('PASS newsroom at',width);await p.close();}
const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await p.goto(url);await p.locator('#news-caption [data-word=headline]').tap();await p.locator('#news-tooltip').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector('#news-word-audio').currentTime>0);console.log('PASS touch translation and pronunciation');await p.close();
const check=await b.newPage();await check.goto(origin+'/ingles/intermediate-2/practice-lab.html#unit-6-folder');const link=check.locator('#unit6ActivityGrid a');await link.waitFor();assert.match(await link.getAttribute('href'),/vocabulary-unit-6-greenford-news/);await check.locator('#practiceLabSearch').fill('Greenford');assert(await link.isVisible());console.log('PASS Practice Lab discovery');
for(const path of new Set([...data.scenes.map(x=>x.image),...audioModels.items.map(x=>'/ingles/intermediate-2/audio/unit-6-newsroom/'+x.file),...data.glossary.map(x=>x.audio)])){const r=await check.request.get(origin+path);assert.equal(r.status(),200,path);}
console.log('PASS all images, 41 new audios and reused vocabulary audio URLs');await check.close();
const fail=await b.newPage();await fail.route('**/unit-6-newsroom/headline.mp3',r=>r.abort());await fail.goto(url);await fail.locator('[data-news-action=play]').click();await fail.waitForFunction(()=>document.querySelector('#news-status').textContent.includes('Audio could not'));console.log('PASS audio failure feedback');await fail.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
