const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const base=process.env.OPINION_ORIGIN||'http://127.0.0.1:8139',url=base+'/ingles/intermediate-2/conversation-coach-unit-6-my-opinion-matters.html';
const nodes={},stub=id=>nodes[id]??={addEventListener(){},dataset:{}};const box={window:{addEventListener(){}},document:{getElementById:stub,addEventListener(){}}};
vm.runInNewContext(fs.readFileSync('assets/js/conversation-coach-data/english-intermediate-2-unit-6-opinion.js','utf8'),box);vm.runInNewContext(fs.readFileSync('assets/js/intermediate2-opinion-coach.js','utf8'),box);const c=box.window.JaraLinguaConversationCoachConfig;
assert.equal(c.scenes.length,5);assert.equal(c.questions.length,16);assert.equal(c.persistHistory,false);const q=id=>c.questions.find(q=>q.id===id),a=transcript=>({transcript,analysis:{checks:[],wordCount:10}});
assert.equal(c.responseResolver(a('Ana'),q('hello'))[0].file,'reply-hello.mp3');
for(const t of ["She is not worried.","She doesn't look worried.","I don't think she looks worried."])assert.equal(c.responseResolver(a(t),q('s2-interpret'))[0].file,'reply-not-worried.mp3');
assert.equal(c.responseResolver(a('She looks worried.'),q('s2-interpret'))[0].file,'reply-worried.mp3');
assert.equal(c.responseResolver(a('She looks like worried.'),q('s2-interpret'))[0].file,'reply-correction-looks.mp3');
assert.equal(c.responseResolver(a('Quantum mathematics is interesting.'),q('s2-opinion'))[0].file,'reply-clarify.mp3');
assert.equal(c.responseResolver(a('I do not know.'),q('s4-opinion'))[0].file,'reply-uncertain.mp3');
assert.equal(c.followUpResolver(a('I would check the source because it could be false.'),q('s2-opinion'),c.followUpSets['2']).kind,'prediction');assert.equal(c.followUpResolver(a('I would share the warning.'),q('s2-opinion'),c.followUpSets['2']).kind,'reason');
assert.equal(c.questionResolver(q('s2-interpret'),{questionId:'s2-observe',transcript:'The student seems worried.'}).audio,'s2-evidence.mp3');
const manifest=JSON.parse(fs.readFileSync('ingles/intermediate-2/audio/unit-6-opinion-coach/models.json'));
for(const item of manifest.items){const data=fs.readFileSync('ingles/intermediate-2/audio/unit-6-opinion-coach/'+item.file);assert(data.length>1000);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),item.sha256);}
(async()=>{const b=await chromium.launch({args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});try{
 const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://accounts.google.com/**',r=>r.fulfill({body:''}));let transcript='',mode='ok';
 await p.route('**/api/english-intermediate/pronunciation-assessment',r=>r.fulfill({status:mode==='fail'?503:200,contentType:'application/json',body:JSON.stringify({text:mode==='silence'?'':transcript,language_code:'en',words:[],audio:{rms:mode==='silence'?0:.08}})}));
 await p.addInitScript(()=>{HTMLMediaElement.prototype.play=function(){setTimeout(()=>this.dispatchEvent(new Event('ended')),50);return Promise.resolve();};});await p.goto(url);
 for(const width of [320,390,768,1024,1440,1920]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.jl-page-qr-open').click();await p.locator('.jl-page-qr-dialog').waitFor({state:'visible'});await p.keyboard.press('Escape');}
 await p.locator('#startConversationButton').click();assert(await p.locator('#floatingMicDock').isHidden());
 async function record(t){transcript=t;await p.waitForFunction(()=>!document.querySelector('#micButton').disabled);await p.locator('#micButton').click();await p.waitForFunction(()=>!document.querySelector('#stopButton').disabled);assert.equal(await p.locator('[data-example]:enabled,[data-word]:enabled').count(),0);await p.waitForTimeout(900);await p.locator('#stopButton').click();}
 async function ready(){await p.waitForFunction(()=>document.querySelector('#recordStatus').textContent==='Answer analyzed'&&!document.querySelector('#questionPlayButton').disabled);}
 await record('Ana');await ready();assert.match(await p.locator('#coachReactionText').innerText(),/Nice to meet you!/);await p.locator('#nextTurnButton').click();
 for(let scene=1;scene<=5;scene++){
  const s=c.scenes[scene-1];assert.equal(await p.locator('#opinionImage').getAttribute('src'),s.image);await p.waitForFunction(()=>{const e=document.querySelector('#opinionImage');return e.complete&&e.naturalWidth>0;});
  for(const width of [390,768,1024,1440,1920]){await p.setViewportSize({width,height:900});const boxes=await p.evaluate(()=>['.david-prompt-column','.opinion-conversation-column','.coach-recorder'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));
  if(width>=980){assert(Math.abs(boxes[0].y-boxes[1].y)<2);assert(Math.abs(boxes[1].y-boxes[2].y)<2);assert(boxes[0].right<boxes[1].x);assert(boxes[1].right<boxes[2].x);}else if(width>=768){assert(Math.abs(boxes[0].y-boxes[1].y)<2);assert(boxes[0].right<boxes[1].x);}else{assert(boxes[0].bottom<=boxes[1].y);assert(boxes[1].bottom<=boxes[2].y);}
  assert(await p.locator('.david-hero-image').isVisible());assert.equal(await p.locator('.david-hero-image img').evaluate(e=>getComputedStyle(e).objectFit),'contain');const portrait=await p.locator('.coach-avatar').boundingBox();assert(portrait&&portrait.width>=128&&portrait.height>=128);assert.equal(await p.locator('.coach-avatar img').evaluate(e=>getComputedStyle(e).objectFit),'contain');await p.locator('#opinionImageOpen').click();assert(await p.locator('#opinionDialog').evaluate(e=>e.open));await p.keyboard.press('Escape');await p.locator('#opinionQuestionExpand').click();assert.equal(await p.locator('.opinion-projected-question').innerText(),q(`s${scene}-observe`).text);await p.locator('#opinionDialogClose').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
  await p.locator('#answerSupport summary').first().click();await p.locator('[data-word]').first().hover();assert(await p.locator('#opinionTooltip').isVisible());assert.equal(await p.locator('#opinionExamples').getAttribute('open'),null);await p.locator('#opinionExamples summary').click();assert.equal(await p.locator('[data-example]').count(),2);await p.locator('[data-example]').first().click();await p.waitForFunction(()=>!document.querySelector('#micButton').disabled);
  await record(s.examples[0][0]+(scene===2?' She seems worried.':''));await ready();await p.locator('#nextTurnButton').click();if(scene===2)assert.equal(await p.locator('#questionText').innerText(),s.detail);
  await record(scene===2?"She doesn't look worried. She looks focused on the warning.":s.examples[1][0]);await ready();if(scene===2)assert.match(await p.locator('#coachReactionText').innerText(),/do not see worry/);await p.locator('#nextTurnButton').click();
  if(scene===1){await record('Could you repeat the question?');await p.waitForFunction(()=>document.querySelector('#recordStatus').textContent==='Your question answered');assert.match(await p.locator('#coachReactionText').innerText(),/Could this photo/);}
  const opinion=s.examples[2][0]+' because the people in the picture need help.';await record(opinion);await p.waitForFunction(()=>document.querySelector('#turnCounter').textContent.includes('Follow-up'));assert.equal(await p.locator('#questionText').innerText(),s.predict);await record('The people might ask for help because the community needs supplies.');await ready();await p.locator('#nextTurnButton').click();
 }
 await p.locator('#summaryPanel').waitFor({state:'visible'});assert.equal(await p.locator('#opinionReport article').count(),5);assert((await p.locator('#reactionAudio').getAttribute('src')).endsWith('reply-closing.mp3'));await p.locator('#closingPlayButton').click();assert(!/\/50|\/10|\d+%/.test(await p.locator('#summaryPanel').innerText()));assert.equal(await p.evaluate(key=>localStorage.getItem(key),c.storageKey),null);await p.screenshot({path:'/private/tmp/opinion-coach-summary.png',fullPage:true});
 await p.locator('#restartConversationButton').click();mode='fail';await record('Ana');await p.locator('#transcriptionRecovery').waitFor({state:'visible'});mode='ok';transcript='Ana';await p.locator('#retryTranscriptionButton').click();await ready();await p.locator('#nextTurnButton').click();
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/private/tmp/opinion-coach-mobile.png',fullPage:true});await p.setViewportSize({width:1440,height:900});await p.screenshot({path:'/private/tmp/opinion-coach-desktop.png',fullPage:true});
 mode='silence';await record('');await p.locator('#transcriptionRecovery').waitFor({state:'visible'});await p.locator('#nextTurnButton').click();await p.waitForFunction(()=>!document.querySelector('#micButton').disabled);assert.deepEqual(errors,[]);
 const assets=[...c.scenes.map(s=>s.image),...manifest.items.map(i=>'/ingles/intermediate-2/audio/unit-6-opinion-coach/'+i.file),...Object.values(c.wordHelp).map(v=>v.audio.startsWith('/')?v.audio:'/ingles/intermediate-2/'+v.audio)];
 for(const asset of new Set(assets)){const r=await p.request.get(base+asset);assert.equal(r.status(),200,asset);}
 console.log('PASS five scenes, 16 main/5 adaptive turns, name/replies, interpretation without repetition, negations, language help, enlarged image/question, QR, six widths, recovery, temporary-only report and all media.');await p.close();
 // Independent real playback check: no play() mocking and public prepared audio only.
 const live=await b.newPage();await live.goto(url);await live.locator('#welcomePlayButton').click();await live.waitForFunction(()=>document.querySelector('#welcomeAudio').currentTime>0);assert(await live.locator('#welcomeAudio').evaluate(a=>!a.paused));await live.locator('#startConversationButton').click();await live.waitForFunction(()=>document.querySelector('#questionAudio').currentTime>0);assert((await live.locator('#questionAudio').getAttribute('src')).endsWith('hello.mp3'));await live.close();console.log('PASS real welcome and greeting playback');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
