const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const host='https://www.jaralingua.com',pathname='/ingles/intermediate-2/speaking-unit-5-behind-the-picture.html';
const config=JSON.parse(fs.readFileSync('assets/data/english-intermediate2-unit5-picture.json','utf8'));
const published=JSON.parse(fs.readFileSync('assets/data/english-intermediate-2-content.json','utf8')).items.filter(item=>item.status==='published');
const localPaths=p=>p===pathname||p.includes('english-intermediate2-unit5-picture.')||p.includes('/unit-5/behind-the-picture/')||p.includes('/audio/unit-5-picture/')||p.includes('ingles-intermediate-2-speaking-unit-5-behind-the-picture.svg')||p==='/ingles/intermediate-2/practice-lab.html'||p==='/assets/data/english-intermediate-2-content.json';
(async()=>{const engine=process.env.WEBKIT?'webkit':'chrome';const browser=await(process.env.WEBKIT?webkit:chromium).launch(process.env.WEBKIT?{headless:true}:{channel:'chrome',headless:true});try{
for(const width of process.env.WIDTH?[Number(process.env.WIDTH)]:process.env.QUICK?[390,1440]:[320,390,430,768,1024,1440,1920]){
 const page=await browser.newPage({viewport:{width,height:process.env.LANDSCAPE?390:900},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const ref=await page.request.get(host+'/ingles/intermediate-2/grammar-unit-5-read-the-clues.html');const csp=ref.headers()['content-security-policy'];assert(csp);
 if(!process.env.LIVE)await page.route(host+'/**',async r=>{const p=new URL(r.request().url()).pathname;if(!localPaths(p))return r.continue();const file=path.resolve('.'+p);if(process.env.PENDING_IMAGE&&p.endsWith('/01-door.webp')&&!fs.existsSync(file))return r.fulfill({path:path.resolve('assets/img/english-intermediate-2/unit-5/explanation/waiting.webp')});assert(fs.existsSync(file),file);return r.fulfill({path:file,headers:p.endsWith('.html')?{'Content-Security-Policy':csp}:{}});});
 await page.addInitScript(()=>{const A=window.Audio;window.__audios=[];window.Audio=function(...args){const a=new A(...args);window.__audios.push(a);return a};window.Audio.prototype=A.prototype;const now=Date.now.bind(Date);window.__timeOffset=0;Date.now=()=>now()+window.__timeOffset;});
 await page.goto(host+pathname,{waitUntil:'networkidle'});
 assert.equal(await page.locator('[data-card]').count(),10);assert.equal(await page.locator('.bp-card .bp-questions li').count(),40);
 const expected=width>=1600?4:width>1100?3:width>620?2:1;assert.equal(await page.locator('.bp-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),expected);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflow '+width);
 assert(await page.locator('.jl-page-qr-card img').evaluate(e=>{const r=e.getBoundingClientRect(),c=e.closest('.jl-page-qr-card').getBoundingClientRect();return e.complete&&e.naturalWidth>0&&Math.abs(r.width-r.height)<1&&r.bottom<c.bottom}));
 await page.locator('.jl-page-qr-open').click();await page.locator('.jl-page-qr-dialog').waitFor({state:'visible'});if(width===1440)await page.locator('.jl-page-qr-dialog img').screenshot({path:'tmp/unit5-picture/qr-expanded.png'});await page.keyboard.press('Escape');
 await page.locator('[data-auth-toggle]').click();await page.locator('[data-local-login-form]').waitFor({state:'visible'});assert(await page.locator('[data-auth-panel]').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&r.left>=0&&r.right<=innerWidth+1&&e.contains(document.elementFromPoint(r.left+20,r.top+20))}),'auth '+width);await page.keyboard.press('Escape');
 const card=page.locator('[data-card="0"]');await card.locator('.bp-questions [data-audio]').first().click();await page.waitForFunction(()=>__audios[0].currentTime>0&&!__audios[0].paused,null,{timeout:10000});assert.equal(await page.locator('#bpProjector').evaluate(e=>e.open),false);assert.equal(await page.evaluate(()=>__audios[0].playbackRate),.75);
 await page.locator('.bp-toolbar [data-speed="1"]').click();assert.equal(await page.evaluate(()=>__audios[0].playbackRate),1);await page.locator('.bp-toolbar [data-speed="0.75"]').click();
 await card.locator('[data-open]').click();await page.locator('#bpProjector').waitFor({state:'visible'});await page.locator('#bpImage').evaluate(e=>e.decode());assert.equal(await page.locator('#bpImage').evaluate(e=>getComputedStyle(e).objectFit),'contain');if(width<=1100&&!process.env.LANDSCAPE)assert(await page.evaluate(()=>document.querySelector('#bpImage').getBoundingClientRect().bottom<=document.querySelector('#bpTitle').getBoundingClientRect().top),'image must not overlap text');assert.match(await page.locator('#bpRound').textContent(),/Partner A starts/);assert(await page.locator('[data-prev]').isDisabled());
 await page.locator('#bpPrompts [data-audio]').first().click();await page.waitForFunction(()=>__audios[0].currentTime>0&&!__audios[0].paused);await page.locator('#bpProjector [data-stop-audio]').click();assert.equal(await page.evaluate(()=>__audios[0].paused),true);
 await page.locator('[data-timer-toggle]').click();await page.evaluate(()=>__timeOffset+=3000);await page.waitForTimeout(250);assert.match(await page.locator('[data-time]').textContent(),/1:5[67]/);await page.locator('[data-timer-toggle]').click();const paused=await page.locator('[data-time]').textContent();await page.evaluate(()=>__timeOffset+=5000);await page.waitForTimeout(250);assert.equal(await page.locator('[data-time]').textContent(),paused);assert.equal(await page.locator('[data-timer-toggle]').textContent(),'Resume');await page.locator('[data-timer-toggle]').click();await page.evaluate(()=>__timeOffset+=120000);await page.waitForTimeout(250);assert.equal(await page.locator('[data-time]').textContent(),'0:00');assert.match(await page.locator('#bpTimerStatus').textContent(),/Time is up/);assert(await page.locator('[data-timer-toggle]').isDisabled());await page.locator('[data-timer-reset]').click();assert.equal(await page.locator('[data-time]').textContent(),'2:00');
 await page.locator('#bpCheck summary').click();for(let i=0;i<4;i++)await page.locator('#bpCheck [data-check="0-'+i+'"]').check();assert.equal(await page.locator('#discussionProgress').textContent(),'1 / 10 conversations checked');
 await page.locator('#bpSupport summary').click();await page.locator('#bpSupport [data-audio]').first().click();await page.waitForFunction(()=>!__audios[0].paused);await page.locator('#bpProjector [data-stop-audio]').click();
 if(width===390||width===1440){await page.locator('#bpSupport summary').click();await page.locator('#bpProjector .bp-project-stage').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'tmp/unit5-picture/'+engine+'-project-'+width+'.jpg',type:'jpeg'});}
 await page.locator('[data-next]').click();assert.match(await page.locator('#bpRound').textContent(),/Partner B starts/);assert.match(await page.locator('#bpTitle').textContent(),/^2\./);assert.equal(await page.locator('[data-time]').textContent(),'2:00');await page.locator('[data-timer-toggle]').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#bpProjector').evaluate(e=>e.open),false);await page.waitForFunction(()=>document.querySelector('[data-timer-toggle]').textContent==='Resume');assert.equal(await page.evaluate(()=>document.activeElement.dataset.open),'0');
 await card.locator('.bp-check summary').click();assert.equal(await card.locator('input:checked').count(),4);
 if(width===1440){
  // Eight unseen cards remain after opening pictures one and two.
  const ids=new Set([1,2]);for(let i=0;i<8;i++){await page.locator((i===0?'.bp-toolbar':'#bpProjector')+' [data-random]').click();const n=Number((await page.locator('#bpTitle').textContent()).split('.')[0]);assert(!ids.has(n),'repeat '+n);ids.add(n);await page.locator('#bpImage').evaluate(e=>e.decode());}
  assert.equal(ids.size,10);assert(await page.locator('#bpProjector [data-random]').isDisabled());assert(await page.locator('#bpProjector [data-new-set]').isVisible());await page.locator('#bpProjector [data-new-set]').click();assert.equal(await page.locator('#bpProjector [data-deck-status]').textContent(),'10 unseen pictures in this set');assert.equal(await page.locator('#discussionProgress').textContent(),'1 / 10 conversations checked');await page.locator('[data-close]').click();
  // Every distinct pronunciation model is playable through a visible text control.
  await page.evaluate(()=>document.querySelectorAll('main details').forEach(e=>e.open=true));
  for(const [text,src] of Object.entries(config.audio)){const b=page.locator('main [data-audio="'+src+'"]').first();assert.equal(await b.count(),1,text);await b.click();await page.waitForFunction(src=>{const a=__audios[0];return a.src.endsWith(src)&&a.currentTime>0&&!a.error&&(!a.paused||a.ended)},src,{timeout:10000}).catch(async e=>{console.log('AUDIO FAILURE',text,src,await page.evaluate(()=>({src:__audios[0].src,time:__audios[0].currentTime,paused:__audios[0].paused,ended:__audios[0].ended,error:__audios[0].error?.message,status:[...document.querySelectorAll('.bp-audio-error')].map(e=>e.textContent)})));throw e});}
  await page.locator('.bp-toolbar [data-stop-audio]').click();await page.evaluate(()=>document.querySelectorAll('main details').forEach(e=>e.open=false));
 }
 if(width===390||width===1440){await page.locator('.bp-grid').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-12));await page.screenshot({path:'tmp/unit5-picture/'+engine+'-cards-'+width+'.jpg',type:'jpeg'});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'tmp/unit5-picture/'+engine+'-hero-'+width+'.jpg',type:'jpeg'});}
 assert.deepEqual(errors,[]);console.log(engine,width,'PASS: responsive cards, prompts/audio, projector, checklist, timer, deck, QR, auth');
 if(width===1440&&!process.env.SKIP_CATALOG){await page.goto(host+'/ingles/intermediate-2/practice-lab.html#unit-5-folder',{waitUntil:'networkidle'});await page.locator('#unit5ActivityGrid .ie2-lab-card').first().waitFor();assert.equal(await page.locator('#unit5ActivityGrid .ie2-lab-card').count(),published.filter(item=>Number(item.unit)===5).length);assert.equal(await page.locator('#labActivityTotal').textContent(),String(published.length));await page.locator('[data-lab-filter="speaking-game"]').click();await page.locator('#practiceLabSearch').fill('Behind the Picture');assert.equal(await page.locator('.ie2-lab-card:visible').count(),1);assert.equal(await page.locator('.ie2-lab-card:visible').getAttribute('href'),pathname);console.log('Practice Lab speaking catalog PASS');}
 await page.close();
}
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
