import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const qa = 'tmp/film-festival-qa';
const session = JSON.parse(fs.readFileSync(qa+'/session.json','utf8'));
const browser = await chromium.launch({channel:'chrome',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/assets/js/google-auth.js*',route=>route.fulfill({contentType:'application/javascript',body:'window.JaraLinguaAuth={getUser:()=>window.__festivalUser||null,openPanel:()=>{}};'}));
await page.route('https://accounts.google.com/**',route=>route.fulfill({body:''}));
await page.route('**/api/intermediate2/film-festival/**',async route=>{
  const path=new URL(route.request().url());
  const response=await route.fetch({url:session.base+path.pathname+path.search});
  await route.fulfill({response});
});
const signIn=async key=>{
  await page.evaluate(user=>{window.__festivalUser=user;window.dispatchEvent(new Event('jaralingua:auth-changed'));},key?{credential:session.tokens[key],provider:'local'}:null);
  if(key)await page.waitForFunction(()=>!document.getElementById('ff-message').textContent.includes('Loading'));
};
const visible=async selector=>{await page.locator(selector).waitFor({state: 'visible'});assert(await page.locator(selector).isVisible(),selector);};
try{
  await page.goto('http://127.0.0.1:8024/ingles/intermediate-2/speaking-unit-4-film-festival.html');
  await visible('#ff-signin');
  assert.equal(await page.locator('#ff-teacher').isVisible(),false);
  await page.screenshot({path:qa+'/page-desktop.jpg',type:'jpeg',quality:75,fullPage:true});
  await signIn('teacher');
  await visible('#ff-teacher');
  await page.locator('#ff-new-name').fill('QA Friday Festival '+Date.now());
  await page.locator('#ff-create button').click();
  await page.waitForFunction(()=>document.getElementById('ff-class-info').textContent.includes('Student code:'));
  const info=await page.locator('#ff-class-info').textContent();
  const code=info.match(/Student code: ([A-Z2-9]{8})/)[1];
  const classId=await page.locator('#ff-class-select').inputValue();
  for(const [key,title] of [['ana','The Golden Moon'],['leo','A Quiet Journey']]){
    await signIn(key);
    await page.locator('#ff-code').fill(code);
    await page.locator('#ff-join button').click();
    await visible('#ff-submit');
    await page.locator('#ff-movie').fill(title);
    await page.locator('#ff-description').fill('A bright golden moon against a blue landscape, using warm lighting and a central composition to express hope.');
    await page.locator('#ff-phrasal').selectOption('stand out');
    await page.locator('#ff-idiom').selectOption('steal the show');
    await page.locator('#ff-file').setInputFiles(qa+'/test-image.png');
    await page.waitForFunction(()=>document.getElementById('ff-student-status').textContent.includes('Preview ready'));
    await page.locator('#ff-no-text').check();
    await page.locator('#ff-send').click();
    await page.waitForFunction(()=>document.getElementById('ff-student-status').textContent.includes('Receipt:'));
    await page.locator('#ff-preview').waitFor({state:'visible'});
  }
  await signIn('teacher');
  await page.locator('#ff-class-select').selectOption(classId);
  await page.waitForFunction(()=>document.querySelectorAll('.ff-entry-project:not(:disabled)').length===2);
  await page.locator('#festival-workspace').scrollIntoViewIfNeeded();
  await page.screenshot({path:qa+'/teacher-gallery.jpg',type:'jpeg',quality:80});
  await page.locator('.ff-entry-project').first().click();
  await visible('#ff-projector');
  assert.equal(await page.locator('#ff-project-title').textContent(),'The Golden Moon');
  assert.equal(await page.locator('#ff-project-student').textContent(),'Ana Test');
  const bounds=await page.locator('#ff-projector').boundingBox();
  assert.equal(bounds.width,1440);assert.equal(bounds.height,1000);
  assert.equal(await page.locator('#ff-project-image').evaluate(el=>getComputedStyle(el).objectFit),'contain');
  await page.screenshot({path:qa+'/projection.jpg',type:'jpeg',quality:85});
  await page.clock.install();
  await page.locator('#ff-timer-start').click();
  await page.clock.fastForward(65000);
  assert.match(await page.locator('#ff-timer-note').textContent(),/minimum reached/);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#ff-projector').isVisible(),false);
  await page.locator('.ff-entry').first().getByRole('button',{name:'Evaluate',exact:true}).click();
  await visible('#ff-evaluate');
  assert(Number(await page.locator('#ff-seconds').inputValue())>=65);
  for(const selector of ['#ff-image-scores select','#ff-oral-scores select'])
    for(const select of await page.locator(selector).all())await select.selectOption('4');
  for(const id of ['ff-observed-phrasal','ff-observed-idiom','ff-image-textfree'])await page.locator('#'+id).check();
  await page.locator('#ff-feedback').fill('Clear reasons and an expressive image.');
  await page.screenshot({path:qa+'/evaluation.jpg',type:'jpeg',quality:80});
  await page.locator('#ff-grade-save').click();
  await page.waitForFunction(()=>document.getElementById('ff-message').textContent==='Evaluation saved.');
  await signIn('ana');
  await page.locator('#ff-code').fill(code);await page.locator('#ff-join button').click();
  await page.locator('#ff-my-review').waitFor({state:'visible'});
  assert.match(await page.locator('#ff-my-review').textContent(),/Clear reasons/);
  assert(!/[\u00c2\u00c3]/.test(await page.locator('#ff-my-review').textContent()),'UTF-8 text must render correctly');
  assert.equal(await page.locator('#ff-movie').isDisabled(),true);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#festival-workspace').scrollIntoViewIfNeeded();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile horizontal overflow');
  await page.screenshot({path:qa+'/student-mobile.jpg',type:'jpeg',quality:80,fullPage:true});
  await signIn(null);
  assert.equal(await page.locator('#ff-my-review').textContent(),'');
  assert.equal(await page.locator('#ff-gallery').textContent(),'');
  assert.equal(await page.locator('#ff-evaluate-description').textContent(),'');
  await visible('#ff-signin');
  await page.goto('http://127.0.0.1:8024/ingles/intermediate-2/practice-lab.html#unit-4-folder');
  await page.locator('#unit-4-folder summary').click();
  await page.locator('#unit4ActivityGrid a').nth(1).waitFor();
  assert.match(await page.locator('#unit4ActivityGrid').textContent(),/Our Film Festival/);
  const authPage=await browser.newPage();
  await authPage.route('https://accounts.google.com/**',route=>route.fulfill({body:''}));
  await authPage.goto('http://127.0.0.1:8024/ingles/intermediate-2/speaking-unit-4-film-festival.html',{waitUntil:'load'});
  await authPage.locator('#ff-signin').click();
  await authPage.locator('[data-auth-panel]').waitFor({state:'visible'});
  await authPage.close();
  // A remembered account is published by shared auth at window load.
  const remembered=await browser.newPage();
  await remembered.route('**/assets/js/google-auth.js*',route=>route.fulfill({contentType:'application/javascript',body:
    'window.addEventListener("load",()=>{window.JaraLinguaAuth={getUser:()=>('+JSON.stringify({credential:session.tokens.ana,provider:'local'})+')};});'}));
  await remembered.route('https://accounts.google.com/**',route=>route.fulfill({body:''}));
  await remembered.route('**/api/intermediate2/film-festival/**',async route=>{
    const url=new URL(route.request().url());
    await route.fulfill({response:await route.fetch({url:session.base+url.pathname+url.search})});
  });
  await remembered.goto('http://127.0.0.1:8024/ingles/intermediate-2/speaking-unit-4-film-festival.html',{waitUntil:'load'});
  await remembered.locator('#ff-student').waitFor({state:'visible'});
  await remembered.close();
  assert.deepEqual(errors,[]);
  console.log('PASS: real API upload, named gallery, full-screen projection, 65-second timer, evaluation, student feedback, logout, mobile and catalog.');
}finally{await browser.close();}
