const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto');
const box={window:{}};vm.runInNewContext(fs.readFileSync('assets/js/english-intermediate2-reported-speech-data.js','utf8'),box);const c=box.window.ReportedSpeechLesson;
const slug='speaking-unit-6-what-did-they-say.html',origin=process.env.REPORTED_ORIGIN||'http://127.0.0.1:8139';
assert.equal(c.scenes.length,11);assert.equal(new Set(c.scenes.map(s=>s.image)).size,11);assert.equal(c.scenes[0].slug,'example');
for(const s of c.scenes){assert(fs.existsSync('.'+s.image),s.image);assert.equal(s.a.length,3);assert.equal(s.b.length,3);assert.equal(s.changes.length,3);assert.match(s.b[0],/^Ana said that /);}
const manifest=JSON.parse(fs.readFileSync('ingles/intermediate-2/audio/unit-6-reported-speech/models.json'));assert.equal(manifest.items.length,25);
const audits=JSON.parse(fs.readFileSync('ingles/intermediate-2/audio/unit-6-reported-speech/audio-audit.json'));assert.equal(audits.length,25);
for(const i of manifest.items){let hash=crypto.createHash('sha256').update(fs.readFileSync('.'+c.audioRoot+i.file)).digest('hex');assert.equal(hash,i.sha256);assert(audits.some(a=>a.file===i.file&&a.matched&&a.sha256===hash));}
const html=fs.readFileSync('ingles/intermediate-2/'+slug,'utf8'),js=fs.readFileSync('assets/js/english-intermediate2-reported-speech.js','utf8');assert(!/speechSynthesis|localStorage|getUserMedia/.test(js));assert.match(html,/page-qr-access/);assert.match(html,/a fact that is still true/);assert.match(html,/told me/);assert(!/ElevenLabs/i.test(html));
const catalog=JSON.parse(fs.readFileSync('assets/data/english-intermediate-2-content.json'));const entry=Object.values(catalog).find(Array.isArray).find(x=>x.id==='unit-6-what-did-they-say');assert.equal(entry.unit,6);assert.equal(entry.teacherSubmission,false);assert(entry.workshopHref.endsWith(slug));
console.log('PASS static: 1 example + 10 distinct images, 33 paired sentences, 25 audited recordings, QR/catalog and formative scope.');
if(process.argv.includes('--static'))process.exit(0);
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch();try{const p=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://accounts.google.com/**',r=>r.fulfill({body:''}));await p.goto(origin+'/ingles/intermediate-2/'+slug);await p.waitForFunction(()=>document.querySelector('#rsImage').naturalWidth>0);
assert.equal(await p.locator('#rsGallery button').count(),10);assert(await p.locator('#rsModels').evaluate(e=>e.open));
for(const width of [320,390,768,1024,1440,1920]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await p.locator('.rs-hero figure img').isVisible());await p.locator('.jl-page-qr-open').click();assert(await p.locator('.jl-page-qr-dialog').isVisible());await p.keyboard.press('Escape');if(width>=1100){const boxes=await p.locator('.rs-round').first().evaluate(e=>[...e.children].map(x=>{let r=x.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right}}));assert(Math.abs(boxes[0].y-boxes[2].y)<2);assert(boxes[0].right<boxes[1].x&&boxes[1].right<boxes[2].x);}}
await p.setViewportSize({width:1440,height:900});
for(let i=0;i<11;i++){if(i>0)await p.locator('#practice [data-nav="next"]').click();assert.equal(await p.locator('#rsTitle').innerText(),c.scenes[i].title);assert.equal(await p.locator('#rsModels').evaluate(e=>e.open),i===0);await p.waitForFunction(()=>document.querySelector('#rsImage').complete&&document.querySelector('#rsImage').naturalWidth>0);await p.locator('#practice [data-project="image"]').click();assert(await p.locator('#rsProjector').evaluate(e=>e.open));assert.equal(await p.locator('#rsProjected img').getAttribute('src'),c.scenes[i].image);await p.keyboard.press('Escape');if(i>0)await p.locator('#rsModels summary').click();assert.equal(await p.locator('#rsModelBody .rs-model-pair p').count(),6);await p.locator('#rsModels [data-project="model"]').click();assert.match(await p.locator('#rsProjected').innerText(),/Ana said that/);await p.locator('#rsProjected [data-audio]').first().click();await p.waitForFunction(()=>document.querySelector('#rsAudio').currentTime>0);await p.locator('#rsClose').click();await p.waitForFunction(()=>{const a=document.querySelector('#rsAudio');return a.paused&&!a.getAttribute('src');});}
assert(await p.locator('#practice [data-nav="next"]').isDisabled());await p.locator('[data-select="0"]').click();
for(const type of ['a','b','round','guide','changes','grammar']){const trigger=p.locator('main [data-project="'+type+'"]').first();if(['changes','grammar'].includes(type))await p.locator('.rs-guide').first().evaluate(e=>e.open=true);await trigger.click();assert((await p.locator('#rsProjected').innerText()).length>60);await p.setViewportSize({width:390,height:844});assert(await p.locator('#rsProjector').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.locator('#rsClose').click();await p.setViewportSize({width:1440,height:900});}
await p.locator('[data-project="image"]').first().click();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#rsTitle').innerText(),c.scenes[1].title);await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#rsTitle').innerText(),c.scenes[0].title);await p.locator('#rsProjector').evaluate(e=>e.requestFullscreen=()=>Promise.reject(new Error('test')));await p.locator('#rsFullscreen').click();await p.waitForFunction(()=>document.querySelector('#rsProjectionStatus').textContent.includes('unavailable'));await p.locator('#rsClose').click();
await p.locator('#rsSearch').fill('drought');assert.equal(await p.locator('#rsGallery button:visible').count(),1);await p.locator('#rsSearch').fill('zzzzz');assert(await p.locator('#rsEmpty').isVisible());await p.locator('#rsSearch').fill('');assert.equal(await p.locator('#rsGallery button:visible').count(),10);
await p.locator('#rsSpeed').selectOption('0.75');await p.locator('#rsModels [data-audio]').first().click();await p.waitForFunction(()=>document.querySelector('#rsAudio').currentTime>0);assert.equal(await p.locator('#rsAudio').evaluate(a=>a.playbackRate),.75);await p.locator('#practice [data-nav="next"]').click();assert(await p.locator('#rsAudio').evaluate(a=>a.paused&&!a.getAttribute('src')));
await p.route('**/audio/unit-6-reported-speech/flood-a.mp3',r=>r.abort());await p.locator('#rsModels summary').click();await p.locator('#rsModels [data-audio]').first().click();await p.waitForFunction(()=>document.querySelector('#rsAudioStatus').textContent.includes('could not'));await p.unroute('**/audio/unit-6-reported-speech/flood-a.mp3');
await p.setViewportSize({width:1440,height:900});await p.screenshot({path:'/private/tmp/reported-speech-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/private/tmp/reported-speech-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
await p.goto(origin+'/ingles/intermediate-2/practice-lab.html');await p.waitForSelector('a[href$="'+slug+'"]');await p.locator('#unit-6-folder').evaluate(e=>e.open=true);assert(await p.locator('a[href$="'+slug+'"]').first().isVisible());
for(const path of [...c.scenes.map(s=>s.image),...manifest.items.map(i=>c.audioRoot+i.file)]){const r=await p.request.get(origin+path);assert.equal(r.status(),200,path);}
console.log('PASS browser: 11 scenes, A/B models, every projection mode, QR, six widths, audio playback/speed/cancellation/errors, gallery search, keyboard and Practice Lab.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
