const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const host='https://www.jaralingua.com',pathname='/ingles/intermediate-2/reading-unit-5-little-red-riding-hood.html',data=JSON.parse(fs.readFileSync('assets/data/english-intermediate2-red-riding-hood.json','utf8'));
const local=p=>p===pathname||p.includes('english-intermediate2-red-riding-hood.')||p.includes('/unit-5/red-riding-hood/')||p.includes('/audio/unit-5-red-riding-hood/')||p.endsWith('ingles-intermediate-2-reading-unit-5-little-red-riding-hood.svg');
(async()=>{const engine=process.env.WEBKIT?'webkit':'chrome',browser=await(process.env.WEBKIT?webkit:chromium).launch(process.env.WEBKIT?{headless:true}:{channel:'chrome',headless:true});try{
 fs.mkdirSync('tmp/unit5-red-riding-hood',{recursive:true});assert.equal(data.pages.length,8);assert.equal(new Set(data.pages.map(p=>p.image)).size,8);
 for(const width of process.env.WIDTH?[+process.env.WIDTH]:[320,390,430,768,1024,1440,1920]){
  const page=await browser.newPage({viewport:{width,height:process.env.LANDSCAPE?390:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const ref=await page.request.get(host+'/ingles/intermediate-2/speaking-unit-5-our-picture-stories.html'),csp=ref.headers()['content-security-policy'];assert(csp);
  if(!process.env.LIVE)await page.route(host+'/**',async route=>{const p=new URL(route.request().url()).pathname;if(!local(p)||(process.env.MEDIA_LIVE&&p.endsWith('.mp3')))return route.continue();const target=path.resolve('.'+p);if(p.endsWith('.mp3')){const raw=fs.readFileSync(target),range=route.request().headers()['range'];if(range){const m=range.match(/bytes=(\d+)-(\d*)/);const start=+m[1],end=m[2]?Math.min(+m[2],raw.length-1):raw.length-1;return route.fulfill({status:206,body:raw.subarray(start,end+1),headers:{'Content-Type':'audio/mpeg','Accept-Ranges':'bytes','Content-Range':`bytes ${start}-${end}/${raw.length}`,'Content-Length':String(end-start+1)}});}return route.fulfill({body:raw,contentType:'audio/mpeg',headers:{'Accept-Ranges':'bytes'}});}return route.fulfill({path:target,headers:p.endsWith('.html')?{'Content-Security-Policy':csp}:{}});});
  await page.addInitScript(()=>{const A=window.Audio;window.__audios=[];window.Audio=function(...args){const a=new A(...args);window.__audios.push(a);return a};window.Audio.prototype=A.prototype;});
  await page.goto(host+pathname,{waitUntil:'networkidle'});assert(await page.locator('#rrCover').isVisible());assert(await page.locator('#rrListen').isDisabled());assert(await page.locator('[data-prev]').isDisabled());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('.jl-page-qr-open').click();await page.locator('.jl-page-qr-dialog').waitFor({state:'visible'});if(width===1440)await page.locator('.jl-page-qr-dialog img').screenshot({path:'tmp/unit5-red-riding-hood/qr-expanded.png'});await page.keyboard.press('Escape');
  await page.locator('[data-auth-toggle]').click();await page.locator('[data-local-login-form]').waitFor({state:'visible'});assert(await page.locator('[data-auth-panel]').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.left>=0&&r.bottom<=innerHeight+1&&r.right<=innerWidth+1&&e.contains(document.elementFromPoint(r.x+20,r.y+20))}));await page.keyboard.press('Escape');
  await page.locator('#rrReader').scrollIntoViewIfNeeded();if([390,1440].includes(width))await page.screenshot({path:'tmp/unit5-red-riding-hood/'+engine+'-cover-'+width+'.jpg',type:'jpeg'});
  await page.locator('#rrBegin').click();await page.locator('#rrImage').evaluate(e=>e.decode());assert.equal(await page.locator('#rrPageTitle').textContent(),data.pages[0].title);assert.equal(await page.locator('#rrText [data-phrase]').count(),3);
  assert.equal(await page.locator('#rrText').evaluate(e=>[...e.querySelectorAll('p')].map(p=>{const c=p.cloneNode(true);c.querySelectorAll('button span').forEach(n=>n.remove());return c.textContent})).then(p=>p.join('\n')),data.pages[0].paragraphs.join('\n'));
  await page.locator('#rrListen').click();await page.waitForFunction(()=>__audios[0].currentTime>0&&!__audios[0].paused,null,{timeout:20000});assert.equal(await page.evaluate(()=>__audios[0].playbackRate),.75);await page.locator('[data-rate="1"]').click();assert.equal(await page.evaluate(()=>__audios[0].playbackRate),1);await page.locator('#rrListen').click();assert.equal(await page.evaluate(()=>__audios[0].paused),true);await page.locator('#rrListen').click();await page.waitForFunction(()=>!__audios[0].paused);await page.locator('#rrStop').click();assert.equal(await page.evaluate(()=>__audios[0].paused),true);
  await page.locator('#rrText [data-phrase]').first().click();await page.waitForFunction(()=>__audios[0].currentTime>0&&!__audios[0].paused);await page.locator('[data-next]').click();assert.equal(await page.evaluate(()=>__audios[0].paused),true);assert.equal(await page.locator('#rrJump').inputValue(),'1');
  await page.locator('#rrJump').selectOption('5');await page.locator('#rrSceneHelp summary').click();assert.match(await page.locator('#rrQuestion').textContent(),/must and can't/);assert.match(await page.locator('#rrLanguage').textContent(),/not an obligation/);assert.equal(await page.locator('#rrLanguage article').count(),3);
  await page.locator('#rrImageOpen').click();await page.locator('#rrLargeImage').evaluate(e=>e.decode());assert.equal(await page.locator('#rrLargeImage').evaluate(e=>getComputedStyle(e).objectFit),'contain');assert(await page.locator('#rrLargeImage').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&r.height>80}));await page.keyboard.press('Escape');
  await page.locator('#rrEnlarge').click();await page.locator('#rrReadingDialog').waitFor({state:'visible'});assert.equal(await page.locator('#rrReadingSlot #rrReader').count(),1);await page.locator('#rrImage').evaluate(e=>e.decode());await page.locator('#rrTextSize').click();assert(await page.locator('#rrReader').evaluate(e=>e.classList.contains('is-large')));
  assert(await page.locator('[data-next]').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}),'page navigation visible in enlarged view');
  if([390,1440,1920].includes(width))await page.screenshot({path:'tmp/unit5-red-riding-hood/'+engine+'-enlarged-'+width+'.jpg',type:'jpeg'});
  await page.locator('#rrImageOpen').click();await page.locator('#rrImageDialog').waitFor({state:'visible'});await page.keyboard.press('Escape');assert(await page.locator('#rrReadingDialog').isVisible());
  if(width===1440&&!process.env.WEBKIT){await page.locator('#rrFullscreen').click();await page.waitForFunction(()=>!!document.fullscreenElement);await page.locator('#rrFullscreen').click();await page.waitForFunction(()=>!document.fullscreenElement);}
  await page.locator('#rrCloseReading').click();await page.locator('#rrHome #rrReader').waitFor({state:'visible'});assert(!await page.evaluate(()=>document.documentElement.classList.contains('rr-modal-open')));
  if(width===1440&&!process.env.SKIP_DEEP){
   const heard=new Set();for(let i=0;i<8;i++){await page.locator('#rrJump').selectOption(String(i));await page.locator('#rrImage').evaluate(e=>e.decode());await page.locator('#rrListen').click();const src=data.pages[i].audio;await page.waitForFunction(src=>__audios[0].src.endsWith(src)&&__audios[0].currentTime>0&&!__audios[0].error,src);heard.add(src);
    for(const b of await page.locator('#rrText [data-phrase]').all()){const n=+(await b.getAttribute('data-phrase')),src=data.pages[i].phrases[n].audio;await b.click();await page.waitForFunction(src=>__audios[0].src.endsWith(src)&&__audios[0].currentTime>0&&!__audios[0].error,src);heard.add(src);}
   }assert.equal(heard.size,32);
   await page.locator('#rrJump').selectOption('0');await page.locator('#rrListenAll').click();for(let i=0;i<8;i++){const src=data.pages[i].audio;await page.waitForFunction(src=>__audios[0].src.endsWith(src)&&__audios[0].duration>1&&!__audios[0].paused,src);assert.equal(await page.locator('#rrJump').inputValue(),String(i));await page.evaluate(()=>{__audios[0].currentTime=__audios[0].duration-.12;});if(i<7)await page.waitForFunction(n=>document.querySelector('#rrJump').value===String(n),i+1);}
   await page.waitForFunction(()=>document.querySelector('#rrAudioStatus').textContent.includes('whole book'));assert(await page.locator('[data-next]').isDisabled());assert(await page.locator('#rrEnd').isVisible());
   await page.locator('#rrJump').selectOption('0');await page.locator('#rrListenAll').click();await page.waitForFunction(()=>!__audios[0].paused);await page.locator('[data-next]').click();assert.equal(await page.locator('#rrListenAll').getAttribute('aria-pressed'),'false');assert.equal(await page.evaluate(()=>__audios[0].paused),true);
   console.log(engine,'32 audio controls, all eight illustrations and continuous page transitions verified');
  }
  await page.locator('#rrJump').selectOption('2');await page.locator('#rrReader').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForTimeout(600);if([390,1440,1920].includes(width))await page.screenshot({path:'tmp/unit5-red-riding-hood/'+engine+'-page-'+width+'.jpg',type:'jpeg'});
  await page.locator('#rrJump').selectOption('-1');assert(await page.locator('#rrCover').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);await page.close();console.log(engine,width,'PASS: book, narration, pronunciation, projection, QR and login');
 }
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
