const {chromium}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=process.cwd(),server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':{'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'}[path.extname(p)]||'application/octet-stream'});res.end(e?'':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.ENGLISH_PORTAL_TEST_BASE_URL||'http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'msedge',headless:true}),out=path.join(process.env.TEMP,'jaralingua-english-portal-qa');fs.mkdirSync(out,{recursive:true});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://accounts.google.com/**',r=>r.abort());await page.goto(base+'/ingles/index.html',{waitUntil:'networkidle'});
 assert.equal(await page.locator('.english-program-card').count(),4);assert.equal(await page.locator('.english-feature-list').count(),0);assert.equal(await page.locator('.quick-access-dropdown').getAttribute('open'),null);
 const paragraphs=await page.locator('.english-program-content p').allTextContents();for(const p of paragraphs){assert.ok(p.trim().split(/\s+/).length<=10,p);assert.equal((p.match(/[.!?]/g)||[]).length,1);}
 assert.deepEqual(await page.locator('.english-program-content .card-link').evaluateAll(es=>es.map(e=>e.getAttribute('href'))),['basico/index.html','basico-2/index.html','intermediate/index.html','intermediate-2/index.html']);
 for(const width of [1920,1440,1024,768,390,320]){await page.setViewportSize({width,height:900});const d=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,cols:getComputedStyle(document.querySelector('.english-program-grid')).gridTemplateColumns.split(' ').length,width:document.querySelector('.english-program-grid').getBoundingClientRect().width,search:document.querySelector('.course-search-panel').getBoundingClientRect().width,hero:getComputedStyle(document.querySelector('.english-index-hero')).position,header:getComputedStyle(document.querySelector('.site-header')).position,images:[...document.querySelectorAll('.english-program-image img')].every(i=>i.complete&&i.naturalWidth>0)}));assert.ok(d.scroll<=width+2,JSON.stringify({width,...d}));assert.equal(d.cols,width>1100?4:width>560?2:1);assert.ok(d.width>=width-66);assert.ok(d.search>=width-66);assert.ok(d.images);assert.ok(!['fixed','sticky'].includes(d.hero));assert.ok(!['fixed','sticky'].includes(d.header));assert.ok(await page.locator('.site-header .auth-trigger').isVisible(),'Top sign in missing');if([1440,390].includes(width))await page.screenshot({path:path.join(out,'page-'+width+'.png'),fullPage:true});}
 await page.locator('#englishHomeSearch').fill('shopping');await page.waitForTimeout(350);assert.equal(await page.locator('.english-program-card:visible').count(),1);await page.locator('[data-course-search-clear]').click();assert.equal(await page.locator('.english-program-card:visible').count(),4);await page.locator('#englishHomeSearch').fill('zzzznotfound');await page.waitForTimeout(350);assert.ok(await page.locator('[data-course-search-empty]').isVisible());assert.deepEqual(errors,[]);console.log('PASS: concise cards, full width, six viewport sizes, images, top sign-in, navigation and search. '+out);
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
