const {chromium}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=process.cwd(),route='/ingles/basico-2/practice-unit-5-compare-the-past.html';
const data=JSON.parse(fs.readFileSync('assets/data/basic2-compare-the-past.json','utf8'));
assert.equal(data.cards.length,12);const qs=data.cards.flatMap(c=>c.questions);assert.equal(qs.length,24);assert.equal(qs.filter(q=>q.correct).length,12);
for(const c of data.cards){assert.equal(c.questions.length,2);assert.equal(c.labels.length,2);assert.equal(c.facts.length,2);for(const q of c.questions){assert.match(q.question,/^(Was|Were) .* than .*\?$/);assert.match(q.answer,/ than /);assert.ok(q.answer.startsWith(q.correct?'Yes,':'No,'));}}
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.mp3':'audio/mpeg','.wav':'audio/wav'}[path.extname(p)]||'application/octet-stream'});res.end(e?'':b);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.COMPARE_PAST_TEST_BASE_URL||'http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'msedge',headless:true}),out=path.join(process.env.TEMP,'jaralingua-compare-past-qa');fs.mkdirSync(out,{recursive:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.route('**/google-auth.js*',r=>r.fulfill({contentType:'text/javascript',body:''}));await page.route('https://accounts.google.com/**',r=>r.abort());
  await page.addInitScript(()=>{window.qaUser={email:'teacher@example.invalid',credential:'test-only',provider:'google'};window.JaraLinguaAuth={getUser:()=>window.qaUser,openPanel:()=>{window.panelOpened=true;}};window.audioCalls=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){window.audioCalls.push(this.src);return play.call(this);};const timeout=window.setTimeout;window.setTimeout=(fn,ms,...args)=>timeout(fn,ms===3500?80:ms,...args);});
  let status=200,role='teacher',delay=0,requests=0;
  await page.route('**/api/basic2/grades',async r=>{requests++;assert.equal(r.request().headers()['authorization'],'Bearer test-only');if(delay)await new Promise(x=>setTimeout(x,delay));try{await r.fulfill({status,contentType:'application/json',body:JSON.stringify({role,students:[1,2,3,4,5,5].map(n=>({id:String(n),fullName:'Test Student '+n,email:'do-not-retain@example.invalid'}))})});}catch{}});
  await page.goto(base+route,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelectorAll('.cp-card').length===12);
  assert.equal(await page.locator('details[open]').count(),0);assert.equal(await page.locator('#deck img').count(),0);
  for(const width of [1920,1440,1024,768,390,320]){
   await page.setViewportSize({width,height:1000});const box=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,hero:getComputedStyle(document.querySelector('.lesson-hero')).position,header:getComputedStyle(document.querySelector('.site-header')).position,shell:document.querySelector('.cp-shell').getBoundingClientRect().width,cols:getComputedStyle(document.querySelector('.cp-deck')).gridTemplateColumns.split(' ').length}));
   assert.ok(box.scroll<=width+2,JSON.stringify({width,...box}));assert.ok(box.shell>=width-50);assert.ok(!['fixed','sticky'].includes(box.hero));assert.ok(!['fixed','sticky'].includes(box.header));assert.equal(box.cols,width>1050?4:width>650?3:2);
   await page.locator('.jl-page-qr-open').click();const qr=await page.locator('.jl-page-qr-dialog').boundingBox();assert.ok(Math.abs(qr.x+qr.width/2-width/2)<2);await page.locator('.jl-page-qr-close').click();
   if([1440,390].includes(width))await page.screenshot({path:path.join(out,'page-'+width+'.png'),fullPage:true});
  }
  await page.setViewportSize({width:1440,height:1000});await page.locator('#playModel').click();await page.waitForFunction(()=>document.querySelector('#modelAudio').currentTime>0);assert.equal(await page.locator('#modelAudio').evaluate(a=>a.playbackRate),.75);await page.locator('[data-speed="1"]').click();assert.equal(await page.locator('#modelAudio').evaluate(a=>a.playbackRate),1);await page.locator('#playModel').click();
  status=401;await page.locator('#loadRoster').click();await page.waitForFunction(()=>document.querySelector('#rosterStatus').textContent.includes('expired'));assert.equal(await page.locator('#loadRoster').isEnabled(),true);
  status=200;role='student';await page.locator('#loadRoster').click();await page.waitForFunction(()=>document.querySelector('#rosterStatus').textContent.includes('Only the authorized'));assert.equal(await page.locator('#roster input').count(),0);
  role='teacher';await page.locator('#loadRoster').click();await page.waitForFunction(()=>document.querySelectorAll('#roster input').length===5);await page.locator('#roster').evaluate(e=>e.parentElement.open=true);await page.locator('#roster input').last().uncheck();await page.locator('#roster').evaluate(e=>e.parentElement.open=false);
  const selected=new Set();let turns=0;
  for(let i=0;i<12;i++){
   await page.locator('.cp-card').nth(i).click();await page.waitForFunction(()=>document.querySelector('#sceneImage').complete&&document.querySelector('#sceneImage').naturalWidth>0);
   if(i===0){for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});const d=await page.locator('#cardDialog').boundingBox();assert.ok(Math.abs(d.x+d.width/2-width/2)<2);assert.ok(await page.locator('#cardDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2));await page.locator('#enlargeScene').click();const z=await page.locator('#imageDialog').boundingBox();assert.ok(Math.abs(z.x+z.width/2-width/2)<2);await page.locator('#closeImage').click();if([1440,390].includes(width))await page.screenshot({path:path.join(out,'dialog-'+width+'.png')});}await page.setViewportSize({width:1440,height:1000});await page.locator('#hideScene').click();assert.equal(await page.locator('#sceneImage').isVisible(),false);await page.locator('#hideScene').click();}
   for(let j=0;j<2;j++){
    if(selected.size===4){await page.locator('#modalResetRound').click();selected.clear();}
    assert.equal(await page.locator('#answerKey').isVisible(),false);
    await page.locator('#spinStudent').evaluate(b=>{b.click();b.click();});await page.waitForFunction(()=>!document.querySelector('#revealQuestion').disabled);const name=await page.locator('#winner').innerText();assert.ok(!selected.has(name),name);assert.notEqual(name,'Test Student 5');selected.add(name);turns++;
    if(i===0&&j===0){await page.locator('#closeCard').click();await page.locator('.cp-card').first().click();assert.equal(await page.locator('#winner').innerText(),name);assert.ok(await page.locator('#spinStudent').isDisabled());}
    assert.doesNotMatch(await page.locator('#questionText').innerText(),/^(Was|Were) /);await page.locator('#revealQuestion').click();assert.equal(await page.locator('#questionText').innerText(),data.cards[i].questions[j].question);assert.equal(await page.locator('#answerKey').getAttribute('open'),null);await page.locator('#answerKey summary').click();assert.equal(await page.locator('#answerText').innerText(),data.cards[i].questions[j].answer);await page.locator('#nextQuestion').click();
   }
  }
  assert.equal(turns,24);assert.match(await page.locator('#cardCount').innerText(),/^12 of 12/);assert.equal(await page.locator('dialog[open]').count(),0);
  const calls=await page.evaluate(()=>window.audioCalls);assert.ok(calls.some(u=>u.endsWith('roulette.wav')));assert.ok(calls.some(u=>u.endsWith('card-flip.wav')));
  await page.locator('#soundToggle').click();const before=await page.evaluate(()=>window.audioCalls.length);await page.locator('.cp-card').first().click();assert.equal(await page.evaluate(()=>window.audioCalls.length),before);await page.locator('#closeCard').click();
  await page.evaluate(()=>{window.qaUser=null;dispatchEvent(new Event('jaralingua:auth-changed'));});assert.equal(await page.locator('#roster input').count(),0);await page.locator('#loadRoster').click();assert.equal(await page.evaluate(()=>window.panelOpened),true);
  await page.evaluate(()=>{window.qaUser={email:'teacher@example.invalid',credential:'test-only',provider:'google'};dispatchEvent(new Event('jaralingua:auth-changed'));});delay=400;const prior=requests;await page.locator('#loadRoster').click();await page.waitForTimeout(60);assert.ok(requests>prior);await page.evaluate(()=>{window.qaUser=null;dispatchEvent(new Event('jaralingua:auth-changed'));});await page.waitForTimeout(500);assert.equal(await page.locator('#roster input').count(),0);assert.ok(await page.locator('#loadRoster').isEnabled());
  for(const url of [...data.cards.map(c=>c.image),'/assets/img/english-basic-2/compare-the-past/hero.png','/assets/img/english-basic-2/compare-the-past/model.png','/assets/img/page-qr/ingles-basico-2-practice-unit-5-compare-the-past.svg','/ingles/basico-2/audio/unit5/compare-the-past/teacher-model.mp3']){assert.equal((await page.request.get(base+url)).status(),200,url);}
  const real=await browser.newPage();await real.route('https://accounts.google.com/**',r=>r.abort());await real.goto(base+route,{waitUntil:'networkidle'});for(const width of [1440,768,390,320]){await real.setViewportSize({width,height:900});assert.ok(await real.locator('.site-header .auth-trigger').isVisible());assert.ok(await real.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Actual auth overflow '+width);}
  await real.goto(base+'/ingles/basico-2/practice-lab.html',{waitUntil:'networkidle'});assert.equal(await real.locator('#unit-5-folder').getAttribute('open'),null);assert.equal(await real.locator('#unit-5-folder a[href="practice-unit-5-compare-the-past.html"]').count(),1);
  assert.deepEqual(errors,[]);console.log('PASS: 24 turns, all images, no-repeat, attendance, reopen, double-click, auth errors/race, audio/speeds, QR, 6 widths and Practice Lab. '+out);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1)});
