const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('frances/Niveau 1/assets/pronunciation-a1.js', 'utf8');
const fn = source.slice(source.indexOf('  function speakWord(word) {'), source.indexOf('  function formatTime(ms) {'));
let spoken = [], paused = 0;
const french = {lang:'fr-FR'}, english = {lang:'en-US'};
let voices = [english, french];
const els = {modelAudio:{pause(){paused++;}},playback:{pause(){paused++;}},modelButton:{querySelector(){return {}; }},wordHelp:{}};
const synth = {cancel(){},resume(){},getVoices(){return voices;},speak(u){spoken.push(u);}};
const Utterance = function(text){this.text=text;};
const context = vm.createContext({els,window:{speechSynthesis:synth,SpeechSynthesisUtterance:Utterance},speechSynthesis:synth,SpeechSynthesisUtterance:Utterance,pronunciationTip:()=>''});
vm.runInContext(fn+'\nspeakWord("français");',context);
assert.equal(spoken.length,1);
assert.equal(spoken[0].text,'français');
assert.equal(spoken[0].lang,'fr-FR');
assert.equal(spoken[0].voice,french);
assert.equal(paused,2);
voices=[english];
vm.runInContext('speakWord("famille")',context);
assert.equal(spoken.length,1, 'Never fall back to an English voice');
assert.match(els.wordHelp.textContent,/voix française/);
assert.match(source,/if \(!attempt \|\| !Number\.isFinite\(score\)\)/);
assert.match(source,/if \(!audioDataUrl\) throw/);
assert.ok(!source.includes('"theme-1": { evaluationId:'));
assert.ok(source.includes('button.dataset.word'));
console.log('French word playback, missing evidence, and delivery controls passed.');
