import assert from "node:assert/strict";
import { existsSync, readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const pagePath = resolve(root, "ingles/intermediate-2/speaking-unit-2-reality-or-imagine-roulette.html");
const scriptPath = resolve(root, "assets/js/english-intermediate2-reality-roulette.js");
const cssPath = resolve(root, "assets/css/english-intermediate2-reality-roulette.css");
const catalogPath = resolve(root, "assets/data/english-intermediate-2-content.json");
const planPath = resolve(root, "docs/english-intermediate-2-master-plan.md");
const imagePath = resolve(root, "assets/img/english-intermediate-2/unit-2/reality-or-imagine-roulette/reality-or-imagine-roulette-hero-v1.png");
const page = readFileSync(pagePath, "utf8");
const script = readFileSync(scriptPath, "utf8");
const css = readFileSync(cssPath, "utf8");
const catalog = JSON.parse(readFileSync(catalogPath, "utf8"));
const plan = readFileSync(planPath, "utf8");

assert.ok(existsSync(imagePath) && statSync(imagePath).size > 100_000, "The activity must ship its professional hero image.");
assert.match(page, /Reality or Imagine\?/);
assert.match(page, /id="rrLoadGradebook"/);
assert.match(page, /Load Intermediate 2 roster/);
assert.match(page, /id="rrStudentWheel"/);
assert.match(page, /id="rrQuestionWheel"/);
assert.match(page, /id="rrStudentPool"/);
assert.match(page, /id="rrQuestionPool"/);
assert.match(page, /No grade or delivery/);
assert.doesNotMatch(page, /0%|Teacher delivery|Send to teacher/i);
assert.match(script, /const API = "\/api\/intermediate2\/grades"/);
assert.match(script, /\["admin", "teacher"\]\.includes\(data\.role\)/);
assert.match(script, /Only names were used/);
assert.match(script, /JaraLinguaRosterImport\.importFile/);
assert.doesNotMatch(script, /speechSynthesis|new Audio\(/);
assert.match(script, /startRouletteSound\(\)/);
assert.match(script, /stopRouletteSound\(true\)/);
assert.match(script, /createOscillator\(\)/);

const questionBlock = script.match(/const questions = \[([\s\S]*?)\n  \];/);
assert.ok(questionBlock, "Question set should be present.");
const ifPrompts = [...questionBlock[1].matchAll(/group: "If"/g)];
const wouldPrompts = [...questionBlock[1].matchAll(/group: "Would"/g)];
assert.equal(ifPrompts.length, 10, "There must be ten If prompts.");
assert.equal(wouldPrompts.length, 10, "There must be ten Would prompts.");
assert.match(questionBlock[1], /prompt: "If you had a free year/);
assert.match(questionBlock[1], /prompt: "Would you move abroad/);
assert.match(questionBlock[1], /If accepting a scholarship meant leaving your family or friends, …/);
assert.ok(questionBlock[1].includes("Complete it with would + base verb"));
assert.match(questionBlock[1], /Complete it with an If clause/);
assert.doesNotMatch(questionBlock[1], /where would you travel|Why or why not\?/);
assert.match(script, /pool\.splice\(index, 1\)/, "Used names and questions must leave their pools.");
assert.match(script, /state\.questionPool = questions\.slice\(\)/, "Reset must restore all questions.");

const item = catalog.items.find((entry) => entry.id === "unit-2-reality-or-imagine-roulette");
assert.ok(item, "The published activity must be in the catalog.");
assert.equal(item.unit, 2);
assert.equal(item.order, 8);
assert.equal(item.type, "speaking-game");
assert.deepEqual(item.questionGroups, { if: 10, would: 10 });
assert.equal(item.teacherRosterLoad, true);
assert.equal(item.teacherSubmission, false);
assert.equal(item.gradebookProjected, false);
assert.equal(item.status, "published");
assert.match(item.summary, /missing half/);
assert.match(css, /@media \(max-width: 650px\)/);
assert.match(css, /env\(safe-area-inset-left\)/);
assert.match(css, /background: #092453/);
assert.match(css, /color: #ffd77f/);
assert.match(css, /min-height: min\(610px, 65vh\)/);
assert.doesNotMatch(css, /position:\s*(?:fixed|sticky)/);
assert.match(plan, /Reality or Imagine\?/);
console.log("Intermediate 2 Reality or Imagine roulette static contract passed.");
