const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const box={window:{}};vm.runInNewContext(fs.readFileSync('assets/js/english-intermediate2-reported-speech-data.js','utf8'),box);const c=box.window.ReportedSpeechLesson,origin=process.env.REPORTED_ORIGIN||'http://127.0.0.1:8139',url=origin+'/ingles/intermediate-2/speaking-unit-6-what-did-they-say.html';
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
async function tipFits(page){assert(await page.locator('#rsTooltip').isVisible());assert(await page.locator('#rsTooltip').evaluate(t=>{const r=t.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&t.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));}
for(let i=0;i<11;i++){if(i)await p.locator('#practice [data-nav="next"]').click();const words=p.locator('#rsWords [data-word]');assert.equal(await words.count(),5);assert(await p.locator('#rsAudio').evaluate(a=>a.paused&&!a.getAttribute('src')));
 for(const term of c.scenes[i].vocabulary){const w=words.filter({hasText:term}).first();await w.hover();await tipFits(p);assert.equal(await p.locator('#rsTooltip').innerText(),c.glossary.find(w=>w.term===term).spanish);assert(await p.locator('#rsAudio').evaluate(a=>a.paused&&!a.getAttribute('src')));}
 await words.first().click();await p.waitForFunction(()=>document.querySelector('#rsAudio').currentTime>0);assert.equal(await words.first().getAttribute('aria-pressed'),'true');await p.locator('.rs-audio-bar [data-stop]').click();await p.locator('#rsWords [data-project]').click();assert.equal(await p.locator('#rsProjected [data-word]').count(),5);await p.locator('#rsProjected [data-word]').last().hover();await tipFits(p);assert(await p.locator('#rsTooltip').evaluate(e=>e.closest('dialog')?.open));await p.keyboard.press('Escape');assert(await p.locator('#rsTooltip').isHidden());assert(await p.locator('#rsProjector').evaluate(e=>e.open));await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#rsProjector').open);
}
await p.locator('[data-select="0"]').click();await p.locator('#rsModels [data-project]').click();const word=p.locator('#rsProjected [data-word="fallen branches"]').first();await word.focus();await tipFits(p);assert.equal(await p.locator('#rsTooltip').innerText(),'ramas caídas');await word.click();await p.waitForFunction(()=>document.querySelector('#rsAudio').currentTime>0);await p.locator('#rsClose').click();await p.waitForFunction(()=>document.querySelector('#rsAudio').paused);assert.equal(await p.locator('button button').count(),0);
for(const width of [320,390,768,1024,1440,1920]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));for(const selector of ['.rs-hero figure img','.rs-gallery img','#rsImage'])assert.equal(await p.locator(selector).first().evaluate(e=>getComputedStyle(e).objectFit),'contain');}
await p.setViewportSize({width:1440,height:900});await p.screenshot({path:'/private/tmp/reported-glossary-desktop.png',fullPage:true});
const phone=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await phone.goto(url);const mobileWord=phone.locator('#rsWords [data-word="witness"]');await mobileWord.tap();await tipFits(phone);await phone.waitForFunction(()=>document.querySelector('#rsAudio').currentTime>0);await phone.locator('#rsWords [data-project]').tap();await phone.locator('#rsProjected [data-word="microphone"]').tap();await tipFits(phone);await phone.screenshot({path:'/private/tmp/reported-glossary-mobile.png'});await phone.locator('#rsClose').tap();assert.deepEqual(errors,[]);await phone.close();console.log('PASS 11 banks × 5 words: Spanish hover without autoplay, click pronunciation, keyboard, touch, visible tooltip in projector, Escape, audio cancellation and full images at six widths.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
