const {chromium}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=process.cwd(),server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':{'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.mp3':'audio/mpeg','.png':'image/png','.svg':'image/svg+xml'}[path.extname(p)]||'application/octet-stream'});res.end(e?'':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.HOLIDAYS_TEST_BASE_URL||'http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://accounts.google.com/**',r=>r.abort());
await page.goto(base+'/ingles/basico-2/audio-listening-unit-5-my-holidays.html',{waitUntil:'networkidle'});
await page.waitForSelector('.question-card');assert.equal(await page.locator('.question-card').count(),10);assert.equal(await page.locator('input[type=radio]').count(),40);assert.equal(await page.locator('input:checked').count(),0);assert.ok(await page.locator('#teacherTools').isHidden());
const out=path.join(process.env.TEMP,'jaralingua-holidays-qa');fs.mkdirSync(out,{recursive:true});
for(const width of [1920,1440,1024,768,390,320]){await page.setViewportSize({width,height:900});const d=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,cols:getComputedStyle(document.querySelector('.question-grid')).gridTemplateColumns.split(' ').length,shell:document.querySelector('.holidays-shell').getBoundingClientRect().width,hero:getComputedStyle(document.querySelector('.lesson-hero')).position,header:getComputedStyle(document.querySelector('.site-header')).position,images:[...document.querySelectorAll('img')].filter(i=>!i.closest('dialog')).every(i=>i.complete&&i.naturalWidth>0)}));assert.ok(d.scroll<=width+2,JSON.stringify({width,...d}));assert.equal(d.cols,width>600?2:1);assert.ok(d.shell>=width-50);assert.ok(!['fixed','sticky'].includes(d.hero));assert.ok(!['fixed','sticky'].includes(d.header));assert.ok(d.images);assert.ok(await page.locator('.site-header .auth-trigger').isVisible());if([1440,390].includes(width))await page.screenshot({path:path.join(out,'page-'+width+'.png'),fullPage:true});}
await page.locator('[data-speed="0.75"]').click();assert.equal(await page.locator('audio').evaluate(e=>e.playbackRate),.75);await page.locator('[data-speed="1"]').click();assert.equal(await page.locator('audio').evaluate(e=>e.playbackRate),1);await page.locator('audio').evaluate(e=>e.play());await page.waitForTimeout(350);assert.ok(await page.locator('audio').evaluate(e=>!e.paused&&e.currentTime>0));await page.locator('audio').evaluate(e=>e.pause());console.log('Audio duration:',await page.locator('audio').evaluate(e=>e.duration));
await page.locator('#quizCheck').click();assert.match(await page.locator('#quizResult').textContent(),/10 unanswered/);
const qs=JSON.parse(fs.readFileSync('assets/data/basic2-unit5-holidays-questions.json','utf8'));for(let i=0;i<qs.length;i++)await page.locator(`input[name=q${i}][value="${qs[i].answer}"]`).check();await page.locator('#quizCheck').click();assert.equal(await page.locator('#quizScore').textContent(),'Score: 10 / 10');assert.equal(await page.locator('.feedback:visible').count(),10);await page.locator('input[name=q0][value="0"]').check();assert.equal(await page.locator('#quizScore').textContent(),'Not checked yet');await page.locator('#quizReset').click();assert.equal(await page.locator('input:checked').count(),0);
await page.route('**/api/basic2/unit5-my-holidays/transcript',async r=>{const staff=r.request().headers().authorization==='Bearer staff-test';await r.fulfill({status:staff?200:403,contentType:'application/json',body:JSON.stringify(staff?{transcript:'Protected teacher test transcript.'}:{error:'teacher_only'})});});
await page.evaluate(()=>{window.JaraLinguaAuth={getUser:()=>({credential:'student-test'})};window.dispatchEvent(new Event('jaralingua:auth-changed'));});await page.waitForTimeout(300);assert.ok(await page.locator('#teacherTools').isHidden());
await page.evaluate(()=>{window.JaraLinguaAuth={getUser:()=>({credential:'staff-test'})};window.dispatchEvent(new Event('jaralingua:auth-changed'));});await page.waitForSelector('#teacherTools',{state:'visible'});await page.locator('#transcriptToggle').click();assert.ok(await page.locator('#teacherTranscript').isVisible());await page.locator('#transcriptToggle').click();assert.ok(await page.locator('#teacherTranscript').isHidden());await page.evaluate(()=>{window.JaraLinguaAuth={getUser:()=>null};window.JaraLinguaCurrentUser=null;window.dispatchEvent(new Event('jaralingua:auth-changed'));});assert.ok(await page.locator('#teacherTools').isHidden());assert.equal(await page.locator('#transcriptText').textContent(),'');
await page.locator('.jl-page-qr-open').click();assert.ok(await page.locator('#jlPageQrDialog').isVisible());await page.keyboard.press('Escape');assert.ok(await page.locator('#jlPageQrDialog').isHidden());assert.deepEqual(errors,[]);
for(const index of ['practice-lab.html','listening-library.html','evaluations.html']){await page.goto(base+'/ingles/basico-2/'+index);assert.ok(await page.locator('a[href="audio-listening-unit-5-my-holidays.html"]').count());if(index==='practice-lab.html')assert.equal(await page.locator('#unit-5-folder').getAttribute('open'),null);}
console.log('PASS: six layouts, images/QR, sign in, audio playback and speeds, scoring/reset, transcript toggle/roles/logout, all three indexes. '+out);
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
