const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844}}),host='https://www.jaralingua.com',href='/ingles/intermediate-2/reading-unit-5-little-red-riding-hood.html';
 const staged='tmp/unit5-red-riding-hood/release';if(!process.env.LIVE)await p.route(host+'/**',async r=>{const name=new URL(r.request().url()).pathname;let f=path.join(staged,name);if(!fs.existsSync(f)){if(name!==href&&!name.includes('english-intermediate2-red-riding-hood.'))return r.continue();f=path.resolve('.'+name);}const ref=await r.fetch();return r.fulfill({response:ref,status:200,contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/html',body:fs.readFileSync(f)});});
 await p.goto(host+'/ingles/intermediate-2/practice-lab.html#unit-5-folder',{waitUntil:'networkidle'});await p.locator('a.ie2-lab-card[href="'+href+'"]').waitFor();
 await p.locator('#practiceLabSearch').fill('Little Red Riding Hood');await p.locator('[data-lab-filter="reading"]').click();assert.equal(await p.locator('.ie2-lab-card:visible').count(),1);
 const card=p.locator('a.ie2-lab-card[href="'+href+'"]');await card.locator('img').evaluate(e=>e.decode());await card.click();await p.waitForURL(host+href);await p.waitForLoadState('networkidle');await p.locator('#rrBegin').click();assert.equal(await p.locator('#rrPageTitle').textContent(),'A basket for Grandma');
 await p.goto(host+'/ingles/intermediate/idioms.html',{waitUntil:'networkidle'});
 for(const term of ['put on','run away','look for']){const label=p.locator('.idiom-btn-title').getByText(term,{exact:true});assert.equal(await label.count(),1);await label.click();assert.match(await p.locator('.idiom-display-header .idiom-category').textContent(),/^Phrasal verb/);assert(await p.locator('.meaning-box [lang="es"]').isVisible());if(term==='put on')assert.match(await p.locator('.meaning-box').textContent(),/clothes or accessories/);await p.locator('#expression-title .expression-pronunciation').click();await p.waitForFunction(()=>expressionAudio&&expressionAudio.currentTime>0&&!expressionAudio.error&&(!expressionAudio.paused||expressionAudio.ended));}
 console.log('PASS: book appears in Reading; catalog navigation; three expressions, meanings and pronunciation in the shared library.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
