const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const host='https://www.jaralingua.com',pathname='/ingles/intermediate-2/listening-unit-5-a-different-first-impression.html';
const data=JSON.parse(fs.readFileSync('assets/data/english-intermediate2-unit5-listening.json','utf8'));
const local=p=>p===pathname||p.includes('english-intermediate2-unit5-listening.')||p.includes('ingles-intermediate-2-listening-unit-5-a-different-first-impression.svg')||p==='/ingles/intermediate-2/listening-library.html'||p==='/assets/js/english-intermediate2-listening-library.js'||p==='/ingles/intermediate-2/practice-lab.html'||p==='/assets/data/english-intermediate-2-content.json';
(async()=>{const engine=process.env.WEBKIT?'webkit':'chrome';const browser=await(process.env.WEBKIT?webkit:chromium).launch(process.env.WEBKIT?{headless:true}:{channel:'chrome',headless:true});try{
for(const width of process.env.QUICK?[390,1440]:[320,390,430,768,1024,1440,1920]){
 const page=await browser.newPage({viewport:{width,height:900},deviceScaleFactor:1});const errors=[];let transcriptRole='student',transcriptDelay=0;page.on('pageerror',e=>errors.push(e.message));
 const ref=await page.request.get(host+'/ingles/intermediate-2/listening-unit-3-the-message-before-the-workshop.html');const csp=ref.headers()['content-security-policy'];assert(csp);
 if(!process.env.LIVE)await page.route(host+'/**',async r=>{const p=new URL(r.request().url()).pathname;if(!local(p))return r.continue();const release=path.resolve('tmp/unit5-listening/indexes'+p);const file=fs.existsSync(release)?release:path.resolve('.'+p);assert(fs.existsSync(file));return r.fulfill({path:file,headers:p.endsWith('.html')?{'Content-Security-Policy':csp}:{}});});
 await page.route(host+'/api/intermediate2/unit5-first-impression/transcript',async r=>{
  const role=transcriptRole,delay=transcriptDelay;assert.equal(r.request().headers()['authorization'],'Bearer test-'+role);if(delay)await new Promise(resolve=>setTimeout(resolve,delay));
  const turns=JSON.parse(fs.readFileSync('ingles/intermediate-2/audio/unit-5-listening/dialogue.json','utf8'));await r.fulfill({status:['teacher','admin'].includes(role)?200:403,json:['teacher','admin'].includes(role)?{transcript:turns.map(t=>t.speaker+': '+t.text).join('\n\n')}:{error:'teacher_only'}});
 });
 await page.addInitScript(()=>{const A=window.Audio;window.__audios=[];window.Audio=function(...args){const a=new A(...args);window.__audios.push(a);return a};window.Audio.prototype=A.prototype;window.__offset=0;const now=Date.now;Date.now=()=>now()+window.__offset;});
 await page.goto(host+pathname,{waitUntil:'networkidle'});const main=page.locator('#impressionAudio');
 assert.equal(await page.locator('.ie2-reading-question').count(),10);assert.equal(await page.locator('#impressionQuiz input').count(),30);for(let i=0;i<10;i++)assert.deepEqual(await page.locator('.ie2-reading-question').nth(i).locator('.u5l-option-letter').allTextContents(),['A.','B.','C.']);
 assert(await page.locator('.jl-page-qr-card img').evaluate(e=>e.complete&&e.naturalWidth>0));assert(await page.locator('.jl-page-qr-card img').evaluate(e=>Math.abs(e.getBoundingClientRect().width-e.getBoundingClientRect().height)<1));await page.locator('.jl-page-qr-open').click();await page.locator('.jl-page-qr-dialog').waitFor({state:'visible'});if(width===1440)await page.locator('.jl-page-qr-dialog img').screenshot({path:'tmp/unit5-listening/qr-expanded.png'});await page.keyboard.press('Escape');
 await page.locator('[data-auth-toggle]').click();await page.locator('[data-local-login-form]').waitFor({state:'visible'});assert(await page.locator('[data-auth-panel]').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&r.left>=0&&r.right<=innerWidth+1&&e.contains(document.elementFromPoint(r.left+20,r.top+20))}),'auth visible '+width);await page.keyboard.press('Escape');
 await page.waitForFunction(()=>Number.isFinite(document.querySelector('#impressionAudio').duration));const duration=await main.evaluate(e=>e.duration);assert(duration>82&&duration<86);assert.equal(await main.evaluate(e=>e.playbackRate),.75);
 await main.evaluate(e=>e.play());await page.waitForFunction(()=>document.querySelector('#impressionAudio').currentTime>0&&!document.querySelector('#impressionAudio').paused);
 for(const r of [1,1.25,.75]){await page.locator('[data-audio-speed="'+r+'"], [data-audio-speed="'+r.toFixed(2)+'"]').first().click();assert.equal(await main.evaluate(e=>e.playbackRate),r)}
 await page.locator('.ie2-listening-vocab-grid details').evaluateAll(es=>es.forEach(e=>e.open=true));const models=page.locator('[data-word-audio]');assert.equal(await models.count(),13);
 for(let i=0;i<(width===1440?13:1);i++){await models.nth(i).click();await page.waitForFunction(()=>__audios[0].currentTime>0&&(!__audios[0].paused||__audios[0].ended),null,{timeout:10000});assert.equal(await page.evaluate(()=>__audios[0].playbackRate),.75);assert.equal(await main.evaluate(e=>e.paused),true);await page.evaluate(()=>__audios[0].pause())}
 await models.last().click();await main.evaluate(e=>e.play());assert.equal(await page.evaluate(()=>__audios[0].paused),true);await main.evaluate(e=>e.pause());assert.equal(await page.locator('#retryAudio').isVisible(),false);if(width===1440){await main.evaluate(e=>e.dispatchEvent(new Event('error')));assert.equal(await page.locator('#retryAudio').isVisible(),true);await page.locator('#retryAudio').click();await page.waitForFunction(()=>!document.querySelector('#impressionAudio').paused&&document.querySelector('#impressionAudio').currentTime>0);await page.locator('#retryAudio').waitFor({state:'hidden'});await main.evaluate(e=>e.pause());}
 for(let i=0;i<3;i++){await page.locator('[data-prediction]').nth(i).click();assert.equal(await page.locator('[data-prediction][aria-pressed=true]').count(),1)}
 for(const pass of [1,2,3])await page.locator('[data-pass="'+pass+'"]').click();assert.match(await page.locator('#passStatus').textContent(),/3 of 3/);await page.locator('[data-pass="2"]').click();assert.match(await page.locator('#passStatus').textContent(),/2 of 3/);
 const check=page.locator('#impressionQuiz [type=submit]');await check.click();assert.match(await page.locator('#quizResult').textContent(),/0 \/ 10 answered/);assert.equal(await page.evaluate(()=>document.activeElement.name),'q1');
 for(let i=0;i<10;i++){const wrong=data.questions[i].answer==='a'?'b':'a';await page.locator('input[name=q'+(i+1)+'][value='+wrong+']').check()}await check.click();assert.match(await page.locator('#quizResult').textContent(),/0 \/ 10 correct/);
 for(let i=0;i<10;i++)await page.locator('input[name=q'+(i+1)+'][value='+data.questions[i].answer+']').check();await check.click();assert.match(await page.locator('#quizResult').textContent(),/10 \/ 10 correct/);for(let i=0;i<10;i++)assert((await page.locator('#feedback'+(i+1)).textContent()).includes(data.questions[i].evidence));
 if(width===390||width===1440){await page.locator('#listening-check').scrollIntoViewIfNeeded();await page.screenshot({path:'tmp/unit5-listening/'+engine+'-questions-'+width+'.jpg',type:'jpeg'})}
 await page.locator('input[name=q1][value=a]').check();assert.match(await page.locator('#quizResult').textContent(),/Answers changed/);assert.equal(await page.locator('#feedback1').textContent(),'');await page.locator('#impressionQuiz [type=reset]').click();assert.equal(await page.locator('#impressionQuiz input:checked').count(),0);assert.equal(await page.locator('#quizResult').textContent(),'');
 assert.equal(await page.locator('#teacherTools').isVisible(),false);assert.equal(await page.locator('#transcriptText').textContent(),'');
 await page.evaluate(()=>{window.__testUser=null;window.JaraLinguaAuth={getUser:()=>window.__testUser};window.JaraLinguaCurrentUser=null;});
 for(const role of ['student','teacher','admin']){
  transcriptRole=role;const done=page.waitForResponse(host+'/api/intermediate2/unit5-first-impression/transcript');await page.evaluate(role=>{window.__testUser={credential:'test-'+role,provider:'local'};window.dispatchEvent(new Event('jaralingua:auth-changed'));},role);await done;
  if(role==='student'){assert.equal(await page.locator('#teacherTools').isVisible(),false);assert.equal(await page.locator('#transcriptText').textContent(),'');continue;}
  await page.locator('#transcriptToggle').waitFor({state:'visible'});await page.locator('#transcriptToggle').click();assert.equal(await page.locator('#transcriptText p:visible').count(),12);assert.equal(await page.locator('#transcriptToggle').getAttribute('aria-expanded'),'true');
  if(width===390||width===1440)await page.locator('#teacherTools').screenshot({path:'tmp/unit5-listening/'+engine+'-teacher-'+width+'.png'});
  await page.locator('#transcriptToggle').click();assert.equal(await page.locator('#teacherTranscript').isVisible(),false);
 }
 await page.evaluate(()=>{window.__testUser=null;window.dispatchEvent(new Event('jaralingua:auth-changed'));});assert.equal(await page.locator('#teacherTools').isVisible(),false);assert.equal(await page.locator('#transcriptText').textContent(),'');
 if(width===1440){transcriptRole='teacher';transcriptDelay=400;const response=page.waitForResponse(host+'/api/intermediate2/unit5-first-impression/transcript');await page.evaluate(()=>{window.__testUser={credential:'test-teacher',provider:'local'};window.dispatchEvent(new Event('jaralingua:auth-changed'));window.__testUser=null;window.dispatchEvent(new Event('jaralingua:auth-changed'));});await response;await page.waitForTimeout(100);assert.equal(await page.locator('#teacherTools').isVisible(),false);assert.equal(await page.locator('#transcriptText').textContent(),'');transcriptDelay=0;}

 await page.locator('#toggleTimer').click();await page.evaluate(()=>window.__offset+=10000);await page.waitForFunction(()=>document.querySelector('#speakingTimer').textContent==='00:35');await page.locator('#toggleTimer').click();assert.equal(await page.locator('#toggleTimer').textContent(),'Continue');await page.locator('#toggleTimer').click();await page.evaluate(()=>window.__offset+=36000);await page.waitForFunction(()=>document.querySelector('#speakingTimer').textContent==='00:00');await page.locator('#toggleTimer').click();assert.equal(await page.locator('#speakingTimer').textContent(),'00:45');await page.locator('#resetTimer').click();assert.equal(await page.locator('#toggleTimer').textContent(),'Start 45 seconds');
 await page.locator('#impressionSearch').fill('zzzznothing');assert.equal(await page.locator('.ie2-search-item:visible').count(),0);await page.locator('[data-course-search-clear]').click();assert(await page.locator('#listening-player').isVisible());
 assert.equal(await page.locator('#impressionQuiz').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),width>1100?3:width>760?2:1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);
 assert.deepEqual(errors,[]);if(width===390||width===1440){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'tmp/unit5-listening/'+engine+'-hero-'+width+'.jpg',type:'jpeg'});await page.locator('#listening-player').scrollIntoViewIfNeeded();await page.screenshot({path:'tmp/unit5-listening/'+engine+'-player-'+width+'.jpg',type:'jpeg'})}
 console.log(engine,width,'PASS: audio, 13 models (all at 1440), questions, transcript, timer, QR, auth, layout');
 if(width===1440){await page.goto(host+'/ingles/intermediate-2/listening-library.html#unit-5-listenings',{waitUntil:'networkidle'});await page.locator('#unit5ListeningGrid .ie2-lab-card').waitFor();assert.equal(await page.locator('#unit-5-listenings').evaluate(e=>e.open),true);assert.equal(await page.locator('#listeningTotal').textContent(),'4');await page.locator('#listeningLibrarySearch').fill('Sam');assert.equal(await page.locator('.ie2-lab-card:visible').count(),1);assert.equal(await page.locator('#unit5ListeningGrid a').getAttribute('href'),pathname);await page.locator('#listeningLibraryClear').click();assert.equal(await page.locator('#listeningResultCount').textContent(),'4 listenings');await page.goto(host+'/ingles/intermediate-2/practice-lab.html#unit-5-folder',{waitUntil:'networkidle'});await page.locator('#unit5ActivityGrid .ie2-lab-card').first().waitFor();assert.equal(await page.locator('#labActivityTotal').textContent(),'23');assert.equal(await page.locator('#unit5ActivityCount').textContent(),'2 activities');await page.locator('#practiceLabSearch').fill('Sam');assert.equal(await page.locator('.ie2-lab-card:visible').count(),1);assert.equal(await page.locator('#unit5ActivityGrid a.ie2-lab-card:visible').getAttribute('href'),pathname);console.log('Catalogs PASS: 23 released activities; 4 listenings');}
 await page.close();
}
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
